### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by cconroy20** [amusecode/amuse#1004]
Hi,
I'm new to amuse and am struggling to get the programs installed.  I am installing on a cluster, and have followed the instructions here: https://github.com/amusecode/amuse/blob/main/doc/install/howto-install-AMUSE.rst 

Everything seems to install fine (no errors thrown).

this is the current error I'm getting: 

Traceback (most recent call last):
  File "/n/holystore01/LABS/conroy_lab/Lab/cconroy/nbody/evolution_cluster.py", line 308, in <module>
    t, x, y, z = evolution.evolution_of_the_cluster(star_cluster)
  File "/n/holystore01/LABS/conroy_lab/Lab/cconroy/nbody/evolution_cluster.py", line 233, in evolution_of_the_cluster
    gravity.parameters.timestep = self.dt_bridge/3.
  File "/n/home12/cconroy/amuse-env2/lib/python3.10/site-packages/amuse/datamodel/parameters.py", line 338, in __setattr__
    f"'{type(self._original()).__name__}' object"
TypeError: 'ParametersWithDocs' object is not callable

any help would be most appreciated!
thanks,
Charlie

**Comment by LourensVeen** [comment]
Hi Charlie,

Clusters are always tricky, especially when they're HPC clusters :upside_down_face: . Just to check, I guess you followed the "Installation on HPC systems using modules (tested for Snellius)" instructions at the bottom of that page, right? And you're running an unmodified version of https://github.com/amusecode/amuse/blob/main/examples/examples_galaxia/evolution_cluster.py ?

I haven't seen this before, but I'm looking into it.

**Comment by rieder** [comment]
Hi,

Yes that makes it clear where the error originated - ph4 doesn't have a timestep parameter that is settable, it calculates this by itself.
If you remove that line it should be ok.

Steven

**Comment by rieder** [comment]
The error message could be clearer...

**Comment by cconroy20** [comment]
thanks for the help!  things are working now...

**Comment by cconroy20** [comment]
if I can hijack my own thread: can someone explain what the file binev.data is producing?  Or point me to the relevant documentation?  thanks!

**Comment by rieder** [comment]
This file relates to binary star evolution, and is created by the SeBa code.

**Comment by cconroy20** [comment]
I gather the relevant documentation is here: https://github.com/amusecode/SeBa/blob/main/README.md#Understanding-the-SeBa-output ?  If so, I'm still struggling to interpret the output.  e.g., the first few lines of the binev.data file are:

1
 8 0 0 0 0 0 0
 0 0.02 25.5175 25.6734 10.3308 9.89162 3.03797 816.825 816.825 3.525 4.87956 -2.32945 -5.11945 0 0 0
1
 18 0 0 0 0 0 0
 0 0.02 25.5175 0 10.3308 1.26536 1.26536 2.0085e-05 2.0085e-05 6.91499 3.22098 -18.1077 14.8053 0 12 0.1
1
 18 0 0 0 0 0 0
 0 0.02 25.5175 0 10.3308 1.26536 1.26536 2.0085e-05 2.0085e-05 6.91499 3.22098 -18.1077 14.8053 0 12 0.1
 
when is the binary evolution info printed to this file?  only when "interesting" things happen in the binary evolution?
thanks

**Comment by cconroy20** [comment]
thanks.  Does amuse label in some way which stars are in binaries (and who their companion is), or does this need to be identified in post-processing?
