### ISSUE TITLE
make_secondaries

### ISSUE THREAD

**Issue by cconroy20** [amusecode/amuse#1009]
I'm trying to use make_secondaries in kira.py to generate a binary star population that I can insert into evolution_cluster.py.  Everything is going ok except that the line:
single_stars = center_of_masses-binaries
results in the single_stars object having fewer attributes than the Particles() object, so that I can then not do:
all_stars = single_stars + binaries
the specific error message is: "Can't create new subset from particles belonging to separate particle sets. Try creating a superset instead."

how can I get single_stars above to have the same particle set?  I'm surprised that it doesn't.

thanks!

**Comment by spzwart** [comment]
Dear Charlie,

It is not clear to my why you would like to do this.
The routine
def make_secondaries
returns three particle sets.
A list of single stars
A list of binary members (also stars with the same properties of the single
stars, except their coordinates are adjusted to make them binary members)
A list of binary center of masses (which has a number of properties,
different than stars, well they are different things).

Adding the single_stars with the binary_members
I can imagine,
but adding the single_stars with the binary_center_of_masses,
I cannot.

Cheers,
Simon

**Comment by cconroy20** [comment]
Hi Simon,

Indeed, I am trying to do exactly what you suggest - adding the single_stars and the singles_in_binaries.

In make_secondaries I have added a single line:
all_stars = single_stars + singles_in_binaries
prior to the return statement, which throws the error mentioned above.

As far as I can tell, in evolution_cluster.py, at some point the number of attributes in the star_cluster particle object is increased, so that when I feed the star_cluster particles into make_secondaries, that object clashes with the newly formed singles_in_binaries object (the latter comes directly from the Particles datamodel).

the star_cluster object has several additional attributes not in the Particles data model, such as:
add_indices_in_attribute_storage
remove_indices_in_attribute_storage
get_state_at_timestamp

Any thoughts on what could be going on here?

thanks
Charlie

**Comment by cconroy20** [comment]
I think I see part of what is going on:

the single_stars are defined in make_secondaries via:
single_stars = center_of_masses-binaries
(which is confusing terminology - the "center_of_masses" object is just the input list of particles to the program)
and binaries is defined by:
binaries = center_of_masses.random_sample(Nbin)
now, for whatever reason, the number of attributes of center_of_masses and binaries is different (195 vs. 186).  Something about the "random_sample" function seems to remove some of the attributes.  When this occurs, the single_stars object inherits the fewer attributes in the operation above.

**Comment by spzwart** [comment]
I guess, I see what you mean, Charlie,

Try the following script, with and without "--add" as command line option.
I replaced
stars += other_stars
with
stars.add_particles(other_stars)
Does this solve your problem?

Simon

**Comment by cconroy20** [comment]
yes that seems to work - thanks!

and wow: the code runs so much slower with binaries!

**Comment by spzwart** [comment]
Yes Charlie,

there is a good reason people try to run without them. so fat I know still
only one paper with primotdial triples....
good luck,
Simon
