### ISSUE TITLE
multithreading 

### ISSUE THREAD

**Issue by cconroy20** [amusecode/amuse#1010]
Hi,

I'm trying to get a sense of how the run time should scale with the number of cores (CPUs, not GPUs).  For the pure N body case, is there any benefit to running on multiple cores?  How is the splitting of the computational cost done in this case?  I understand the basics of how the splitting is done in tree(PM) and related codes, but I am not very familiar with direct N body codes.

thanks
Charlie

**Comment by rieder** [comment]
Hi,

With PeTar I definitely would expect a slowdown rather than a speedup with only 1000 particles. 
PeTar is written for orders of magnitude more particles. Its overhead will dominate.

**Comment by cconroy20** [comment]
ah ok - very good to know!  Can you recommend another solver that has better scaling with N_CPU for ~1e4 particles?
