### ISSUE TITLE
Issue With Multiples Module

### ISSUE THREAD

**Issue by fredt00** [amusecode/amuse#1029]
Hi! 

I've been trying to simulate a star cluster with primordial binaries using ph4, smallN, Kepler and the multiples module. However I've noticed that this runs at the same speed as ph4 by itself. Looking further into this, I've noticed that when I run the simulation Kepler_worker and smallN_worker both run but use almost zero memory and cpu time suggesting they aren't working properly.

For testing this I've been using this amuse-masc example script: https://github.com/rieder/amuse-masc/blob/main/examples/MASC%20and%20Multiples.ipynb

According to multiples_code.get_total_multiple_energy() there are zero multiples, even if I increase the binary fraction towards 100% or reduce the semi major axis which makes the code grind to a halt. Despite this, Kepler and smallN continue to use the same negligible cpu time. Could this be a problem with my installation? Any help would be appreciated!

Thanks,
Fred

**Comment by rieder** [comment]
Sorry to get to this late.

Did you set a(n interaction) radius for the stars? This is required for multiples to work, if it is non-existent or set to a very small value, the gravity code will do all the work - resulting in the behaviour that you are seeing.

**Comment by fredt00** [comment]
Ah yes, increasing the radius to a few AU makes smalln and Kepler work correctly with interactions handled with multiples. Thank you!
