### ISSUE TITLE
Problem installing amuse-brutus

### ISSUE THREAD

**Issue by carpark421** [amusecode/amuse#1037]
Please can someone offer an insight into how to fix my problem?
The output is:

      error in call, tail output:
      
      amusifier --type=c interface.py BrutusInterface -o worker_code.cc
      amusifier --type=H -i amuse.community.interface.stopping_conditions.StoppingConditionInterface interface.py BrutusInterface -o worker_code.h
      make -C src all CXXFLAGS="-g -O2 -fno-common  -I./mpfrc++     -std=c++0x -I../mpfrc++"
      g++ -O1 -g -O2 -fno-common  -I./mpfrc++     -std=c++0x -I../mpfrc++ -c Star.cpp
      In file included from Star.cpp:1:
      In file included from ./Star.h:6:
      ../mpfrc++/mpreal.h:125:10: fatal error: 'mpfr.h' file not found
      #include <mpfr.h>
               ^~~~~~~~
      1 error generated.
      make[1]: *** [Star.o] Error 1
      make: *** [src/libbrutus.a] Error 2

**Comment by spzwart** [comment]
Looks like you have not installed the mpfr libraries...

Simon

**Comment by carpark421** [comment]
I did `brew install mpfr` before receiving this output. Would that not have tried to fix it?

**Comment by rieder** [comment]
If you installed mpfr after installing amuse-framework, it would not be present in the amuse config, which would lead to this error.

**Comment by carpark421** [comment]
Yes, what I did was naïvely uninstall amuse-framework and mpfr. I then installed mpfr, amuse-framework, and then finally tried `pip install amuse-brutus`: same error.

**Comment by rieder** [comment]
Unfortunately this will indeed fail, because pip packages are cached after building them. You would have to remove the cached pip wheels (I think in ~/Library/cache/pip, but please check), and then re-install amuse-framework.

**Comment by carpark421** [comment]
I thought that would be the case, so, when uninstalling the stuff, I did this: `rm -r ~/Library/Caches/pip/wheels/*`
