### ISSUE TITLE
Create a lean AMUSE distribution?

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#107]
AMUSE in its current form is a big collection of codes. This makes sense when installing it system-wide, but this is not per se the best option. My workflow is increasingly so that I have a separate installation of AMUSE for each of my projects. This allows me to "freeze" the installation for that project, which makes it that much easier to reproduce results later on.

For such a use case, AMUSE is somewhat "bloated". It would be nice to have a "lean" AMUSE installation. This could consist of core-AMUSE, where all community codes (and their datafiles) would be DOWNLOAD_ONLY-style codes. 

There are of course several issues that should be resolved in order to make this work nicely:
- Python3-AMUSE currently needs to install community codes as dist-packages, this would make things difficult
- Where would community codes be stored?
- Error message when trying to use a community code could ask user to install respective community code

(add other issues below)

**Comment by ipelupessy** [comment]
This is related to the longterm plan to make the base framework more domain agnostic

**Comment by rieder** [comment]
Yes, it would fit in with that :).

**Comment by rieder** [comment]
I just got the AMUSE minimal distribution working on my iPad/iPhone, within the Pythonista app.
This does not support running any of the compiled community codes, but all purely python code works (creating initial conditions, plotting data, analysing snapshots etc.). 
This is another argument for making an official “minimal” version, since it could make AMUSE much more available to people.

**Comment by rieder** [comment]
Actually, I think it may be possible to provide a version with pre-compiled codes for iOS...

**Comment by rieder** [comment]
We could probably learn from https://github.com/vaexio/vaex (@maartenbreddels) how to split a package in multiple sub-packages.

**Comment by rieder** [comment]
I think this is solved by #390.
