### ISSUE TITLE
PC restarts when using Amuse AI on 6800XT

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [amusecode/amuse#1073]
**Describe the bug**
Using AMUSE AI for a couple of minutes make my PC reboot.

**To Reproduce**
My PC configuration is:
13700k (stock settings, always stable, 0x129 microcode)
6800XT (stock settings)

**Expected behavior**
My PC should not reboot when using Amuse AI.
No other program or even stress test on either CPU or GPU has ever made my PC reboot.

**Environment (please complete the following information):**
 - OS and version: Windows 11

**Additional context**

**Comment by rieder** [comment]
This has absolutely nothing to do with this particular AMUSE.

**Comment by LourensVeen** [comment]
I've actually managed to get my AMD GPU all confused running this (astrophysics) AMUSE on it, so I'm not entirely surprised, but you'll want to take this to TensorStack.ai it seems. They seem to have a contact form at https://www.tensorstack.ai/contact
