### ISSUE TITLE
Bonsai and Pikachu no longer working

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#115]
On my computer (Ubuntu 16.10, Cuda 8.0, GCC 5.4.1, GeForce GTX 970), Bonsai and Pikachu tests fail to run.
Both give errors like "Received reply for call id 0 but expected XXX" (the number XXX seems to change at random).

**Comment by spzwart** [comment]
Dear Steven,

this is quite unfortunate. I will ask Masaki to have a look at it.

Cheers,

Simon

**Comment by rieder** [comment]
HiGPUs has similar (and more) issues. My guess is that CUDA 8.0 is somehow incompatible with earlier versions...

**Comment by rieder** [comment]
In Bonsai, the offending code seems to be the 
`load_source(hKernelFilename, ptxSource)`
line in "my_cuda.h"
ptxSource remains an empty string after this call, and the following CU_SAFE_CALL fails.

**Comment by rieder** [comment]
"hKernelFilename" is an existing ptx file though.

**Comment by ipelupessy** [comment]
is this related to #116?

**Comment by rieder** [comment]
Yes, #116 is a partial fix for this. I'll test it on Pikachu later.
