### ISSUE TITLE
Missing: interface for Brutus

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#124]
I noticed that there isn't an interface for Brutus yet.
Tjarda informed me that Adaptb is an older version of that, but basically obsolete.
Maybe this interface can be updated to one for Brutus?

**Comment by ipelupessy** [comment]
I think Brutus is going to be in AMUSE eventually/shortly (but its up to Tjarda..)

**Comment by ipelupessy** [comment]
work in progress #129

**Comment by rieder** [comment]
Awesome.

**Comment by ipelupessy** [comment]
fixed by #130
