### ISSUE TITLE
Problems with AMUSE with a VPN enabled

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#128]
Amuse and Python3 don't play nice together yet. While installing it in a virtualenv seems to work for me now, I can't run anything. When I add particles to a code, the code freezes and nothing happens anymore...
```python
from amuse.lab import *
g = ph4()
p = new_plummer_model(100)
g.particles.add_particles(p)  # the code freezes after this point, no output is generated
print(g.particles[0].x)
g.evolve_model(0.02|nbody_system.time)
print(g.particles[0].x)
```

**Comment by rieder** [comment]
I installed in a py36 venv, using this method:
```bash
touch amuse.cfg
./configure
python3 setup.py install
```

**Comment by rieder** [comment]
This problem is apparently only occurring when I run with a VPN enabled. Somehow this freezes AMUSE...

**Comment by ipelupessy** [comment]
are you sure the same problem does not occur pith python 2 and a VPN enabled?

**Comment by rieder** [comment]
It seems to, yes...

**Comment by ipelupessy** [comment]
can you do any other communication with the code (say ```print g.parameters```)??

**Comment by rieder** [comment]
No, all of that results in an unresponsive code and python waiting for that code...

**Comment by ipelupessy** [comment]
have you recently tried this again?

**Comment by rieder** [comment]
Just now, the problem persists...

**Comment by rieder** [comment]
just a note: this is still not working.

**Comment by rieder** [comment]
Also, running with `mpirun --mca btl_tcp_if_include lo0 -n 1 python test.py` works.

**Comment by rieder** [comment]
seems like MPI is choosing the "wrong" network to work on...

**Comment by rieder** [comment]
This seems related to the problem with running AMUSE without a network. The solutions above also work in that case.

**Comment by ipelupessy** [comment]
workaround available?
