### ISSUE TITLE
Flatter AMUSE namespace?

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#132]
The AMUSE namespace is not all that easy to remember at the moment, and different from what is used in other major projects.

For example:
```python
# Expected:
import amuse.units
x = 1 | units.cm
# this does not work

# Actual:
from amuse.units import units
x = 1 | units.cm
```

and:
```python
from amuse.datamodel import Particles
```
(which I always forget)

This leads to the use of things like 
```python
from amuse.lab import *
```
which are not at all ideal... 

I would suggest we try to make the AMUSE namespace somewhat flatter, in the way that projects like astropy/numpy/scipy and others work. 

E.g.:
```python
# import everything under amuse namespace
import amuse 
# or, for a shorter namespace:
import amuse as am

particle = amuse.Particle()
particle.x = 1 | amuse.units.cm
```
```python
# imports units directly
import amuse.units 
x = 1 | units.cm
```

Similarly, we could then have (these are suggestions)
```python
# import particles
import amuse.particles 
```
```python
# import all interfaces
import amuse.interfaces
# or only one
import amuse.interfaces.hermite0 as Hermite
```

**Comment by ipelupessy** [comment]
hmm, I don't think things like:
```
  from amuse.units
  d=1| units.m
```
are supposed to work. I think 
```
  from amuse import units
  d=1|units.m
```
could be nice, but then you would also want:
```
  from amuse import constants
```
not sure if this will fit...in any case you would only want changes that don't break existing
scripts...as a side node, I consider things like
```
  import numpy as np
  import amuse as am
```
bad form, don't do it...

**Comment by rieder** [comment]
Regarding the latter point: in the case of numpy, they use "np" _everywhere_ in their documentation...

**Comment by ipelupessy** [comment]
maybe something like: https://github.com/ipelupessy/amuse/tree/simplified_namespaces

 I am not sure if it will work 100%, and in any case in general I am not in favour of obfuscation of namespace, in case you didn't notice;-)

**Comment by arjenve** [comment]
Yes, moving all that is now in lab to the amuse main __init__ would be a good idea, and allowing
for "from amuse import *" .  
I do not want the renaming to am in our examples like numpy always seems to do in their examples, (why not call the package np?). 
But yes, having from amuse import <name> is helpful (btw we already do this for datamodel where we import particles etc into the datamodel __init__)

**Comment by arjenve** [comment]
BTW instead of interfaces, I would name these the codes.

**Comment by rieder** [comment]
Ok, great! 
"codes" is probably better than "interfaces", yes. 
I would try to avoid 
```python
from amuse import *
```
as it is unclear to the user what this specifically imports, but being able to import _specific_ things directly from amuse (if you want to avoid the amuse namespace) would be very helpful.

**Comment by rieder** [comment]
#312 relates to this

**Comment by rieder** [comment]
After a discussion today:

- amuse.lab should have all the basics available for importing (generally speaking: all the things that are required for the examples in the book)
- Community codes should be available in lab.py
- Community codes should be available under their current name (with not necessarily predictable capitalisation) as well as a spelling with only the first letter capitalised (e.g. Bhtree, Simplex, Ph4).

**Comment by ipelupessy** [comment]
I think this has been mostly fixed
