### ISSUE TITLE
python3 install scripts not up to date with python 2

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#134]
install3.py in doc/install trails install.py somewhat

(but needs to be tested)

**Comment by ipelupessy** [comment]
a single script would obviously be easier to maintain, especially if it would also be tested...

**Comment by ipelupessy** [comment]
yes and yes, @isazi is working on this!

**Comment by rieder** [comment]
I think this is done, right?

**Comment by ipelupessy** [comment]
not done yet (but less important now)

**Comment by rieder** [comment]
Is this still relevant? I think it can be closed...

**Comment by ipelupessy** [comment]
I think it is: the python2 script can be removed, but the prerequisites in the python3 script need to be updated (older)..its not high priority though..

**Comment by ipelupessy** [comment]
we moved to python3 fully and the install scripts where fixed
