### ISSUE TITLE
Amuse binary releases

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#135]
The latest binary release on amusecode.org is from late 2014, so it's a bit out of date... Are binary releases still built? If so, where can they be found? And are there also python3 binary releases?

**Comment by ipelupessy** [comment]
the binary build machine is indeed down/ broken... don't think there ever were python3 binaries...I have build binaries myself not so long ago, so the build scripts should still work

**Comment by rieder** [comment]
Ok, but is there a plan to update the binary releases on the website soon? The AMUSE v10.0 releases there date from 2014, and they're the easiest way to access AMUSE... An update would be quite welcome.

**Comment by ipelupessy** [comment]
binary releases not a priority (container builds, packaging are a better alternative )
