### ISSUE TITLE
Update of prerequisite installation commands for UBUNTU  needed

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#140]
The prerequisite installation commands for Ubuntu is outdated as some of the
packages have been either updated or removed from official package
repositories. I faced this issue while installing them and had to manually
install some of them. If you want, I can provide you with the updated
commands & manual installation instructions for the docs.

( copied from maillist)

**Comment by sr6033** [comment]
I have sent a pull request with the updated instructions.

**Comment by ipelupessy** [comment]
ok, thanks - I have made a new leaner fix for this (and tested it). it should work now (at least on the newest ubuntu...) (fixed by 7a576a2)
