### ISSUE TITLE
Using tags (v2.0e_nbody_sample_working tag?)

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#143]
its not bothering me, but my guess this tag was created by accident?
(or there might be a rationale for this, maybe a way to distribute definite versions?)

**Comment by rieder** [comment]
I didn't create the tag, as far as I can remember... 

But yes, a tag would be very useful to identify release versions - if we would choose to use them again? The last release was a few years ago...
Personally, I store the identifier of the most recent commit for my simulations. A tag just makes it easier to identify specific commits.

**Comment by rieder** [comment]
Wait, I did create that tag. It's referring to the FDPS branch, which is still not merged (and shouldn't yet be merged). Not sure why it's visible elsewhere... I'll see if I can delete it.
