### ISSUE TITLE
Tracker: AMUSE and Python3

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#145]
Tracker for all issues related to making AMUSE work flawlessly with Python3.
Please add other issues below.

Related issues:
#131 #134 #186

**Comment by ipelupessy** [comment]
#128

**Comment by rieder** [comment]
#128 is not py3 specific.

**Comment by rieder** [comment]
Installation method for Amuse with Python3: https://github.com/rieder/amuse/wiki/Installation-on-macOS-with-Python3

**Comment by rieder** [comment]
#190

**Comment by rieder** [comment]
Closed - using a label for this is much easier.
