### ISSUE TITLE
cython interfaces?

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#148]
When I build an AMUSE community code, AMUSE generally attempts to create two versions of the workers: the default one and a cython version.
The cython versions always fail to build for me. Is this expected (as work-in-progress), or should they compile?

What is the difference between these worker types?

**Comment by ipelupessy** [comment]
I think they should work with cython installed, but I have seen them fail..its work in progress..Arjen knows more...

**Comment by rieder** [comment]
Well, I do have cython installed... Are there other dependencies? Or do I need some special configure options?
An example error I get, for the rebound cython worker:

> rebound_cython.cc:435:31: fatal error: numpy/arrayobject.h: No such file or directory

**Comment by ipelupessy** [comment]
ok, I have tried (latest cython 0.25.2, but I get a different error:
```
rebound_cython.pyx:8:8: 'mpi4py/MPI.pxd' not found
```
and then complaints about mpi4py..I get this even after rebuilding and reinstalling mpi4py (there is a I mpi4py/MPI.pxd somewhere)...think we need some here here

**Comment by ipelupessy** [comment]
although: "gcc should have access to the NumPy C header files so if they are not installed at /usr/include/numpy or similar you may need to pass another option for those" might solve your issue? (from http://docs.cython.org/en/latest/src/userguide/numpy_tutorial.html )

**Comment by ipelupessy** [comment]
btw, the idea of this cython workers is to be able to link codes directly as libraries (this seams defeating the point of AMUSE, however the idea is that eventually you have a python layer "on the other side" too, which allows for more flexibility...)

**Comment by arjenve** [comment]
Yes, the whole Cython thing is an experiment, I'm trying to find ways to get the same kind of functionality using different techniques, so far no luck yet unfortunately. ( the case being we have limited number of nodes, need multiple codes, but not all the time, with Cython (and shared libraries) we can use 10 codes as on one node and have it count as one process, although everything will be sequential and 10 x slower). The other option is to swap in and out data + parameters  for a code, this I have not made fast enough yet. So basically the cython code will go away. BTW. the problems you are seeing may have to do with using linux distributions , check if the development version is installed.

**Comment by rieder** [comment]
Ok, thanks!
I didn't realise it was an experiment only, since this is the master branch... 
I was/am seeing this on both Mac and Linux machines, with the default cython.
