### ISSUE TITLE
" an index can only have a single ellipsis ('...')"

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#150]
the buildbot builds fail with the error in testing (a.o.):
```an index can only have a single ellipsis ('...')```
This is, i think, due to a new numpy version( 1.13.0). I think multiple ellipsis 
can be safely reduced to one (double ellipsis don't make sense anyway)

(if not possibly [:,:,0] was meant)

**Comment by ipelupessy** [comment]
I would also try to have a (virtual) test machine with a stable set of prerequisites installed..

**Comment by arjenve** [comment]
yes, numpy was updated yesterday and now these test fail, I'll look at it.

we do have test-system with stable set of prerequisites (the prerequisite tests, the binbuild)

**Comment by ipelupessy** [comment]
ok, thanks! 

(I think those two don't run the amuse test suite...)

**Comment by arjenve** [comment]
this is not the only problem btw. it also seems that arrays are not flattened any more + an error that reads: "only integer scalar arrays can be converted to a scalar index".

**Comment by ipelupessy** [comment]
I think the flattening should be examined carefully to see what exactly changed between numpy version, the integer scalar array error I don't understand (as far as i can see, it should yield an integer index array...)

**Comment by arjenve** [comment]
well it is only one test, and should be flattened there so this one is OK.

the other is new in that you can no longer use a 1 element array as an index (multi element work fine).
(I fixed the test, but I think numpy is not right on this point).

another is in random.uniform(a,b,size), the size now has to be an integer (we had a float here which was run through numpy.ciel) also fixed.

**Comment by ipelupessy** [comment]
you sure about the second one (i tested, seems fine)

**Comment by arjenve** [comment]
no sure, as I got the info from google....

turns out it is like this, a numpy 1 element array can no longer be used as a scalar in indexing operations for lists

so, make a python list:

x = list(range(10))

and do:

x[numpy.array([1])]

this will work in older numpies but not in 1.13

**Comment by ipelupessy** [comment]
ok, its about indexing lists (not numpy arrays)..hadn't understood that...
it makes sense to not allow it - it wouldn't have worked before if it had length more than 1..)

**Comment by ipelupessy** [comment]
better change the output of the read_input_file to numpy arrays in the simplex test though..

**Comment by ipelupessy** [comment]
closing this; i still think there should be test machines with older numpy versions, adding issue for that..
