### ISSUE TITLE
tests for numpy <1.13.0

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#153]
this is a reminder that test machines with earlier numpy versions are needed...

**Comment by ipelupessy** [comment]
its not strictly a code issue, but we have no seperate issue tracker for buildbot issues...

**Comment by rieder** [comment]
You can make a label for those types of issues? :)

**Comment by egpbos** [comment]
Let's make that into it's own issue @rieder :)

**Comment by rieder** [comment]
I don't think this is needed anymore. Does anyone use ancient numpy versions (and does AMUSE even work with these now)?
I'll close this in a week if there are no objections.

**Comment by ipelupessy** [comment]
yea, maybe we should advance the minimum version requirement

**Comment by rieder** [comment]
Yeah - I think to 1.19 as that’s the last version to support Python 3.6 (which we also support as minimum version).

**Comment by ipelupessy** [comment]
just close, easy to do iff we ever need it
