### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by tianzhijia** [amusecode/amuse#158]
```
binaries, stars = generate_initial_population_grid(
        0.5 | units.MSun, 1.5 | units.MSun, 3, #mass range
        0.9, 0.9, 1,                           #mass ratios range
        10 | units.RSun, 100 | units.RSun, 120,    #semi major axis range
        0.0 , 1.0, 120                          #eccentricity range
    )
```

> ... Traceback (most recent call last):
>   File "<stdin>", line 5, in <module>
>   File "binary_population_synthesis.py", line 110, in generate_initial_population_grid
>     grid = multidimensional_meshgrid(primary_masses, mass_ratios, separations, eccentricities)
>   File "binary_population_synthesis.py", line 42, in multidimensional_meshgrid
>     array = array.reshape(shape)
> TypeError: 'numpy.float64' 

code from `binary_population_synthesis.py`
error about numpy appears when running generate_initial_population_grid, 
Anyone who knows how to fix it? Thx

FYI. Install amuse on Mac os X 10.11 following [http://www.amusecode.org/doc/install/install-prerequisites-osx.html]

**Comment by rieder** [comment]
Fixed.
