### ISSUE TITLE
rfi/channel.py: is_threaded() function broken and not needed?

### ISSUE THREAD

**Issue by fjansson** [amusecode/amuse#165]
`class MpiChannel`  in rfi/channel.py defines the following two classmethods:
```
def is_multithreading_supported(cls):
        return MPI.Query_thread() == MPI.THREAD_MULTIPLE

def is_threaded(cls):
        #We want this for backwards compatibility with mpi4py versions < 2.0.0                                                                                                                             
        try:
            return rc.threaded
        except AttributeError:
            return rc.threads
```
It seems the second tries to answer the same question as the first, but in a less robust way. Is it needed at all? Also, it doesn't work, but results in   `NameError: global name 'rc' is not defined`.
I think the first function does the right thing, and queries the actual threading support provided. The rc module on the other hand seems to contain the requested threading level, which the MPI library then may or may not provide.

I stumbled onto this because I make amuse calls to different worker codes concurrently from multiple python threads. This is safe only if MPI.Query_thread() == MPI.THREAD_MULTIPLE, which depends on the MPI library in use. A better way seems to be async amuse function calls (I couldn't find these in the documentation, though).

**Comment by ipelupessy** [comment]
it certainly is broken, the rc import from mpi4py was removed at some point.... is_threaded was used as far as i can see to determine whether to call Init or Init_thread..not sure whether this is no longer necessary or another bug... (the try..except was added because some people ran into the threaded<-threads change...

**Comment by arjenve** [comment]
We used to do our own initialization of MPI, but this was too complex and unnecessary, so Init was removed and also the use of the is_threaded call became obsolute (and not working apparently).
Please use "is_multithreading_supported", I'll fix is_threaded but also add a comment!

**Comment by arjenve** [comment]
BTW, these 2 functions do have different semantics, "is_threaded" can be run without mpi being initialized and is actually more "should have threads, if possible", is_threading_supported can run after mpi initialization and will report the actual support for threads in the MPI implementation

**Comment by ipelupessy** [comment]
is the print in 4c6da93 there on purpose?

**Comment by arjenve** [comment]
Ofcourse!

**Comment by fjansson** [comment]
The semantics of is_threaded confused me, that's part of why I opened this issue. As far as I know, mpi4py will by default try to initialize with the highest level of thread support, unless rc.threaded is explicitly set to something lower before importing mpi4py.MPI. So is_threaded will normally return true, even if one then ends up getting some lower level of thread support.
Does anyone actually use or need is_threaded, or could it be removed?

**Comment by rieder** [comment]
Is this solved?

**Comment by ipelupessy** [comment]
should be solved
