### ISSUE TITLE
AMUSE master branch

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#166]
Currently, all work is merged directly into the 'master' branch of AMUSE. 
This is leading to some troubles, at times, like accidental merges that affect unintended files (as happened to me just now). It might be good to consider how we want to deal with this in the future.

Things we could consider:
- Use 'master' branch only for AMUSE releases (as done in the past, but not since release 10)
- Allow merging into the 'master' branch only via pull requests, describing what the changes do
- Allow special project branches with individual rules (e.g. a 'textbook' branch, 'cython' branch, 'python3' branch etc) for testing and development.

Other ideas?

**Comment by ipelupessy** [comment]
as a side note: the faulty commits undid (in a way I don't understand) a commit (of 22 aug)  on support/distribute/binbuild/build/build_libraries.py
and touched /test/ext_tests/test_orbital_elements.py
it doesn't show up in the 'changed' files..
only diffing:
```git diff -r 609675c6d2e59a983bd305ab3f9c481d6973e29b -r 668ed7032a564242021e95f16882ea008eb94779```
I am hesitating to fix it before I understand what happened here

**Comment by ipelupessy** [comment]
for some reason these files were not included in merge 2f1ebbb1e7c37a82a95a2d8f5bc0f13724dd0f48

**Comment by ipelupessy** [comment]
no further action necessary
