### ISSUE TITLE
Update amuse.units.optparse to use argparse

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#172]
Out of curiosity, why is there a module amuse.units.optparse? 
Is this different from the standard python optparse (which is since Python 2.7 deprecated and replaced by argparse)?
And why is it in amuse.units? Seems a weird place for this...

**Comment by spzwart** [comment]
indeed Steven,
the amuse.units.optparse overloads the units into the standard python package. you can read about it in the amuse book.

Groeten,
Simon

----- Reply message -----

**Comment by rieder** [comment]
No rush though, optparse will not be removed any time soon. https://www.python.org/dev/peps/pep-0389/#deprecation-of-optparse

**Comment by rieder** [comment]
This should be fixed for AMUSE 13 as well.

**Comment by rieder** [comment]
I'll see if I can get it to convert strings. If this works I'll update the examples to that new method and add some deprecation warning to the current optparse method.

**Comment by rieder** [comment]
I've tested @ipelupessy's example above with #934 and it works with that change, so I think that's the way to go.

**Comment by rieder** [comment]
Fixed with #934!
