### ISSUE TITLE
Infinite loop in galaxy generation gendisk

### ISSUE THREAD

**Issue by jjfPCSI1** [amusecode/amuse#174]
Hello,

I've just spend some time installing amuse on MacOSX. After a few struggling, I finally managed to make it work (40 out of 43 codes built, 5 out of 6 libraries built). I'm trying to produce a test galaxy o I tried to run the code from this page: http://amusecode.org/doc/examples/applications/galaxy_merger.html

But when using it, gendisk seems to run in a loop using 100% CPU for a long long time even if I decrease the number of particles to a few hundreds.

```
PID    COMMAND      %CPU TIME     #TH   #WQ  #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE
38902  gendisk      99.8 00:12.83 1/1   0    12    24M    0B     0B     38892 38893 running
35677  Python       97.7 00:57.68 4/1   0    98    57M    0B     0B     35676 35676 running
```

Do you have any idea what could be going on and how to solve it ?

Thanks,

**Comment by spzwart** [comment]
Dear Jean-Julien,

The galaxy generator is sometimes a bit picky about initial conditions, 
and may get stuck in some internal source code look. I will check the 
example code you used, but for now I recommend using another script 
which has is sort of doing the same, except that it is better tested.

You can find the script in your amuse directory in: 
/examples/textbook/merge_two_galaxies.py

On my laptop it took 22 seconds to generate the two galaxies, and a few 
minutes longer to run, producing the attached figure.

Note, btw. A small typo (forgot to declare the parameter n_disk in line 
50 in the script) but which is now  corrected when you do a

%> git pull

The accompanying text can be found in the textbook Steve McMillan and I 
are writing. A preliminary version can be found at my web page under 
"Mission" (see chapter 5, section 2.5.4).

Cheers,

Simon

**Comment by jjfPCSI1** [comment]
Hello Simon,

Thanks for this quick answer.

Unfortunately, it does not solve the problem but I think that it comes from some parallelization issues. In both scripts, the call to `new_galactics_model` is the one that triggers `diskgen` which never ends (I let it run almost an hour before killing it)

After finally having amuse being installed (late, yesterday evening), I forgot to launch `nosetests` which is now running and seems also stuck after having launched several workers that would not stop their computations as you can see below.

```
PID    COMMAND      %CPU TIME     #TH   #WQ  #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE
40429  Python       64.7 52:08.63 3/1   0    78    156M   0B     16M    40429 35712 running
46400  Python       42.7 30:30.30 2/1   0    18    28M    0B     0B     46399 1     running
46405  Python       42.5 30:22.27 2/1   0    18    27M    0B     0B     46401 1     running
45957  smallN_worke 40.2 28:55.02 2/1   0    18    2364K  0B     0B     45956 1     running
46021  smallN_worke 40.2 28:50.33 2/1   0    18    2388K  0B     0B     46020 1     running
46027  smallN_worke 40.2 28:49.83 2/1   0    18    2364K  0B     0B     46026 1     running
45951  smallN_worke 40.2 28:51.28 2/1   0    18    2384K  0B     0B     45950 1     running
45985  smallN_worke 40.1 28:47.67 2/1   0    18    2384K  0B     0B     45984 1     running
45991  smallN_worke 40.1 28:45.52 2/1   0    18    2372K  0B     0B     45990 1     running
45997  smallN_worke 40.1 28:46.15 2/1   0    18    2392K  0B     0B     45996 1     running
45939  smallN_worke 40.1 28:47.42 2/1   0    18    2372K  0B     0B     45938 1     running
45933  smallN_worke 40.0 28:49.05 2/1   0    18    2408K  0B     0B     45932 1     running
45969  smallN_worke 40.0 28:44.92 2/1   0    18    2404K  0B     0B     45968 1     running
46146  ph4_worker   40.0 28:38.01 2/1   0    18    2476K  0B     0B     46145 1     running
45963  smallN_worke 40.0 28:46.44 2/1   0    18    2392K  0B     0B     45962 1     running
45945  smallN_worke 40.0 28:44.02 2/1   0    18    2376K  0B     0B     45944 1     running
45975  smallN_worke 40.0 28:42.01 2/1   0    18    2404K  0B     0B     45974 1     run
```

Hence the suspicion about parallelization being somewhat not well installed or recognized on my computer.
I will try to redo the amuse installation from scratch on another computer to see if I'm luckier when directly following the correct set of instructions. I'll keep you posted if it works (or not).

Cheers,

JJ

**Comment by rieder** [comment]
JJ,

Out of curiosity, can you try to run a different script that uses a community code (e.g. the HR track example)? If that runs fine, it's at least not the entire installation.
Also, how is your computer connected to a network? Direct internet connection, or with a VPN? I've experienced similar problems as yours with the latter enabled...

Steven

**Comment by jjfPCSI1** [comment]
Hello Steven,

The `test_HRdiagram_tracks.py` runs just fine and I get the right graph in the end. 
So at least some parts of the installation are working 😃 

No VPN: just plain direct internet connection via WiFi.

JJ

**Comment by ipelupessy** [comment]
I think it could be an issue with gendisk in combination with certain compilers. We are trying to reprodce it, but could you report the exact OS and compiler version?

another thing which you could try (but probably won't work) is to add change the random seed, add disk_random_seed=12345 or something to the arguments of new_galactics_model

**Comment by jjfPCSI1** [comment]
I'm on OS X.11.6 (El Capitan). More exactly

```
~>uname -a
Darwin hyperion.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
```

I followed the instructions in file `doc/install/install-prerequisites-osx.txt` concerning uninstalling any port that should be reinstalled after, then installed using `+gcc49` flag where it was given in the `port` commands and configured with
```

./configure --with-fftw=/opt/local \
                  MPICXX=mpicxx-openmpi-gcc49 MPICC=mpicc-openmpi-gcc49 \
                  MPIFC=mpif90-openmpi-gcc49 \
                  FC=gfortran-mp-4.9 PYTHON=python2.7 \
                  PREFIX=/opt/local CC=gcc-mp-4.9\
          CXX=g++-mp-4.9
```

I've just made the configuration again followed by a `make clean` and then `make` to be sure I didn't forget the last line whose indentation is a bit different, but it didn't do any difference (which tend to prove I didn't forget it).
The file `build.log` is attached if it could be of any help.

[build.log](https://github.com/amusecode/amuse/files/1407524/build.log)

I tried with the new seed but without any success. Here is the error message once I killed `gendisk` manually:

```
Traceback (most recent call last):
  File "merge_two_galaxies.py", line 84, in <module>
    galaxy1, galaxy2, converter = make_galaxies(**o.__dict__)
  File "merge_two_galaxies.py", line 28, in make_galaxies
    disk_random_seed=12345)
  File "/Users/jfleck/git/amuseJJ/src/amuse/ext/galactics_model.py", line 42, in __call__
    return _new_galactics_model(*args, **kwargs)
  File "/Users/jfleck/git/amuseJJ/src/amuse/ext/galactics_model.py", line 10, in _new_galactics_model
    instance.generate_particles()
  File "/Users/jfleck/git/amuseJJ/src/amuse/community/galactics/interface.py", line 883, in generate_particles
    result = self.overridden().generate_particles()
  File "/Users/jfleck/git/amuseJJ/src/amuse/support/methods.py", line 107, in __call__
    result = self.method(*list_arguments, **keyword_arguments)
  File "/Users/jfleck/git/amuseJJ/src/amuse/support/methods.py", line 107, in __call__
    result = self.method(*list_arguments, **keyword_arguments)
  File "/Users/jfleck/git/amuseJJ/src/amuse/support/methods.py", line 109, in __call__
    result = self.convert_result(result)
  File "/Users/jfleck/git/amuseJJ/src/amuse/support/methods.py", line 145, in convert_result
    return self.definition.convert_result(self, result)
  File "/Users/jfleck/git/amuseJJ/src/amuse/support/interface.py", line 628, in convert_result
    return self.handle_return_value(method, result)
  File "/Users/jfleck/git/amuseJJ/src/amuse/support/interface.py", line 571, in handle_as_unit
    unit.append_result_value(method, self, value, result)
  File "/Users/jfleck/git/amuseJJ/src/amuse/support/interface.py", line 60, in append_result_value
    self.convert_result_value(method, definition, value)
  File "/Users/jfleck/git/amuseJJ/src/amuse/support/interface.py", line 70, in convert_result_value
    definition.handle_errorcode(errorcode)
  File "/Users/jfleck/git/amuseJJ/src/amuse/support/interface.py", line 548, in handle_errorcode
    raise exceptions.AmuseException("Error when calling '{0}' of a '{1}', errorcode is {2}".format(self.name, type(self.wrapped_object).__name__, errorcode), errorcode)
amuse.support.exceptions.AmuseException: Error when calling 'generate_particles' of a 'GalactICs', errorcode is -2

```

The new version of Xcode just finished its installation on my other computer where I will reset the MacPorts due to change of OSX version so I will have a brand new MacPort with no interference of what I could have installed previously. If it succeeds, I will see if it's worth upgrading my laptop so that amuse could work on it.

**Comment by jjfPCSI1** [comment]
Bad news:

`Error: gcc49 is not supported on macOS High Sierra and Newer`

gcc5 is possible: is there any drawback to go this way (or gcc6 or gcc7) ?

**Comment by rieder** [comment]
macports gcc6 should work just fine (gcc5 too, haven't tested gcc7 yet).

**Comment by jjfPCSI1** [comment]
Unfortunately, there seems to be a bug in one of Apple system files (see https://trac.macports.org/ticket/54993) that prevents openmpi to compile (I tried all flavors of gcc just to be sure). The reparation is a bit tricky to risk on the family computer so I will have to wait until an update is issued (I hope it won't take too long).

**Comment by rieder** [comment]
Xcode 9.3 (when it's released, still in beta) finally solves the OpenMPI issue

**Comment by rieder** [comment]
Xcode 9.3 is now released, so the macports version of openmpi finally compiles under High Sierra. 
@jjfPCSI1 does this solve your problem (or is it otherwise resolved now)?

**Comment by rieder** [comment]
Please feel free to reopen this if the problem remains.
