### ISSUE TITLE
Amuse quantities don't use 'future' imported division

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#178]
When `division` is imported from `__future__`, this is not used by quantities.
This may result in unexpected behaviour when using divisions.
E.g.:
```python
from __future__ import division, print_function
from amuse.units import units
print(5 / 4)
# prints 1.25
print(5 // 4)
# prints 1
a = 5 | units.m
b = 4 | units.m
print(a / b)
# expected: 1.25
# actual result: 1
```

NB: using Python 2.7, I didn't test this in Python3 (when the new division is standard).

**Comment by rieder** [comment]
One option to fix this would be to just add `from __future__ import division` to quantities.py. This would force the new behaviour of the division operator. 
A better method would be to determine which division method is used (i.e. if the user script uses the `from __future__` import), but I'm not sure how to do that yet.

**Comment by arjenve** [comment]
Well, importing future(s) is not something we want here (also it would possibly break existing codes).
I fixed the implementation for truediv and also added floordiv,could you check if this fixes it?

**Comment by rieder** [comment]
Confirmed, issue is fixed.
