### ISSUE TITLE
Problems with installation and conda

### ISSUE THREAD

**Issue by nluetzge** [amusecode/amuse#182]
Hi I'm having trouble installing the code (I had it installed in the past) I moved my python totally into the conda environment and I'm sure this is interfering. I would like to install amuse in a closed environment so that it doesn't screw with my other installations. Is this possible? Also some of my pre-installations failed ... could this be because I'm still on Yosemite?

**Comment by rieder** [comment]
Hi Nora,
Are you still having problems with this?
It is certainly possible to install Amuse within a closed environment (virtualenv, conda, or whatever).

**Comment by nluetzge** [comment]
Hi Steven, 

Still working on it but I’m in contact with Arjen about this. 

Thanks.
Cheers, 
Nora

**Comment by rieder** [comment]
Hi Nora,
I'm closing this issue for now. Please feel free to re-open if you have more questions or information about this, or e.g. if you want to share a required fix!
