### ISSUE TITLE
Building a single code with python3

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#186]
With python2, it's possible to build only a single code, or even just the Amuse framework:
```make framework``` or e.g. ```make ph4.code```

Since the installation for python3 is quite different, I'm wondering how to do something similar there. Building all the codes can take a long time...

**Comment by ipelupessy** [comment]
I agree, for python 3 it would be much preferable to be able to use the same workflow....

**Comment by ipelupessy** [comment]
half done, remains: #282
