### ISSUE TITLE
Convert unit from string to amuse unit object

### ISSUE THREAD

**Issue by fjansson** [amusecode/amuse#189]
Is there a nice way to generate an amuse unit from a string? For example 
```
"m/s" -> units.m / units.s
```
The use case is reading in data from netCDF and use it with amuse. The netCDF API provides units as strings.

**Comment by spzwart** [comment]
Not really Fredrik,

But I guess that a simple python script to read them and convert to the 
proper units would be rather straightforward, right?

Groeten,

Simon

**Comment by fjansson** [comment]
I was thinking this could be a nice feature to have in amuse, as others might want it too. 

One way would be a big dictionary mapping strings to unit expressions. For our immediate case this would work. Gijs says he tried to parse the string and extract corresponding unit objects from the units module, and that this got ugly.

**Comment by ipelupessy** [comment]
I also think a simple dict is most practical (this is the way I do it now ad hoc for some netcdf reading scripts)

**Comment by ipelupessy** [comment]
ad hoc is the best way to do this atm
