### ISSUE TITLE
particles.potential() breaks for len(particles) >= 3163

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#192]
When I run the script below, it fails for len(particles) >= 3163... 
From the error message, it seems like one counter is mirrored and counting back after it reaches 3162?
Error spotted by Alison Sills. She mentioned that this worked fine in earlier versions of Amuse (e.g. v10.0)
```python
import numpy as np
from math import sqrt, pi

from amuse.units import units
from amuse.units import constants
from amuse.units import quantities
from amuse.units import nbody_system

from amuse.io import read_set_from_file

from amuse.ic import plummer

class Analysis(object):

    def __init__(self,):

        self.scale_R = 1.0 | units.parsec
        self.scale_M = 1000.0 | units.MSun
        self.converter = nbody_system.nbody_to_si(self.scale_M,self.scale_R)

        for n in range(3160, 3170, 1):
            print(n)
            self.stars_n = n
            self.stars = plummer.new_plummer_model(
                    self.stars_n, 
                    convert_nbody=self.converter,
                    )
            try:
                potential = self.stars.potential()
            except:
                break

        print("This breaks if the number of particles >= %i" % n)
        # print(potential)

if __name__ in("__main__"):
    
    code = Analysis()
```

Output of this script:
```
3160
3161
3162
3163
This breaks if the number of particles >= 3163
Traceback (most recent call last):
  File "minimum.py", line 42, in <module>
    code = Analysis()
  File "minimum.py", line 38, in __init__
    print(self.stars.potential())
  File "/Users/rieder/Env/Amuse/lib/python3.6/site-packages/amuse/datamodel/base.py", line 491, in __call__
    return self._function(self.particles, *list_arguments, **keyword_arguments)
  File "/Users/rieder/Env/Amuse/lib/python3.6/site-packages/amuse/datamodel/particle_attributes.py", line 384, in particleset_potential
    div = mass / dr
  File "/Users/rieder/Env/Amuse/lib/python3.6/site-packages/amuse/units/quantities.py", line 136, in __truediv__
    return new_quantity_nonone(operator.__truediv__(self.number,other.number), (self.unit / other.unit).to_simple_form())
  File "/Users/rieder/Env/Amuse/lib/python3.6/site-packages/amuse/units/quantities.py", line 1351, in numpy_true_div_operator
    return numpy.true_divide(array, other, out)
ValueError: operands could not be broadcast together with shapes (3163,) (3163,3161) 
```

**Comment by ipelupessy** [comment]
this is a bug introduced by 6901631

I think its ok now (fix a7a0f6a), but should be checked (also for correctness!)

**Comment by arjenve** [comment]
I updated the tests a bit and the code, I compared with the old implementation (also the output).
Turned out that the blocks (a) if block_size < "number of particles" had the wrong shape (fix from Inti) (b) were not summed in the loop to the potentials. In fix of (a) the shape was corrected but then the summation was not over the correct axis.

I've updated the code and tests,  problem left is the speed of one of the tests (too slow)

**Comment by rieder** [comment]
Thanks! At least it works again now.

**Comment by ipelupessy** [comment]
@arjenve sure its correct now? the summation on the other axis passes the same test, and the stricter difference.number==0 test - difference with the newer version is ~1.e-9 (or is it a matter of efficiency?)

**Comment by arjenve** [comment]
Note that we check the relative error (this is e-16).
In the original and first fix only part of the addition was accounted for.
Note that order differences make it impossible to get the error to exactly 0 now.

**Comment by arjenve** [comment]
Steven, can you confirm this one is fixed?

**Comment by rieder** [comment]
Yep, it no longer breaks.
