### ISSUE TITLE
Allow squash merging?

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#204]
The Amuse git repository currently doesn't allow squash merging.
It would be useful to have this, to keep the log readable.
See https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/

**Comment by ipelupessy** [comment]
already fixed?

**Comment by ipelupessy** [comment]
I think this is possible now..

**Comment by rieder** [comment]
Yes, great!
I think ideally we should always use this method to merge, especially big changes.

**Comment by ipelupessy** [comment]
hmm, it depends, I would say its not the preferred method (as there is usually some logic to the commit history that is worthwhile to preserve), unless there is reason to squash (too many micro commits, or poor commit messages, binary changes..etc)
