### ISSUE TITLE
Binary release isn't available

### ISSUE THREAD

**Issue by gekaremi** [amusecode/amuse#205]
link still broken http://amusecode.org/blog/new_image
This is sad

**Comment by spzwart** [comment]
Dear Gekaremi,

Could you explain what is sad about a broken link?

Simon

**Comment by gekaremi** [comment]
Hello! Amuse binary image was great for quick deploy(especially for non-trivial linux distros) and tests. And good ipython tutorials
After suse studio shutdown ( http://amusecode.org/blog/new_image ) last available virtual disk image is old "Release 8.1" ( http://www.amusecode.org/wiki/releases )

**Comment by rieder** [comment]
Ah, yes, the http://www.amusecode.org/wiki/releases page is definitely out-of-date. We're working on a more up-to-date website to address that, in the meantime I've added a link to the 11.1 release to that page.
The release of binary images is another point of attention. Hopefully we can soon again have a working binary release available.

**Comment by gekaremi** [comment]
Good to hear it, thank you
