### ISSUE TITLE
configure doesn't find installed libraries

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#209]
On my system (macOS High Sierra), running configure can't find several (symbols in) libraries that are installed (gmp, mpfr, hdf5), resulting in some codes (adaptb, brutus, simplex) not building.

Select output from ./configure is the following:
```
checking gmp.h usability... yes
checking gmp.h presence... yes
checking for gmp.h... yes
checking for __gmpz_init in -lgmp... no
configure: WARNING: libgmp : library missing. (Cannot find symbol gmpz_init). Check if libgmp is installed and if the version is correct
checking for MPFR... no
checking mpfr.h usability... yes
checking mpfr.h presence... yes
checking for mpfr.h... yes
checking for mpfr_init in -lmpfr... no
configure: WARNING: libmpfr : library missing. (Cannot find symbol mpfr_init). Check if libmpfr is installed and if the version is correct
checking how to run the C++ preprocessor... g++ -E
checking mpreal.h usability... no
checking mpreal.h presence... no
checking for mpreal.h... no
configure: WARNING: Cannot find header (mpreal.h) of the library MPFR with MPFR_FLAGS .
checking hdf5.h usability... yes
checking hdf5.h presence... yes
checking for hdf5.h... yes
checking for H5_init_library in -lhdf5... no
configure: WARNING: libhdf5 : library missing. (Cannot find symbol H5_init_library). Check if libhdf5 is installed and if the version is correct
```
If I manually set the paths in config.mk, the codes build fine; so maybe the problem is in finding the symbols specified above?

**Comment by rieder** [comment]
@arjenve Any ideas why these libraries aren't being detected? It seems to be a macOS-specific problem, on my Linux machine the symbols are found.

**Comment by rieder** [comment]
See also #347 #266 #284

**Comment by rieder** [comment]
#453 fixed this for HDF5 libraries, the others still may need work...

**Comment by rieder** [comment]
Installing amuse-brutus on macOS/macports fails because MPFR_FLAGS is left empty instead of set to the required -I/opt/local/include.

**Comment by rieder** [comment]
MPFR still not found correctly (macOS), causing Brutus build failures.

**Comment by ipelupessy** [comment]
from #609, #662, for mpfr (and possibly gmp) the essential bit is that the configure is working ok, its pkg-config that gives the wrong information; though it should not matter and it doesn't except for macOS..(where the  macports directory does not get added to the standard include dirs)

**Comment by rieder** [comment]
Bump as this is still an issue...

**Comment by rieder** [comment]
A solution that works for me on macOS is installing `pkgconfig` from macports. Then all the prerequisites are found.

**Comment by rieder** [comment]
on macOS 12 Monterey installing this is a necessity

**Comment by rieder** [comment]
it's still just mpfr that is missing the include flags...

**Comment by ipelupessy** [comment]
close, please reopen with concise list of not working library detections
