### ISSUE TITLE
Easier installation documentation on website

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#218]
Currently documentation requires navigating a menu and several headers on pages, I think this could be simpler.
I'm working on a jupyter notebook (in https://github.com/rieder/amuse-tutorial) that has dropdown menus for selecting the OS (and version of that OS) and MPI version, and then displays the desired installation instructions (which could be stored as individual RST or Markdown formatted text files).
This document could directly be embedded in a webpage using nbviewer, or it could automatically generate a regular, static webpage with the same features. 
I think either would be an improvement.

**Comment by ipelupessy** [comment]
this has been fixed by the new website (and if it is not, it needs a new issue)
