### ISSUE TITLE
Broken Links in mpiamrvac

### ISSUE THREAD

**Issue by ny2292000** [amusecode/amuse#230]
'src/amuse/community/mpiamrvac/src/mpiamrvac/AMRVAC_Man/figmovdir/vaclogo.png': doesn't exist or not a regular file
'src/amuse/community/mpiamrvac/src/mpiamrvac/AMRVAC_Man/figmovdir/sphereadvection.png': doesn't exist or not a regular file

These are broken links in the current AMuse.

They cause problems.

**Comment by rieder** [comment]
Thank you for reporting. 
Could you describe where this causes problems (please attach a log file if possible)?
