### ISSUE TITLE
update mpiamrvac download

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#231]
I think mpiamrcav has moved to github:
https://github.com/amrvac/amrvac
(maybe check with Rony)
updating this and also building on a more recent version might fix #230

**Comment by rieder** [comment]
The old version was from 2012, so updating will probably take a bit of effort.
But I agree it's a good idea to update to a more recent version.
v2.0 seems like it would be a good starting point. I'll make a branch for updating this.

**Comment by rieder** [comment]
work-in-progress in branch patch-update-amrvac.

**Comment by ipelupessy** [comment]
ok, thanks..btw..it may take a while for this branch to be merged (if it runs out to require some effort), wouldn't the branch better live in your personal fork? I think we sought to clarify this in #166 and #225 (but then maybe not clear enough ;-) )

**Comment by rieder** [comment]
You’re right. I’ll move it to my fork. 
The most important thing is that this should not be work done in master, as it very much breaks things ;).

**Comment by ipelupessy** [comment]
ok...
for reference: http://amrvac.org/md_doc_faq.html#faq-new-version
