### ISSUE TITLE
add CFF (citation file format) file

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#232]
**Is your feature request related to a problem? Please describe.**
its related to citation for the AMUSE

**Describe the solution you'd like**
add CFF file (citation file format file: https://github.com/citation-file-format/citation-file-format) with the 
references for AMUSE code papers. (not references for the community codes)

**Describe alternatives you've considered**
The default citations only show up after using AMUSE. CFF files are also used by automated tools to generate citations

**Additional context**
CFF are an emerging standard for software citations. I am no particular fan of the format itself (doesn't look very elegant), but if this is what other people are using...

**Comment by rieder** [comment]
Seems good to have something like this.

Perhaps we could additionally generate bibtex files with ADS entries?
We could easily get those for all the citations that are currently printed.

**Comment by ipelupessy** [comment]
fixed by #311
