### ISSUE TITLE
Replace MPI C++ bindings in ph4 with C bindings

### ISSUE THREAD

**Issue by nitadori** [amusecode/amuse#239]
I failed to build ph4.
It seems it is because C++ bindings of MPI is used, which are deprecated and removed from recent OpenMPI.
The error log is as follows:

Building code: ph4, target: all, in directory: build/temp.macosx-10.11-x86_64-2.7/codes/ph4
****************************************************************************************************
/Users/nitadori/amuse/build.py --type=c interface.py ph4Interface -o worker_code.cc
/Users/nitadori/amuse/build.py --type=h  -i amuse.support.codes.stopping_conditions.StoppingConditionInterface interface.py ph4Interface -o interface.h
make -C src all CXX='mpicxx'
mpicxx -g -O2 -fPIC -g -O2 -fPIC -Wall -g -O2 -I/Users/nitadori/amuse/lib/stopcond  -g -O2 -fPIC -Wall -g -O2 -I/Users/nitadori/amuse/lib/stopcond -g -Wall -I/Users/nitadori/amuse/lib/stopcond  -c -o debug.o debug.cc
In file included from debug.h:2:0,
                 from debug.cc:1:
jdata.h:81:5: error: 'MPI' does not name a type
     MPI::Intracomm mpi_comm;  // communicator for the N-body system
     ^
jdata.h:182:20: error: 'MPI' has not been declared
     void setup_mpi(MPI::Intracomm comm);
                    ^
jdata.h:182:35: error: expected ',' or '...' before 'comm'
     void setup_mpi(MPI::Intracomm comm);
                                   ^
jdata.h: In constructor 'jdata::jdata()':
jdata.h:141:2: error: 'mpi_comm' was not declared in this scope
  mpi_comm = NULL;
  ^
make[1]: *** [debug.o] Error 1
make: *** [src/libph4.a] Error 2
****************************************************************************************************

**Comment by ipelupessy** [comment]
if necessary you can still build openMPI with c++ bindings I think, configure --enable-mpi-cxx..
@stevemcmillan: are there any plans to update the code?
(there are also other codes that use the c++ bindings)

**Comment by JPGlaser** [comment]
I recently had to install amuse on a new Ubuntu 16.04.4 LTS machine and encountered this error. This was my solution:

1. Perge all user-created versions of mpi4py and openMPI from the computer.
2. Install LinuxBrew Package Handler (http://linuxbrew.sh/) and follow all instructions.
3. Install OpenMPI 3.1.1 via: _brew install openmpi_ This will enable the c++ bindings by default.
4. Install mpi4py via your python's pip: _pip install mpi4py --no-cache-dir _ This should automatically install the mpi4py for the above stated version of OpenMPI.
5. Run _make clean_ in the AMUSE directory.
6. Run _./configure_ with desired options/paths.
7. Run _make_.

The only code that couldn't compile is galaxia and all cython dependent versions (though I have never been able to get those to install).

Hope this helps!

~ Joe G.

dasd

**Comment by JPGlaser** [comment]
Correction, the above works for all codes **except** ph4 and simplex. For some reason, AMUSE had pulled my system's main openmpi which caused errors against the mpi4py that it wasn't compiled against. Looks like --enable-mpi-cxx doesn't fix the compile errors for OpenMPI 3.1.1.

~ Joe G.

**Comment by rieder** [comment]
The fix for this should be replacing the C++ bindings for MPI with C bindings. I guess we could use help with that, if anyone wants to pick this up!
Some background: https://blogs.cisco.com/performance/the-mpi-c-bindings-what-happened-and-why

**Comment by rieder** [comment]
Thanks Josh!
I will try tomorrow (unless someone else checks it first).

**Comment by ipelupessy** [comment]
this should be fixed for ph4, simplex still needs to be done (but has a separate issue)
