### ISSUE TITLE
hdf5 cannot write (numpy) unicode strings

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#24]
hdf5 cannot write numpy unicode strings (see https://github.com/ipelupessy/amuse/tree/hdf5_unicode_error), which is a problem because by (i think) commit 3997b47224a29b57807c59c5e8214a11c0cdd5bf  strings returned from code are converted to unicode?

**Comment by arjenve** [comment]
Test is now working, and saving unicode strings should work. Can you confirm?

**Comment by ipelupessy** [comment]
yup, seems to work fine now...
