### ISSUE TITLE
Add Travis CI testing

### ISSUE THREAD

**Issue by egpbos** [amusecode/amuse#241]
Following up on https://github.com/amusecode/amuse/issues/153#issuecomment-399291984, let's get Travis CI going.

For reference: @rieder's branch contains a [Travis file](https://github.com/rieder/amuse/blob/cover/.travis.yml) for which I don't see any objections to merging.

We can build on it from there to include coverage of a build matrix containing:
- macOS
- probably also Python 3.5/3.6
- perhaps some contributor code tests (though I heard they take very long, so maybe not test everything on all platforms; the CUDA codes will not work anyway)
- maybe a code coverage tool for amuse_core

**Comment by egpbos** [comment]
@rieder Any reason why you list specific tests instead of just doing `nosetests test/core_tests`?

**Comment by rieder** [comment]
I skipped one test, because it failed for some reason I couldn’t figure out at the time (and didn’t have time to get back to it since).

**Comment by egpbos** [comment]
A repo admin (@ipelupessy @arjenve?) should enable the amuse repo in Travis here: https://travis-ci.org/profile/amusecode
