### ISSUE TITLE
Fix MPI firewall trouble on macOS

### ISSUE THREAD

**Issue by egpbos** [amusecode/amuse#243]
When running the test suite on macOS, MPI (and possibly other things?) causes many (focus-grabbing and thus highly annoying) pop-ups saying that I have to open my firewall. Clicking "allow" (for that one time) does not even make the test succeed, so they are not only annoying, but also useless.

I would prefer if doing firewall configuration were not necessary, perhaps through code signing, something like this: https://apple.stackexchange.com/questions/3271/how-to-get-rid-of-firewall-accept-incoming-connections-dialog

I guess one alternative is to indeed add the programs to the firewall white list, but I don't really want to do this. If it would be possible to use MPI without having to do any of these things, e.g. by using some default firewall-safe dummy connection settings, that would be ideal imho.

**Comment by egpbos** [comment]
Setting
```
export OMPI_MCA_rmaps_base_oversubscribe=yes
```
seems to help, at least for hermite0. With this set, no firewall settings are necessary for that code. Other codes still complain for various reasons though. Needs further investigation.

@ipelupessy documented this at: http://www.amusecode.org/wiki/openmpi

**Comment by rieder** [comment]
Do you by any chance have a hostfile which wants to connect to other machines?
Recent (open)mpi seems unwilling to use more processes on a local machine than there are cores, unless that environment variable is set. This is very inconvenient for AMUSE, so I'd suggest we always setting it (or recommend doing so in the documentation).

**Comment by egpbos** [comment]
I don't know about hostfile settings, I didn't change it. Indeed, either using the environment variable for recent OpenMPI version or, if possible, somehow using the --oversubscribe argument for mpirun (can that be passed through mpi4py?) would be a good idea.

**Comment by ipelupessy** [comment]
@rieder still an issue?

**Comment by ipelupessy** [comment]
@rieder do you still have this behaviour (ie firewall pop-ups) on mac?

**Comment by rieder** [comment]
Yes, unfortunately.

**Comment by ipelupessy** [comment]
hmm, does this help:
mpiexec -n 1 --oversubscribe --mca btl_tcp_if_include lo   python <script>
??
