### ISSUE TITLE
Code refactoring (style)

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#250]
A lot of the code in AMUSE currently doesn't follow the AMUSE style guidelines (http://www.amusecode.org/doc/reference/style_guide.html). Fixing this would increase readability, and could help in refactoring code for Python3.

**Comment by arjenve** [comment]
Steven, are you using an automated tool for this? Could you not do the python3 stuff mixed with the code style? Allthough code style is important, so is continuation in the source code (i.e. having manageable changes etc.) So I have to think about this.

**Comment by rieder** [comment]
No, I did this manually (using a tool to check validity), mostly to kill time on an intercontinental flight ;).

The reason I did the print function changes is that my tool runs on Py3 and would otherwise complain about that. But you're right, these things are different and should not be mixed. 

So please don't merge these yet - I'll make these into purely code style changes and we'll do the py3 stuff in a separate PR.

**Comment by ipelupessy** [comment]
I was wondering the same thing...(also I think some of the formatting changes to pep8 style collide a bit with way scientific formula are read (ie not spread out over multiple lines) )

**Comment by rieder** [comment]
Personally, I find them much more readable that way...

**Comment by ipelupessy** [comment]
really? e.g.:
```
self.factors = (
                pow(
                    self.mass_boundaries[1:]
                    / self.mass_boundaries[:-1],
                    self.alphas + 1.0
                    )
                - 1.0
)
```

**Comment by ipelupessy** [comment]
(not to imply the original formatting is perfect...)

**Comment by ipelupessy** [comment]
mostly done or wip
