### ISSUE TITLE
Fix matplotlib test on Travis

### ISSUE THREAD

**Issue by egpbos** [amusecode/amuse#257]
Following up from #244, https://github.com/amusecode/amuse/pull/244#issuecomment-400202610

The matplotlib test in core_tests/test_plot.py currently is disabled in the Travis build. @rieder fixed this test in [his branch](https://github.com/rieder/amuse/tree/cover) by removing the explicit Agg backend line in the test and adding a matplotlibrc file that sets things instead.

**Comment by ipelupessy** [comment]
would this matplotlibrc file be picked up in normal usage?

**Comment by ipelupessy** [comment]
travis retired
