### ISSUE TITLE
Fix dynamic build tests by adding LDFLAGS

### ISSUE THREAD

**Issue by egpbos** [amusecode/amuse#264]
Make a new submodule amuse.test.compile_tools which includes fix for ld_flags and then manually replace copy-pasted test codes by these tools. Follows up on https://github.com/amusecode/amuse/issues/258#issuecomment-400273654

**Comment by egpbos** [comment]
Searching for "def *_compile" and "def build_worker" in the test directory gives me the following list of affected files:

codes_tests/test_c_implementation.py
codes_tests/test_c_implementation_simplified.py
codes_tests/test_cython_implementation.py
codes_tests/test_fortran_implementation.py
codes_tests/test_fortran_sockets_implementation.py
codes_tests/test_java_implementation.py
codes_tests/test_stopping_conditions.py
core_tests/test_grid_implementation.py
reports/test_speed.py

**Comment by egpbos** [comment]
I'm thinking now about adding these tests to the Travis build so that I can have CI feedback while developing.

I first thought I could just run these specific tests explicitly, but now I'm thinking: doesn't it make more sense split these tests out into a separate directory, say `test/compile_tests`? @ipelupessy @arjenve

**Comment by ipelupessy** [comment]
a bit more organization would be good, so for me its ok...

**Comment by egpbos** [comment]
Ok, moved them in 2e667dd

**Comment by ipelupessy** [comment]
fixed by #272
