### ISSUE TITLE
Installing Amuse on macOS

### ISSUE THREAD

**Issue by egpbos** [amusecode/amuse#266]
Just for reference, I want to paste here my notes on installing Amuse on macOS as a total newbie. Maybe some of it proves useful to someone.

ATTEMPT 1
---------

```
conda install mpi4py nose
./configure
make build3 -j4
```

--> 22 out of 47 codes built, 4 out of 6 libraries built

Mainly the fortran codes seem problematic, seems to be an issue with mpif90. Openmpi was installed through conda, maybe try via macports.

NOTES
-----
Seeing a lot of:

```
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
```

Not really pretty, what's going on?

Also quite a few

```
Can't parse .../SOME_FILE.py: ParseError: bad input: type=22, value='=', context=('', (209, 59))
```

ATTEMPT 2a
----------

```
sudo port install openmpi
```

ATTEMPT 2b
----------

The conda-forge openmpi build does seem fortran-enabled (https://github.com/conda-forge/openmpi-feedstock/search?q=fortran&unscoped_q=fortran), so we can also try that one first.

conda install -c conda-forge openmpi

--> 35 out of 47 codes built, 4 out of 6 libraries built

CONDA ENV
---------
Amuse is Python 2 by default.

conda create -n amuse python=2.7

It should be possible to run with Python 3 by running `python setup.py build` instead of `make`.

NOSETESTS
---------

Necessary for running tests in clean conda env:

conda install nose numpy docutils
conda install -c conda-forge mpi4py
conda install ipython h5py

To avoid all the MPI firewall crap, do only core tests:

nosetests test/core_tests

ATTEMPT 3
---------
Now also install gfortran through conda

conda install -c anaconda gfortran_osx-64

Do make clean and rebuild, also configure. Now don't have to do make build3 anymore, that was because I built in a python3 environment before, but not anymore now.

--> 22 out of 46 codes built, 5 out of 6 libraries built

conda install -c conda-forge cython

--> 30 out of 46 codes built, 5 out of 6 libraries built

Try to build bhtree (one of the not-built ones) manually:

```
cd src/amuse/community/bhtree
make
```

Shows linking errors to std:: things... that usually means compiler or stdlib mismatch.

Back in the amuse root dir, check config.mk: shows that it detects g++ and gcc (macports) for CXX and CC, but that mpicc and mpicxx use clang, so there's the mismatch. Indeed, bhtree builds some parts with g++ and some with mpicxx.

ATTEMPT 4
---------

If you have gcc installed via Macports, make sure the configuration detects clang as your main compilers to avoid later linking problems (e.g. we saw this with bhtree):

make clean
env CXX=clang++ CC=clang ./configure
make -j4

--> 22 out of 46 codes built, 5 out of 6 libraries built

Check adaptb:

```
cd src/amuse/community/adaptb
make
```

--> fatal error: 'mpfr.h'

conda install mpfr -c conda-forge

Still same error...
Seems like configure doesn't find things in $CONDA_PREFIX? Let's add it then. And also add some dependencies while we're at it

```
conda install -c conda-forge fftw gsl gmp netcdf4
env CXX=clang++ CC=clang ./configure --with-mpfr=$CONDA_PREFIX --with-hdf5=$CONDA_PREFIX --with-fftw=$CONDA_PREFIX --with-gsl-prefix=$CONDA_PREFIX --with-gmp=$CONDA_PREFIX --with-netcdf=$CONDA_PREFIX
make -j4
```

--> 37 out of 46 codes built, 5 out of 6 libraries built

ATTEMPTS 5 & 6
--------------

At runtime, I get @rpath/libSOMETHING not found errors. This is due to building without ld flags for rpath. Tried installing pkg-config to automagically fix this, but didn't work. It does help in the configure process, though not for GMP and HDF5. In any case, try rebuild with added LD_FLAGS. I wanted to also remove some of the above options because pkg-config should detect them, which in most cases it indeed does, and netcdf is apparently not detectable even with the flag, but it turned out they all had to stay in, otherwise stuff doesn't get built... seems like these flags are both "activation flags" and path-specifiers in one... anyway:

```
conda install -c conda-forge pkg-config
env CXX=clang++ CC=clang LDFLAGS="-Wl,-rpath,$CONDA_PREFIX/lib" ./configure --with-hdf5=$CONDA_PREFIX --with-gmp=$CONDA_PREFIX --with-mpfr=$CONDA_PREFIX --with-fftw=$CONDA_PREFIX --with-gsl-prefix=$CONDA_PREFIX
make -j4
```

--> 40 out of 46 codes built, 5 out of 6 libraries built

However, arrrgh, hermite0_worker still fails with the same error. Does it not use LD_FLAGS perhaps?

Oh wait, I had typed LD_FLAGS instead of LDFLAGS... d'oh!

Again...
--> 24 out of 46 codes built, 5 out of 6 libraries built

.. but when I manually build athena (cd src/amuse/community/athena; make) it seems to build just fine... maybe a problem with make -j4 then? Try again with just one job:

```
make
```
--> 42 out of 46 codes built, 5 out of 6 libraries built

Okay then! Let's give it yet another shot :D

... that doesn't change the outcome. So indeed the multiple make jobs seem to break things... odd.

The remaining failing ones:
 * fastkick
 * fi
 * hacs64
 * kepler_orbiters

Fastkick:
make clean
make
--> builds!

Fi:
Can't get it to link, because conda fftw is missing fortran symbols, see https://github.com/conda-forge/fftw-feedstock/issues/16. Did a suggestion to fix this using default conda fortran compiler, proposing that I could do a PR for it.

Hacs64:
Weird errors, possibly to do with gcc-specific/non-portable C functions:

```
... error: using os/log.h requires Xcode 8 or later
...
... error: use of undeclared identifier '__builtin_os_log_format_buffer_size'
```

Many of the last one. That one seems to have been implemented in LLVM (https://reviews.llvm.org/D25888), but maybe it's not in the Apple version yet.

Kepler_orbiters:

```
ld: library not found for -lomp
```

This is an error in the compilation command, the -fopenmp flag doesn't usually work on macOS, and in any case it should first have been detected during configuration before being activated.

So, in the end we end up with 
--> 43 out of 46 codes built, 5 out of 6 libraries built

Most importantly, the programs now also seem to run! At least hermite0_worker does.

Let's run the tests then.

```
nosetests
```

The firewall messages are still a major annoyance...

**Comment by evertrol** [comment]
Related #240 .
