### ISSUE TITLE
kepler_orbiters build on macOS fails due to OpenMP

### ISSUE THREAD

**Issue by egpbos** [amusecode/amuse#268]
Following up on #266, kepler_orbiters cannot be built on macOS due to the -fopenmp flag which adds -lomp (OpenMP library). OpenMP is not officially supported on macOS (there are ways to do it, but they are hacky and non-robust), so the -fopenmp flag should not be used for macOS builds.

**Comment by rieder** [comment]
That's with the Xcode compilers, right? I believe with gcc OpenMP works fine?

**Comment by egpbos** [comment]
Yes, you're right, so it only needs to be disabled when using Apple clang. This is, however, the default compiler, so I think it still makes sense to fix it. Using gcc on macOS in my experience has always been and remains to be a hassle; Macports and Homebrew are great in their own ways, but they also introduce some new problems that I personally started preferring to avoid lately. [Conda also uses Apple clang by default](https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html), and since that is the way I'm currently building on macOS, that was how I got to this point.

**Comment by rieder** [comment]
Fixing the dependency is of course a great idea, but let's also check if the compiler supports OpenMP and enable it again if it does.

**Comment by arjenve** [comment]
Note that configure checks for openmp and that we have special flags for openmpi inclusion. Probably the kepler_orbiters flag do not use these flags.

**Comment by egpbos** [comment]
Indeed, kepler_orbiters' Makefile hard-codes the -fopenmp flag: https://github.com/amusecode/amuse/blob/master/src/amuse/community/kepler_orbiters/Makefile#L11

So probably that's the only thing to fix then?
