### ISSUE TITLE
Make building out-of-place the default

### ISSUE THREAD

**Issue by evertrol** [amusecode/amuse#271]
The default for building with Python 2 is in-place. While this is easiest, in particular for building single codes, the default should probably be an out-of-place build.

**Comment by ipelupessy** [comment]
I think you want same behaviour for python2 and 3, and since python 3 does not support in-place build due to 2to3, this is reasonable, but this will probably invite discussion! (which is good)

**Comment by evertrol** [comment]
On the other hand, if a Py2/3 compatible code base could happen relatively soon (at least for relevant files), this issue may become largely moot.

**Comment by egpbos** [comment]
Even with a 2/3 compatible code base, out-of-place builds make management of the repo easier (no long gitignore list, just ignore `build/`; easy restarting from scratch by deleting the build directory; easy multiple builds with different configurations), so I would still vote for it.

**Comment by rieder** [comment]
So would I.
virtualenv makes it easy to install in a separate directory if this is desired anyway.

**Comment by ipelupessy** [comment]
closing this; out of place is the default if using setup.py, other issues are fixed with combinations of pip install [-e] etc
