### ISSUE TITLE
cleanup of tests

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#277]
- debug print statements; some tests generate large amounts of output, which can probably be removed
- tests that generate files should maybe also clean them up...

**Comment by rieder** [comment]
I think this is probably solved...

**Comment by ipelupessy** [comment]
largely, some codes test need cleanup (capreole, ..?) and print statements (output for tests should be really terse)

**Comment by ipelupessy** [comment]
close for another time
