### ISSUE TITLE
travis test fails on for osx

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#280]
many tests fail on the osx travis build (they are disabled now)..not clear whether it indicates a problem with the test machine or the (conda-based) iinstall on it.. problems are:
- tests with port accept, connect fail on disconnect (e.g. test26 of test_python_implementation)
- socket tests (fortran and c) all fail

**Comment by ipelupessy** [comment]
also tested on real mac with brew based install: fails for openmpi 3.1.0, works with mpich

**Comment by rieder** [comment]
Socket tests still all fail.

**Comment by ipelupessy** [comment]
travis retired
