### ISSUE TITLE
Cython build failure reasons

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#281]
this issue is to document the reasons Cython worker builds fail:
- the cython command generating the pyx needs the mpi4py include -I(mpi4py.get_include())
- the mpicxx compile generating the _cython.so needs the numpy include -I(numpy.get_include())

currently this is in the config.mk nor propagated to the code makefiles...

fixing it is possible, but I think the current plan is to remove the cython workers again...

**Comment by rieder** [comment]
Is anything in AMUSE using Cython these days? If not, let's remove it.

**Comment by ipelupessy** [comment]
yes, I think we can remove it (this was the plan with Arjen) - I think we may want to leave it in the framework (for development, at some point it may be handy - in one of the ways to achieve parallel transport) but at least remove it from the makefiles of the codes that have it

**Comment by spzwart** [comment]
Cython is used by Hanno Rein's code Rebound.

**Comment by rieder** [comment]
Not for the AMUSE interface, right?
There's a 'regular' and a (for me not working) 'cython' worker for Rebound, and I can imagine the standalone Rebound uses Cython for its Python interface, but we're not using that I think?

**Comment by ipelupessy** [comment]
I think rebound uses ctypes for its own python interface not cython (at least in the version downloaded by AMUSE)...

in any  case, this is about the amuse cython interface (ie the cython version of the mpi communication channel).

**Comment by rieder** [comment]
See #452 - close this?

**Comment by rieder** [comment]
cython is long removed from AMUSE now
