### ISSUE TITLE
Simplex compilation errors

### ISSUE THREAD

**Issue by stevemcmillan** [amusecode/amuse#284]
Simplex fails to bulid using Ubuntu 16 and 18 with apt prerequisites, and Macos High Sierra
with Macports prerequisites.

Saying 'make clean all' in the simplex directory should build the simplex_worker code.  The underlying cause of the problems seems to be that  **configure**  doesn't identify the proper HDF5 paths and flags.

There are multiple sources of error:

1.  On Ubuntu 16 and 18, the Simplex HDF5 write functions fail to compile because apt installs hdf5.h in /usr/include/hdf5/serial which is not picked up by configure.  The correct line in config.mk would be

        HDF5_FLAGS=-I/usr/include/hdf5/serial

but the actual assignment is blank.

This isn’t a problem in MacOS because Macports installs hdf5.h in /opt/local/include, which is automatically detected by the compiler.

2.  Even with the header location fixed, compilation fails on all three OSs because -lhdf5 does not appear anywhere in the Makefile. In addition, in Ubuntu 16 and 18, apt places the library in /usr/lib/x86_64-linux-gnu/hdf5/serial, which again is not picked up by configure.  Macports installs libhdf5.a in /opt/local/lib, which is properly detected by the compiler.  Thus the correct config.mk entries would be

        HDF5_LIBS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5

for Ubuntu 16 and 18 and

        HDF5_LIBS=-L/opt/local/lib -lhdf5

in MacOS (the -L part isn’t actually needed).  Again, configure leaves these assignments blank.

3.  Finally, the Makefile uses make syntax incorrectly.  The line

        HDF5_LIBS ?= something

should set HDF5_LIBS if it isn't already set, providing a means of correcting configure shortcomings.  However, once config.mk is done, it leaves HDF5_LIBS set equal to the null string, so the  ?=  line does nothing.

**Comment by arjenve** [comment]
Thank you for the extensive report!

Could you please try to run configure with:

./configure --with-hdf5=/usr/lib/x86_64-linux-gnu/hdf5/serial

Although it probably won't work (very strange practice to put libraries in directories like this)

In Mac Os this should work

./configure --with-hdf5=/opt/local

(if the headers are in /opt/local/include and libs in /opt/local/lib)

I'll see if there is any other way to do this optional setting in the Makefile

**Comment by rieder** [comment]
Related to #209?
