### ISSUE TITLE
Initialize multiples with a cluster of binaries

### ISSUE THREAD

**Issue by Timothe20** [amusecode/amuse#288]
Hi,

I am trying to model a cluster of few thousands of stars with a quite high binary fraction > 50%. I base my initial conditions on the kira example, except that I did not add stellar evolution yet. I just want to see the dynamical evolution for the moment.
My question is how to well initialize the multiples module (or encounter module) in order to settle correctly single stars and binary stars. Do I have to make 3 particle sets as in kira, one with the singles, one with the binaries' center of mass and one with the binaries relative to their center of mass ?

Thanks by avance,

Timothé

**Comment by Timothe20** [comment]
I am updating my post to be a bit more precise. I finally use the general multiple module which doesn't seem to need more than one particle set. But I wonder how to organize this particle set at the beginning to make multiple understand that there are already some binaries in the cluster and to deal with it in consequence. Maybe as a binary tree, or on the same pattern than the Multiples.stars particles set?
For the moment, because I feed the code with all the stars individually. The code recalculate all the binaries I already initialized, which is quite ugly and takes time.

**Comment by ipelupessy** [comment]
Hi Timothé, will ask around for this - I think the most knowledgeable people on this are away on holiday atm...

**Comment by arjenve** [comment]
Hi Timothe, look into the root_to_tree code.

The Multiples code is based on a gravity code, every particle in that code might be a "tree". These
"trees"  are stored in a dictionary keyed to the particle. Each tree is a small particle set, the gravity particle is in there (the parent) and the children and grandchildren are in there, all stored as a binary tree using two attributes "child1" and "child2", for example:

| key  |  child1 | child2 | mass |
|-------|----------|---------|--------|
|      1|         2 |       3 |      1.0 |
|      2|            |         |       0.7 |
|      3|            |         |      0.3 |

To set this up, simply make a gravity code, add particles, create a multiples code and, for some of the particles, create trees and put those in the root_to_tree dictionary.

Very high level
```
P = new_particles()
G = new_gravity_code()
G.particles.add_particles(P)
M = new_multiples_code(G)
for X in particles_that_should_have_binaries(P):
     T = create_tree(X)
     M.root_to_tree[X] = T
M.evolve_model(TIME)
```


Some details:

```
P = new_plummer_model(10)

# make a binary of the first particle
parent = P[0]
tree = Particles()
child1 = Particles(mass = parent.mass / 2.0, x = parent.x + r/2, y = parent.y, z = parent.z, vx = ..., v...)
child2 = Particles(mass = parent.mass / 2.0, ...)_
parent_in_tree = tree.add_particle(parent)
parent_in_tree.child1 = tree.add_particle(child1)
parent_in_tree.child2 = tree.add_particle(child2)

# now define the binary
C = Multiples(...)
C.root_to_tree[parent] = tree
```

**Comment by Timothe20** [comment]
I think I saw your previous message that helps me in building the tree. 
In fact I didn't get the syntax to initialize the parent_tree: 

`tree=Particles()`
`parent_tree = tree.add_particle(center_of_mass)`
`parent_tree.child1 = tree.add_particle(primary)`
`parent_tree.child2 = tree.add_particle(secondary)`

because it creates it in the same time as the tree particle... Anyway it seems to work, I suppose I have to do next:

`binary_tree = BinaryTreeOnAParticle(parent_tree)`
`multiple_code.root_to_tree = {tree[0]: binary_tree}`

I finally made up my choice on the multiple module and not the encounter one. I found that it was simpler to use but the philosophy remains the same.  Something I still don't get is the position and velocity of the singles. If I add the center of mass postion and velocity to both component and the code should find the same orbits because it is the same for both singles. Maybe it is making an error in calculating the orbit ?

Thanks again,

Timothé.

**Comment by Timothe20** [comment]
I actually investigate the problem of the position and velocity of the singles in the binary trees. When I don't add the center of mass position and velocity to the singles, I don't find the same values in the multiples_code.check_trees() function which should be the case, shouldn't it ?

**Comment by stevemcmillan** [comment]
Timothe, I agree that the initialization of multiples is inelegant, to say the least.  I wrote most of the "physics" parts, but not the data structures, and I had been hesitant to play around too much with parts of the code I don't know well.  However, prompted by your questions, I have added a new method to multiples to allow you to create a binary without going through the integrator and stopping condition.  It's experimental, but please try it out and let me know if you have problems.  I've done some rudimentary tests and it "seems too work," as they say...

The calling sequence is very simple.  Assuming you have a list of stars in your script created in the usual way, the syntax is

         multiples_code.create_binary(star1, star2)

This will create a binary from the two components, remove them from the particles dataset in the gravity module, add the center of mass to the module, and update all internal multiples data structures.  You'll have to update your own channel data in the script, if you are using it.  I'll be happy to elaborate if you have problems.

**Comment by Timothe20** [comment]
Nice, thanks ! it seems to work just fine. I could compare with the method I built and I understand a bit better what does the code needs. Nevertheless I have still a question about the position of the singles in the binary particle. They should be placed relative to the center of mass of the binary, but when you add the singles in the binary particle, you just keep the same positions as in the top level. Ok, it is simpler, but I find it confusing...

**Comment by stevemcmillan** [comment]
I agree that it might have been cleaner to store the child coordinates relative to their parent. That would save a couple of lines of code when reconstituting a multiple for the next encounter.  On the other hand, the current method is quite practical, as the dictionary entry for a given top-level node is just a copy of the particle set at the end of the encounter.  Once the user understands what is stored, I don't think changing the format would gain much, and would have a high probability of breaking the module, at least temporarily.
