### ISSUE TITLE
Why do we have units.none and units.no_unit?

### ISSUE THREAD

**Issue by iambernie** [amusecode/amuse#29]
In all of my amuse related programming, i've never actually had to resort to `units.none` and/or `units.no_unit`, so after reading #28 I just couldn't restrain myself from asking:

    Why do we have units.none and units.no_unit? What is their purpose? 
    What can you do with units.none that you couldn't with a simple numpy ndarray?

Btw, I'm not asking why we have them both, I'm asking why we have them at all.

**Comment by ipelupessy** [comment]
there use is limited, and normally they are dropped whenever encountered,  but see e.g. the definition of deg and rad units
