### ISSUE TITLE
Problem in the particles management with the multiple module 

### ISSUE THREAD

**Issue by timroland** [amusecode/amuse#297]
Hello Amuse community,

I ran a simulation of a star cluster of less than 1000 stars with a subpopulation of binaries. I am using the "Multiples" module with ph4 and SmallN. I noticed a problem in the mass conservation which bothers me quite a lot.

**Describe the bug**
It happens always at the same time when the SmallN integration does not converge during an encounter. It then seems that some stars disappear just after this encounter. They are not the particles directly involved in the encounter but in the perturbers list (in the example I give here, they are the id 35 and 19). 
I suppose the problem comes from when the SmallN code abort, it does put back the particles of the encounter but not the particles flagged as perturbers... 

**Expected behavior**
Is there a real problem here? or is SmallN unexpected to fail? Maybe the simulation should stop in this case to handle it in a way or another, but should not continue with some particles missing. 

**To Reproduce**
I attached here in an archive, my script (multhic.py for python 2 and multhic3.py for python 3) with the initial conditions in a csv file. You just have to run it as `python[3] multhic[3].py`.
[Multiple_test.tar.gz](https://github.com/amusecode/amuse/files/2530958/Multiple_test.tar.gz)
The version in python 3 is a bit different because the binaries are identified (in the other one, I just let the multiples module take care of it at the first steps of the simulation). There are less encounters at the beginning but the same problem happens after anyway.

**Logs**
The log file is here: [log_mass_loss.txt](https://github.com/amusecode/amuse/files/2530987/log_mass_loss.txt) where I have the output of this simulation (multiples debugging info, some energy conservation tracking and a list of the ids of the stars, single or in multiple system). 
The SmallN code crashes at line 2777. Just before, 6 stars are taken into account in the encounter (line 2766); just after, only 4 (line 2829). It corresponds to the 2 missing particles when I list them line 2909 to 2921. 

**Environment (please complete the following information):**
 - OS and version: Ubuntu Linux 16.04 but same on macOs and Ubuntu 18.04
 - Compiler: gcc5, gcc7

Thanks a lot for your help.

**Comment by Timothe20** [comment]
I just realised that I forgot to give the initial conditions. here is a tar with everything needed.
[Multiple_test.tar.gz](https://github.com/amusecode/amuse/files/2371391/Multiple_test.tar.gz)

**Comment by Timothe20** [comment]
I am just updating this issue because I looked a bit more closely to what happened. Actually both particle 9 and 35 were involved as scattering stars in an encounter where the SmallN code didn't finished (line 2777 of the log file). They seem to disappear right after it returns to the top level integration. But they should not be removed from the top level...
