### ISSUE TITLE
Numpy 1.15 incompatible with AMUSE

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#302]
Bug reported by @stevemcmillan 

**Describe the bug**
Updating numpy to version 1.15 makes the following bit of code not work anymore (works fine with 1.14):
```python
from amuse.lab import *
import numpy
times = numpy.arange(0|units.Myr, 10|units.Myr, 1|units.Myr)
```

This results in the following:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/steve/amuse/src/amuse/units/quantities.py", line 261, in __ne__
    return self.value_in(self.unit) != to_quantity(other).value_in(self.unit)
  File "/Users/steve/amuse/src/amuse/units/quantities.py", line 226, in value_in
    value_of_unit_in_another_unit = self.unit.value_in(unit)
  File "/Users/steve/amuse/src/amuse/units/core.py", line 359, in value_in
    return self.conversion_factor_from(unit)
  File "/Users/steve/amuse/src/amuse/support/core.py", line 520, in memof
    result=f(*arg)
  File "/Users/steve/amuse/src/amuse/units/core.py", line 302, in conversion_factor_from
    raise IncompatibleUnitsException(x, self)
amuse.units.core.IncompatibleUnitsException: Cannot express none in Myr, the units do not have the same bases`

**To Reproduce**
Update numpy to version 1.15 or higher, try example code

**Expected behavior**
should work normally, not produce an error

**Comment by ipelupessy** [comment]
I am not sure if it is a bug; this behaviour has not been designed for I think:
it is also not recommended: it produces an (inefficient) array with dtype object instead of a
a vector quantity, as:
```
numpy.arange(0,10,1) | units.Myr
```
It may be fixable by adding a len attribute to a scalar object though...

**Comment by ipelupessy** [comment]
actually, it doesn't work on numpy 1.8 either...

**Comment by stevemcmillan** [comment]
Yes, it had occurred to me that it could be worked around that way, but the actual context in which it arose (in examples/textbook/gravity_potential.py and examples/textbook/gravity_gravity.py) is in the line

    times = numpy.arange(0|units.Myr, tend, timestep)
 
where tend and timestep are arguments to a function.  I was hoping this could be repaired at the AMUSE level  before rewriting these (and maybe other) scripts.  But if you say this shouldn’t work, or at least isn’t part of the AMUSE design, I’m sure we can work around it.

**Comment by arjenve** [comment]
We do have an alternative in amuse, so this works

```
from amuse.units import quantities

times = quantities.arange(0|units.Myr, tend, timestep)
```

**Comment by rieder** [comment]
Thanks Arjen! I think that's a good solution for this.
