### ISSUE TITLE
amuse_root_dir confusion

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#306]
get_amuse_root_dir is multiply defined trhoughout the code base, and furthermore
sometimes refers to the directory where build.py lives and sometimes serves as a pointer to the soource code. (these are not the same for out of place builds/installs)

**Comment by arjenve** [comment]
Yes, it lives in different places but the implementation is the same for all these places;

A) it uses a configuration parameter 'amuse_root_dir' from any of the configuration files (configuration files are searched for in several directories, the last one and most important one the current working directory)
B) if not found in the configuration file then we look for the environment variable "AMUSE_DIR"
C) if not found there we try to find it by going down the directory structure and look for "build.py". In this case "build.py" is a way to determine were the src directory lives.

In normal installs (A) will always be available and set to the right install directory, B and C are valid for source builds. Note that out of place builds are not supposed to run and work automatically (these are build directories not run directories), for those cases  one can either make a amuserc file or define the AMUSE_DIR parameter. 

In case of a "non-fixed" installation point (as it is for the binary release) we have auxillary scripts to set the AMUSE_DIR environment variable (as in this case no automatic determination is easily available).

**Comment by ipelupessy** [comment]
ok, so if I run into one of them I can replace it with the one in amuse/support ? (it doesn't live in amuse.config afaik)

also: the amuse_root_dir is always supposed to the location of build.py (ie for installs: $prefix/share/amuse this is what the amuserc will point to)?? I am not sure if this is always the intention in the code (see eg channel.py and core.py in rfi)...

**Comment by arjenve** [comment]
In case of install, yes. The channel code needs the directory of the executable(s) and  will first use another configuration variable (which will be set for installed code) and in case of installed code it will never use the amuse_root_dir attribute.  

I think it is save to refer to the amuse.support version, just check that not circular imports will be created.

**Comment by ipelupessy** [comment]
related 5495b6c

**Comment by ipelupessy** [comment]
fixed by now
