### ISSUE TITLE
hardcoded paths in python workers and java launchers

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#307]
create_java and create_python insert the paths in the templates during build, these should 
instead be replaced with runtime checks (for out of place installs/builds)

**Comment by arjenve** [comment]
Here we have a chicken and egg problem. The scripts are supposed to run without any preset idea about the a.o. the python paths (as it is not always possible to send environment information over from the amuse script to the running code), so we fix these paths at the point of running or at the point of installation. I would be all for a way to do this more dynamically.

**Comment by ipelupessy** [comment]
can't this info be pulled from the environment?

**Comment by arjenve** [comment]
That's the whole problem, although most MPI implementations will send along the environment variables not all do this and some filter the variables. The current solution is the most robust but also least flexible, so maybe a method where first amuse is imported and only if this fails the hardcoded version is used might be an option (the only downside of this method is that the wrong version of amuse might be used if the environment is not correct)
