### ISSUE TITLE
Issues with Nbody6xx inside AMUSE

### ISSUE THREAD

**Issue by dipto4** [amusecode/amuse#314]
**Describe the bug**
Hi,
I wanted to use Nbody6xx in AMUSE to simulate the evolution of a star cluster. However, I encountered a MPI errors when using it. The error was not reproducible with other codes including phiGRAPE and HiGPUs.
I got the following error:
`File "nbody6_first_run.py", line 30, in <module>
    code.evolve_model(4  )
  File "/home/mukherjeed2/senior_comp/amuse/src/amuse/rfi/core.py", line 115, in __call__
    raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}'".format(self.specification.name, type(self.interface).__name__, ex))
amuse.support.exceptions.CodeException: Exception when calling function 'evolve_model', of code 'Nbody6xxInterface', exception was 'Other MPI error, error stack:
PMPI_Wait(183)............: MPI_Wait(request=0x7f52fc365ee0, status=0x1) failed
MPIR_Wait_impl(77)........:
dequeue_and_set_error(596): Communication error with rank 0'`

I ran the program using
`mpiexec -n 1 python nbody6_first_run.py`

**Comment by ipelupessy** [comment]
this could indicate that the code has crashed - do you have a minimal example script that shows this behaviour??

**Comment by arjenve** [comment]
Also, you could start nbody6 with: Nbody6xx(redirection="none") 
This may give some more output and would help in finding the problem

**Comment by rieder** [comment]
I tried running that code (with added lines for importing), it seems to work fine for me.

Is your computer connected to a network when running the script?

**Comment by dipto4** [comment]
Hi,
Thank you all for your help. It turns out there was an error with my mpi libraries. I reinstalled amuse with the correct libraries and it worked fine. One small question, does Nbody6xx inside AMUSE use CUDA by any chance?

**Comment by rieder** [comment]
@maxwelltsai can you answer that?

**Comment by rieder** [comment]
It seems to not be implemented yet.

**Comment by maxwelltsai** [comment]
@dipto4 No, the Nbody6xx inside AMUSE only uses MPI.
