### ISSUE TITLE
set_printing_strategy overrides manually specified preferences for units

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#332]
**Describe the bug**
When using set_printing_strategy, the units specified are always used, even when specifically printing with another unit is requested using "as_quantity_in" or "in_". 
A workaround may be using "value_in" and adding the unit separately, but this is nasty.

**Expected behavior**
Printing a unit with "as_quantity_in" or "in_" should override the "set_printing_strategy" behaviour.

This can occur when e.g. different scales are important in a problem, e.g. star cluster (parsecs) and planetary systems (AU) and/or stellar collisions (RSun). It's very inconvenient to express all of these in the same length unit, but it's still useful to have a "base" length unit.

**Comment by ipelupessy** [comment]
I am opening a new issue on printing strategy (different from this one)
