### ISSUE TITLE
secularmultiple fails on newer compiler, unless -O0

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#333]
**Describe the bug**
secularmultiple fails test, hangs (dirty crash) on newer gcc (8.1.1)

**To Reproduce**
nosetests test/codes_tests/test_secularmultiple.py
on a succesfuil build

**Expected behavior**
tests to finish ok

**Environment (please complete the following information):**
seems connected to gcc version

**Additional context**

offending line 146 in structure.cpp:
```
        P_p->total_system_mass = total_system_mass;
```
the tests pass normally if secularmultiple is compiled with -O0 (everything above fails)

**Comment by ipelupessy** [comment]
need some ideas on this one; the work-around is to ompile with -O0..I have tried to narrow down the casue by trying one-by-one the flags that comprise -O1 vs -O0 and omitting them, neither approach gave more insight...

**Comment by spzwart** [comment]
ill forward your email to Afrian, he is checking this out right now.

**Comment by ipelupessy** [comment]
fixed by 8a24874e38189de3018f7aa635bd1e433461bb0f
