### ISSUE TITLE
Status of P3T

### ISSUE THREAD

**Issue by anthony-arnold** [amusecode/amuse#335]
In [GPU-Enabled Particle-Particle Particle-Tree Scheme for Simulating Dense Stellar Cluster System](https://arxiv.org/abs/1506.04553?context=astro-ph.IM), the authors mention that the code is available as part of AMUSE. I can't see it anywhere in the included community libraries.

Was this code ever a part of AMUSE? Is it possible to get a hold of it anywhere?

**Comment by rieder** [comment]
I think the code referred to in this article is available as “pikachu” in AMUSE.

**Comment by anthony-arnold** [comment]
So it is. Wow, I wouldn't have guessed to look in there. Thanks so much!
