### ISSUE TITLE
Make AMUSE-written txt files automatically readable by AMUSE

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#337]
**Is your feature request related to a problem? Please describe.**
When a particle set is written to disk in txt format:
```python
p = new_plummer_model(10)
write_set_to_file(p, "particles.txt", "txt")
```
the file is not automatically readable on doing the reverse:
```python
q = read_set_from_file("particles.txt", "txt")
```
Instead, we have to manually specify `attribute_types` and `attribute_units`:
```python
q = read_set_from_file(
    "particles.txt",
    "txt", 
    attribute_names=('mass','radius','vx','vy','vz','x','y','z'),
    attribute_types=(
        nbody_system.mass, nbody_system.length,
        nbody_system.speed, nbody_system.speed, nbody_system.speed,
        nbody_system.length, nbody_system.length, nbody_system.length,
    )
)
```

**Describe the solution you'd like**
It would be better if we can construct a file header that would allow the file to be read automatically.

**Comment by ipelupessy** [comment]
answer: yes, in fact text.py in io contains already code for this...wondering why requested feature is not working yet...

**Comment by ipelupessy** [comment]
aha, it is implemented for csv (derives from txt)!

**Comment by ipelupessy** [comment]
is the csv work-around accepted?

**Comment by rieder** [comment]
No - but I think the "amuse-txt" format is acceptable (I didn't know it existed).
