### ISSUE TITLE
Travis openmpi/linux fails

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#351]
**Describe the bug**
OpenMPI/Linux tests fail on Travis, not exactly sure why.

#350 disables these tests for now, since in practice it works fine and it seems better to get at least some useful feedback from testing (instead of them always failing).

**Comment by ipelupessy** [comment]
it used to work, but then something changed on the test machines/configurations (you can go back in history to retry one of the commits that passed and see them fail), so I was hoping it catch it working again;-) in any case maybe better to set allow_failure for this test?

Can you confirm the test works on real machine with the same config??

there is another problem with the travis script, it passes sometimes while tests are failing...

**Comment by rieder** [comment]
Need to test this with the updated config

**Comment by ipelupessy** [comment]
travis retired
