### ISSUE TITLE
Don't use wildcard imports in AMUSE base code

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#354]
In many places in the AMUSE code (particularly, but not limited to, community code interfaces), wildcard imports (e.g. 'from amuse.community import *') are used.
These should be avoided and replaced by imports of only the necessary bits.

**Comment by rieder** [comment]
Also, in many places unused code is imported. This should be avoided.

**Comment by rieder** [comment]
@spzwart @stevemcmillan @ipelupessy and myself decided that this should be fixed. Internally in AMUSE, we should never use import *.

**Comment by ipelupessy** [comment]
closing, I think we are doing this thing now, but there is no need for an issue
