### ISSUE TITLE
Fix 'Unnecessary semicolon' issue in interface definitions

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#360]
[CodeFactor](https://www.codefactor.io/repository/github/amusecode/amuse/overview/master) found an issue: Unnecessary semicolon

for example:
[src\amuse\community\fi\interface.py:373
](https://www.codefactor.io/repository/github/amusecode/amuse/source/master/src/amuse/community/fi/interface.py#L373)

but also in other interface files

**Comment by rieder** [comment]
This can be automatically fixed with `autopep8 --select E703 -i (*.py)`.

**Comment by ipelupessy** [comment]
fixed
