### ISSUE TITLE
Unit from quantity?

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#364]
There is new_quantity_from_unit in amuse.units.quantities, but I wonder if there is a similar function to do the reverse (e.g. new_unit_from_quantity) somewhere?
This could be useful when creating a new unit which depends on a quantity (e.g. lightminute - constants.c * units.minute) where now a quantity is generated. 
If it doesn't exist, the following would work:
```python
def new_unit_from_quantity(x):
    return x.value_in(x.unit) * x.unit
```

Sidenote: is there a reason why quantities cannot also be units (and vice versa)? I think in Astropy they are the same...

**Comment by spzwart** [comment]
The difference between units and quantities and value was initiated by 
Marosvolgii, who was rather religious about the topic.

I see no particular reason why a quantity could not be a unit. pi is a 
good example of a unit as wel as a quantity..

**Comment by rieder** [comment]
I would be in favour of abolishing the difference then. It would also make it easier to make Amuse units compatible with Astropy at some point.

**Comment by ipelupessy** [comment]
well, a scalar quantity has a method to_unit which does exactly this. In general, the difference is important (think about vector quantities...)

**Comment by ipelupessy** [comment]
it even has two methods for this (as_unit, to_unit)..

**Comment by rieder** [comment]
> it even has two methods for this (as_unit, to_unit)..

Thanks, that's what I was looking for.

> In general, the difference is important (think about vector quantities...)

I can see why a VectorQuantity is a Quantity but not a Unit, but I still don't see why a Quantity cannot be a Unit...

**Comment by ipelupessy** [comment]
well quantitiy and units are two fundamentally different things (e.g. you cannot sum units) - so making this destinction seems natural. 

practically speaking, we also do some heavy memoization on the unit operations, which doesn't work if the number of units is unlimited (if every quantity is a unit), 

not to say it is not possible to define a __ror__ for scalar quantities which does:
```
def __ror__(self, value):
    return value | self.as_unit()
```
this may or may not have no unpleasant side effects... (in any case it removes some of the safe guards against unit/quantity errors)

**Comment by ipelupessy** [comment]
well..let me know if you have specific examples...

btw @noisegate, care to comment on the above?

**Comment by ipelupessy** [comment]
workaround available
