### ISSUE TITLE
Retrieve unique particles in a Particleset?

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#369]
Currently, a Particleset can have duplicate particles, and `particleset.has_duplicates()` returns True if this is the case.
Would it be possible to implement a function (e.g. `particleset.no_duplicates()`) that returns each particle only once (so duplicate particles are not counted more than once)? Or would this return unpredictable results (since duplicates can have different values)?

**Comment by ipelupessy** [comment]
I think you wouldn't want to create a set with duplicates to begin with - how do you get one?

**Comment by rieder** [comment]
This would happen by doing something wrong, or by being sloppy (i.e. not checking for duplicates when adding multiple possibly overlapping subsets to a model). 
It's not high priority, obviously...
