### ISSUE TITLE
Duplicate code in amuse.ext

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#372]
amuse.ext contains a few modules that have since been integrated in other modules, e.g. bridge in amuse.couple, gasplummer in amuse.ic.
Maybe we can clean this up, by letting the amuse.ext versions just import the non-ext versions for compatibility (like amuse.community.simplex2_5 imports amuse.community.simplex)?

Incomplete list of suspected duplicates:
- amuse.ext.bridge -> amuse.couple.bridge
- amuse.ext.galactics_model -> amuse.community.galactics ?
- amuse.ext.plummer -> amuse.ic.plummer
- amuse.ext.salpeter -> amuse.ic.salpeter
- amuse.ext.gasplummer -> amuse.ic.gasplummer

**Comment by ipelupessy** [comment]
- ext bridge and couple bridge are different implementations (i prefer the ext ;-) )
- galactics_model contains convenience functions to genereate galaxy ICs (and calls the galactics code), analogous to new_plummer_model; should move to amuse.ic
- plummer, salpeter already moved
- gasplummer should move...

**Comment by ipelupessy** [comment]
this looked like wip
