### ISSUE TITLE
Revamp AMUSE website

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#373]
The current website amusecode.org is very much out of date in many respects. 
We should update it, preferably with something simpler.
It should contain:
- Download link (source and binary release/docker image)
- Installation manual
- Further documentation (link to the AMUSE book, further material?)
- Which papers have used AMUSE
- Showcases
- Contact (link to github?) / licence / credits

Perhaps it would be easiest to use Github Pages for this? https://pages.github.com

**Comment by rieder** [comment]
I think github pages would support the current documentation, which would be a definite benefit.
I will make a trial page in my fork.

**Comment by rieder** [comment]
See https://rieder.github.io/amuse/

**Comment by rieder** [comment]
I've pushed some updates to this page. I think we should aim to replace the current website rather sooner than later, so please let me know which **essential** bits are currently missing (except for a more detailed installation page, which I am working on now).

**Comment by rieder** [comment]
I'm currently happy enough with the new website for it to replace the current amusecode.org one.

**Comment by rieder** [comment]
@ipelupessy @spzwart @stevemcmillan I'd appreciate your input. Is anything *essential* missing from https://rieder.github.io/amuse/ ?

**Comment by ipelupessy** [comment]
I think the following need to be there (eventually)
1) logo 
2) link to documentation
3) tutorial with walkthrough of basic example
4) simple examples with the pictures

**Comment by ipelupessy** [comment]
what do you want to do with the old site?

**Comment by rieder** [comment]
> I think the following need to be there (eventually)
> 
> 1. logo
> 2. link to documentation
> 3. tutorial with walkthrough of basic example
> 4. simple examples with the pictures

Thanks. I agree - also on the "eventually" part (I think it's more important to have up-to-date basic info).

> what do you want to do with the old site?

I'd like to move it to www.amusecode.org/old for now. That way it's still accessible (and this solves the issue of not having the documentation in the new structure yet).

**Comment by rieder** [comment]
I've (provisionally) fixed points 1 and 2 now.

**Comment by rieder** [comment]
I've re-added the gallery (which for now is just the same as the old gallery)

**Comment by rieder** [comment]
Also pushed the getting started tutorial (slightly updated)

**Comment by rieder** [comment]
The new website is now live.

**Comment by ipelupessy** [comment]
ok, great!
