### ISSUE TITLE
Configure warnings about NETCDF

### ISSUE THREAD

**Issue by DavidJJansen** [amusecode/amuse#374]
Running 'configure' in amuse 11.2 with all prerequisites installed gives a warning:

checking Fortran netcdf presence... configure: WARNING: Cannot compile or link against library Fortran NETCDF in /

Configure completes ok, and building the code works fine, although I don't know if the issue will pop up in any of the included community codes.

Since it is only the Fortran part of netcdf that seems to fail, I did some digging. It turns out I can get rid of the warning with:
export FCFLAGS="-I/usr/lib64/gfortran/modules"
and running 'configure' with the option "--with-netcdf=/usr" (the "/" at the end of the warning seems to be the location used if --with-netcdf isn't explicitly set).
So somehow, netcdf installed in the system default location isn't found, and fortran needs an explicit reference to the modules directory that looks like the compiler's default location.

Perhaps interesting to note as well, that netcdf isn't listed on the website as a prerequisite.

Operating system:
RedHat Enterprise 7.6 and Fedora 29 (both give the same output)
Amuse version: 11.2

**Comment by ipelupessy** [comment]
no this will work ok for AMUSE, netcdf is not needed...
