### ISSUE TITLE
Corrections in the prerequisites installation instructions for ubuntu

### ISSUE THREAD

**Issue by gekaremi** [amusecode/amuse#376]
Good day to all!

I tried to set amuse on Kubuntu 18.10. Most of the instructions for installing prerequest work out of the box. Except for two changes:
1.- **easy_install** is obsolete, but it can be successfully replaced with a **pip** (for installing **mpi4py** and other packages) #375 [I tried to create a commit, please forgive me if it is forbidden to do ._.]
2. Starting with bionic (18.04LTS), **libmpfr4** was replaced with **libmpfr6** https://packages.ubuntu.com/bionic/libmpfr6

Technically, this package( **libmpfr4** or **libmpfr6** ) is in the list of dependencies of another package, **libmpfr-dev**, so it can be removed from the command altogether. But I suspect this package is highlighted separately for clarity.

It is interesting to note that **libmpfr-dev** replaces **libgmp3-dev**, which is also in the list of dependencies.

**Environment:**
 - AMUSE from http://amusecode.org/releases/amuse-11.2.tar.gz

Thank!

P.S.: Maybe it will be useful to include additional packages, like **cython** for codes and **matplotlib** **python-tk** for plot scripts

**Comment by rieder** [comment]
Thanks for this! I will check your pull request. You're right in writing that some of the instructions are outdated. We're looking at different ways to make installing AMUSE easier, but in the meantime we can probably update the current instructions at least.
