### ISSUE TITLE
Installing Amuse using setup.py doesn't recognise MPI

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#383]
**Describe the bug**
Install AMUSE directly via `python setup.py install` instead of running `./configure` first (as would happen when installing via PyPI/pip) results in MPI not being found and some codes not building (on macOS at least). One of the codes not built as a result is Hermite0, while BHTree and ph4 seem to build without problems.

**Expected behavior**
The exact same config.mk file should be produced by both methods

**Environment (please complete the following information):**
 - OS and version: macOS Mojave with OpenMPI, macports and a clean Python 2.7 virtual environment

**Comment by ipelupessy** [comment]
the reason could be simple:
```
self.call(['./configure --disable-mpi'], env=environment, shell=True)
```
on 1174 of setup_codes.py..not sure why this is...

**Comment by rieder** [comment]
Not sure either. But currently, I think it shouldn't be like that.

**Comment by ipelupessy** [comment]
yea, you can remove the  --disable-mpi...

**Comment by rieder** [comment]
Changing that line does the trick and makes things work fine

**Comment by ipelupessy** [comment]
it might have been something with the buildbot machines (currently offline)...

**Comment by rieder** [comment]
Thanks for finding the issue, I totally missed that line.
