### ISSUE TITLE
Make AMUSE modules separately installable

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#386]
AMUSE is currently one big package. This is convenient, but also has a few problems:
- Installing it takes a while
- Not all codes may be needed
- AMUSE is too big for inclusion on PyPI without compromising (some codes are left out currently)
- Some codes remain behind a DOWNLOAD_ONLY flag

It would be nice if we can make AMUSE installable as separate modules. Something like this:
Meta-packages:
- amuse (installs everything: basics + community codes)
- amuse-framework (install basics only)
- amuse-community (install standard community codes currently needed by lab.py)

Basics:
- amuse-io (amuse/io)
- amuse-units (amuse/units)
- amuse-datamodel (amuse/datamodel)
- (etc)

Community:
- amuse-hermite0 (amuse/community/hermite0)
- (etc)

I think this approach would not need separate git archives, just separate setup files. We can have a look at https://github.com/vaexio/vaex to see how this can be done, as they seem to do something very similar.

This might also allow us to do away with DOWNLOAD_ONLY codes, as we can simply package them separately (with licensing as appropriate).

**Comment by ipelupessy** [comment]
I like the idea, however I think we should not rush this, few points to consider:

- at the moment there is a problem that the basic submodules (amuse.io etc) have a bit too much interdependence for this to work...

- we need to think about the relation between amuse and other domain packages; for these a good starting point is https://github.com/eWaterCycle/amuse-framework/tree/muse - which partially agrees with the philosophy here, but not completely

- for users the pip install is nice, but we should also consider more advanced use (e.g. is it possible to work on your own code with a amuse-framework pip install?)

btw: how are the pip packages generated? how can they be tested?

**Comment by rieder** [comment]
No rush needed, but we need to work towards this :).

We could start by a very simple split: framework (so all of io, units, datamodel etc.) and individual community codes. 

It is definitely possible to work on your own code with a pip install (which is essentially the same as installing with 'python setup.py install' - AMUSE will live in site-packages).
I can see two ways:
- outside of the AMUSE namespace - this will have zero restrictions on your code.
- inside the AMUSE namespace (e.g. current community codes) - it may be necessary to be part of the "official" amuse distribution (but I am not sure of that), and it may be necessary to also have your code pip-installable (i.e. have a decent setup.py). Vaex has a similar approach to this, with many modules within the vaex namespace.

**Comment by rieder** [comment]
As an initial project we could try to make packages for the codes I had to leave out for space reasons (EVTwin, SimpleX, MESA).

**Comment by ipelupessy** [comment]
I am not sure I like the way vaex organizes the packages (in seperate trees, with seperate setups), but maybe because I am sure how the installation/ generation of pypi packages goes...

**Comment by rieder** [comment]
I haven't investigated this in detail yet either. I don't think the way vaex organises things is the only way to go though. Once installed though, it is probably similar to how we would want it.

**Comment by ipelupessy** [comment]
I have checked in a branch with a prototype for this (#390)..it introduces a seperate packages library
with subdirectories from which to create partial packages:
```
python setup.py sdist
```
in each (framework, sse implemented)...

**Comment by rieder** [comment]
That’s great!
I will try this out for a bit.

**Comment by ipelupessy** [comment]
so it needs a bit of work to make sure all the scripts are as lean as possible (and also things like version numbers need to be generated)...

**Comment by ipelupessy** [comment]
and dependencies ..

**Comment by rieder** [comment]
Right. But this is a great first step. When this works, trimming down will be much easier than building up from scratch.
Version numbers will require some thought. I think a package like amuse-sse will not need many updates unless either SSE or a fundamental change in AMUSE happens, so we may not want a version number that can 'feel' old (e.g. AMUSE could be version 13 at some point, while amuse-sse would be 11.2). Maybe have it relate to the version of the community code?
Dependencies will need some sorting out, but that shouldn't be too difficult. Start with only basic dependencies (MPI and amuse-framework), and see what else is needed before it works. Only a few dependencies for the whole of AMUSE now, so it can't be much.

**Comment by rieder** [comment]
Since we can't do binary distributions (as we don't know which MPI people will use), we would want to avoid many updates to the community code packages (so they don't need to be recompiled).

**Comment by ipelupessy** [comment]
can you add an example of a meta package?

**Comment by rieder** [comment]
I’ll try!

**Comment by rieder** [comment]
Added a meta package 'amuse', which requires installation of 'amuse-framework' and 'amuse-sse'.

**Comment by rieder** [comment]
I think we can consider this fixed.
