### ISSUE TITLE
Particles.savepoint() returns as undefined!

### ISSUE THREAD

**Issue by JPGlaser** [amusecode/amuse#392]
**Describe the bug**
Following Chapter 2.3.7 of the AMUSE textbook (page 66), the _savepoint_ attribute of a Particle Set being returned as not defined.

**To Reproduce**
Create any Particle Set and attempt to call the attribute _savepoint_ with a given time (including units). An example code is included below:
[[TYCHO] Savepoint Bug.pdf](https://github.com/amusecode/amuse/files/2984171/TYCHO.Savepoint.Bug.pdf)

**Expected behavior**
The Particle Set should be able to store instances of the particle set in memory and have this writable to an HDF5 file to reduce IO overhead.

**Logs**
![image](https://user-images.githubusercontent.com/11276213/54621103-95e84b00-4a3d-11e9-9a60-60f73bce5a65.png)

**Environment (please complete the following information):**
 - OS and version: Ubuntu Linux 18 LTS and CentOS 6
 - Compiler: gcc/5.5.0 and gcc/4.8.1 

**Additional context**
The desire is to use the _savepoint_ function to store fewbody interactions in memory and write out to a single HDF5 at the conclusion of the encounter, reducing IO interactions.

**Comment by spzwart** [comment]
Dear Joseph,
It would help to have the source code, rather than a pdf file.
Simon

**Comment by ipelupessy** [comment]
ok, I think the error is the fact that bodies in the example is a ParticlesSuperset ? Can you confirm by e.g. printing out type(bodies) just before the error? 

it may need to be implemented...

**Comment by JPGlaser** [comment]
@spzwart, apologies on that front, GitHub wasn't allowing me to upload .py files directly to teh comment yesterday for some reason.

@ipelupessy is right though, it does appear to be related to the fact that these particles are sitting in a SuperSet. When use savepoint() on the ParticleSet that makes up the SuperSet, it seems to work fine. 

We can discuss implementing this to SuperSets in the referenced issue above.

However, trying to use it on _gravity.particles_, which is defined by the Particles class, does not work with a slightly different error:
![image](https://user-images.githubusercontent.com/11276213/54716118-6b74bb80-4b2b-11e9-92d2-6a0cbff028ac.png)

**Comment by rieder** [comment]
Hi @JPGlaser, as an alternative to uploading a .py comment, you could instead either use a code block (by placing code between backticks - "`") or otherwise via a gist (https://gist.github.com).

**Comment by ipelupessy** [comment]
for incode particles savepoint will not work - this should be catched and a warning given..I think it may be possible to implement this also, but it isn't at the moment...

**Comment by ipelupessy** [comment]
see #394

**Comment by ipelupessy** [comment]
merged #394

**Comment by ipelupessy** [comment]
probably fixed
