### ISSUE TITLE
Guidelines for naming community packages / modules

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#399]
**Is your feature request related to a problem? Please describe.**
Currently, community code modules (and their functions) aren't named consistently.
E.g. a code 'hermite0' has a function 'HermiteInterface'; 'bhtree' has 'BHTreeInterface'; 'phiGRAPE' has 'PhiGRAPEInterface'.
It would be preferable to have consistent naming for all of these, especially now that we are moving to a modularly installable AMUSE.

**Describe the solution you'd like**
I propose that:

- modules are always named with lowercase only (there are very few exceptions anyway)

- the functions should be in either UpperCamelCase or lowerCamelCase (Upper would be most in line with the current situation but lower looks better in my opinion). No additional capitalisation should be used, even if this is the "proper" name of the code (e.g. 'BHTreeInterface' would become 'BhtreeInterface' or 'bhtreeInterface').

- the name of the module is used exactly in the functions they provide (e.g. 'hermite0' should have 'Hermite0Interface'/'hermite0Interface', *or* 'hermite' should have 'HermiteInterface'/'hermiteInterface'. If additional functions are provided (e.g. in 'fi'), they also use this name followed by an additional description (e.g. 'FiMapInterface'/'fiMapInterface').

- numbers in the name should be avoided, unless we (expect to) support multiple concurrent (and incompatible?) versions of that code

- Current modules and functions not in line with this should import the new names, while displaying a deprecation warning. I see no harm in keeping these names around for the foreseeable future, but we should encourage the stricter naming and not accept new codes not adhering to this.

Related to this would be the naming of packages on PyPI, for which I'm not yet sure what is the best naming scheme (consider possible packages could be from 'community' as well as 'ext', and possibly other *muse projects).
Simplest would be e.g. 'amuse-bhtree', but other options could be 'muse-amuse-bhtree', 'amuse-community-bhtree' and things I did not yet consider...

I'd welcome comments to all of this (@ipelupessy @stevemcmillan @spzwart)

**Comment by rieder** [comment]
Note that pep8 recommends function names should be written with underscores (e.g. 'hermite_interface'; 'fi_map_interface') and not CamelCase (https://www.python.org/dev/peps/pep-0008/#function-and-variable-names).
I would be happy with this choice (it would be consistent with other Python projects and that's generally a good idea), but it would be a more radical departure from the current situation. I'm not sure how others feel about this.

**Comment by ipelupessy** [comment]
the interfaces (low and high level) are not functions but classes. Some names, eg BHTree do follow camel case convention since its recommended that acronyms in camel case are fully capitalized..not to say current names are best...lets hear what others think..

**Comment by rieder** [comment]
You're right of course, classes not functions. Then more of the current names will still be fine probably.

**Comment by stevemcmillan** [comment]
Sorry for the late response.  I think that the lowercase-only name should always be a legal way to reference a module.  Beyond that, I don’t care what other crazy capitalization is used (BHtree, SimpleX, etc.), just so long as I know that the lowercase spelling will work.  However, the original names should be retained so we don’t break anyone’s scripts.

I do agree that the interface name should always be consistent with the module name.

Numbers are not necessarily versions, though — for example, the 4 in ph4 refers to the order of the integrator.  I could easily imagine extending it to ph6, so the 4 and 6 are meaningful and necessary.  Hermite0 is an oddball.  Since we don’t have a Hermite, we could perhaps rename it (but preserving Hermite0 as an alias).  The 0 really means that it is a rather primitive shared-tilmestep integrator.  Not the best naming scheme, I agree…

I don’t like deprecation messages, but we should try to ensure that all new modules follow our guidelines.

Steve

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by rieder** [comment]
Thanks Steve.

PR #409 (https://github.com/amusecode/amuse/pull/409 <https://github.com/amusecode/amuse/pull/409>) is an attempt at fixing this.

One problem is that phiGRAPE cannot be renamed while also keeping the old name for backwards compatibility, since the only difference is in capitalisation... 

I'm not sure what the best approach is - we could rename it to e.g. phi_grape, phigpu or something and keep the old name for compatibility, but I don't like that approach.

We could also just rename and let anyone relying on phigrape make a small adjustment to their scripts...

Or we could keep the name as it is and be inconsistent.

**Comment by stevemcmillan** [comment]
Not sure I understand -- phiGRAPE and phigrape are different in Python, aren’t they?

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by stevemcmillan** [comment]
…and won’t that also be true of Hermite and BHtree?

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by rieder** [comment]
Yes - but some filesystems that we support can't deal with directories that differ in capitalisation only, so this can cause very annoying problems.

**Comment by stevemcmillan** [comment]
Ah — MacOS included!  Now I get it — I thought the changes would only apply to naming schemes in Python, but of course the directory is part of the module specification.  But don’t we already have the convention that the directories are lowercase?  I thought we did, in which case phiGRAPE appears to be the only exception.  I think we should enforce that convention and live with breaking a few scripts.  I don’t know if there are many anyway.

Steve

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by rieder** [comment]
no - the modules aren't named that way, just the class (and for classes capitalisation is allowed/recommended)

**Comment by stevemcmillan** [comment]
We have 25 references to phiGRAPE in the examples directory.

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by stevemcmillan** [comment]
Actually, 15 to phiGRAPE and 10 to phigrape, in 15 files.

./textbook/gravity_potential.py
./textbook/gravity_drifter.py
./textbook/old_evolve_triple_with_wind.py
./textbook/gravity_gravity_old.py
./textbook/gravity_gravity.py
./simple/galactic_center_in_code.py
./simple/pythagorean.py
./simple/galactic_center.py
./syllabus/gravity_potential.py
./applications/test_plummer_sphere_on_grid.py
./applications/test_smallcluster_async.py
./applications/test_smallcluster.py
./applications/validate_bridge.py
./validation/particles_and_gas_in_cluster.py
./validation/particles_and_multiples.py

Does anyone use a GRAPE now?

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by rieder** [comment]
Nearly done renaming them all in the PR :).

**Comment by stevemcmillan** [comment]
PR?

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by rieder** [comment]
pull request (https://github.com/amusecode/amuse/pull/409 <https://github.com/amusecode/amuse/pull/409>)

**Comment by stevemcmillan** [comment]
Ah — sorry!

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by ipelupessy** [comment]
> Does anyone use a GRAPE now?

phigrape is also gpu enabled (saporro)

**Comment by stevemcmillan** [comment]
Isn’t that phigpu?

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by rieder** [comment]
Definitely the amuse phigrape works with gpus.
