### ISSUE TITLE
Create a searchable web interface for indexing user-made AMUSE scripts

### ISSUE THREAD

**Issue by maxwelltsai** [amusecode/amuse#404]
To facilitate AMUSE-script sharing, it would be worthy to consider creating a website interface in the AMUSE website, so that 

- AMUSE users who wish to share their scripts can submit a title, a brief description, and a link to their source code.

- AMUSE users who wish to search for existing scripts could put their keywords to the web interface.

**Comment by ipelupessy** [comment]
note that https://github.com/amusecode/amuse-sandbox is the old repository for this sort of thing;
would be nice if people add to this..

**Comment by gekaremi** [comment]
Probably something like this site for MESA users http://cococubed.asu.edu/mesa_market/ and http://cococubed.asu.edu/mesa_market/inlists.html wit table of papers + scripts

**Comment by rieder** [comment]
Yes that looks good to me.

To make sure it gets updated we should have an easy process for people to add their articles.

Maybe we should write a script that processes a database file people can add their own article to? 
Does anyone know how MESA does this?

**Comment by spzwart** [comment]
maybe Erik Deul can setup something like this?
simon

**Comment by rieder** [comment]
Yes - or we can do it just manually and strongly advise people to let us know about their articles (e.g. add it to the "cite these papers" bit).
I've added a test page for this on the new website: https://amusecode.github.io/papers

**Comment by rieder** [comment]
This script (https://www.astrobetter.com/blog/2020/02/17/bibmanager-a-bibtex-manager-designed-for-astronomers/) could be very useful for this. We'd need users to set up their ADS token though.

**Comment by ipelupessy** [comment]
no progress on this. Closing. If its still on the wishlist reopen. or new issue preferably with a more concrete goal.
