### ISSUE TITLE
Gadget on more than 32 cores

### ISSUE THREAD

**Issue by twijnen** [amusecode/amuse#41]
Gadget only runs on more than 32 cores, if the following change is made in src/amuse/rfi/channel.py, line 1223:

if not self.hostname is None:
  #self.info = MPI.Info.Create()
  #self.info['host'] = self.hostname
  self.info = MPI.INFO_NULL
else:
  self.info = MPI.INFO_NULL

**Comment by rieder** [comment]
I'm not sure what self.info is used for, but this change would reduce this bit of code to simply "self.info = MPI.INFO_NULL", so self.info['host'] would never be set. 
Seems that there is either a bigger issue, or maybe self.info is not at all needed?

**Comment by ipelupessy** [comment]
can you remember what the symptoms where? (ie did not startup or run crashes etc??)
