### ISSUE TITLE
Update download scripts for DOWNLOAD_ONLY codes

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#420]
Currently, the download scripts (e.g. download_http.py for rebound) don't seem to work on Python3, even with the automatic 2to3 conversion. This will need some manual attention (and perhaps a bit of generalisation).

**Comment by ipelupessy** [comment]
any specific error?

**Comment by ipelupessy** [comment]
also if possible, they better be replaced by a git or wget command?

**Comment by rieder** [comment]
output from running
```
2to3 -w download_http.py
python3 download_http.py
```
is
```
download_http.py:121: DeprecationWarning: MyFancyUrlopener style of invoking requests is deprecated. Use newer urlopen functions/methods
  opener = MyFancyUrlopener()
Traceback (most recent call last):
  File "download_http.py", line 153, in <module>
    main(**options.__dict__)
  File "download_http.py", line 134, in main
    instance.start()
  File "download_http.py", line 122, in start
    filename, httpmessage, code = opener.retrieve(url, filename = os.path.join(self.src_directory(),filename))
  File "download_http.py", line 17, in retrieve
    url = urllib.unwrap(urllib.toBytes(url))
AttributeError: module 'urllib' has no attribute 'unwrap'
```

**Comment by ipelupessy** [comment]
hmm, I see its the modules that have moved and some prints...

**Comment by rieder** [comment]
I think this script could definitely be simplified, but I wouldn't do it with a git checkout (we don't need all the git overhead). Wget is possible, but I'd want to use curl as well then as a fallback (macOS doesn't have wget by default). But probably we can do it just with python and I'd prefer that.

**Comment by rieder** [comment]
yes, much of urllib has changed with py3.

**Comment by ipelupessy** [comment]
ok, lets fix the python script then (and maybe take care all use the same)...I think some codes do use wget and or git (but maybe mainly in omuse)...

**Comment by rieder** [comment]
This needs checking... I think it's not working properly yet.

**Comment by rieder** [comment]
This issue is a blocker for AMUSE 13 for me. Some codes can't be downloaded/installed yet. I will see if I can get around to it today.

**Comment by rieder** [comment]
Fixed. The scripts are much less fancy now but they work just fine.

**Comment by rieder** [comment]
Also apart from very small differences they're identical now. Should consolidate them at some point.
