### ISSUE TITLE
Error in PowerLawCutoff_profile potential

### ISSUE THREAD

**Issue by webbjj** [amusecode/amuse#427]
Currenty for the PowerLawCutoff_profile potential, get_potential_at_point returns the following:

-2.*np.pi*self.G*self.rho0_r0_to_alpha*self.rc**(3.-self.alpha)/r* \
            (gamma(1.5-0.5*self.alpha)*gammainc(1.5-0.5*self.alpha,r_rc**2)+r_rc*gamma(1.-0.5*self.alpha)*(1.-gammainc(1.-0.5*self.alpha,r_rc**2)))

However comparing directly to GALPY potential, I think the function should be returning:

-2.*np.pi*self.G*self.rho0_r0_to_alpha*self.rc**(3.-self.alpha)/r* \
             (gamma(1.5-self.alpha/2.)*gammainc(1.5-self.alpha/2.,(r/self.rc)**2.)-(r/self.rc*gamma(1.-self.alpha/2.)*gammainc(1.-self.alpha/2.,(r/self.rc)**2.)))

I stumbled across this error when comparing the results of AMUSE's MWpotentialBovy2015 to Galpy's MWPotential2014, which should be the same. The other components of the potential appear to be correct.

Jeremy

**Comment by ipelupessy** [comment]
the expression indeed seems wrong, but can you format the galpy expression here correctly so I can check??

**Comment by ipelupessy** [comment]
ok, I worked it out, and fixed, thanks!
