### ISSUE TITLE
12.0 release notes

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#429]
Tracker for changes / fixes in the 12.0 release.

- #409 Consistent naming of community codes
- #390 Install with packages
- Many relatively small fixes
- Other things that should be announced?

**Comment by ipelupessy** [comment]
improved async support

**Comment by rieder** [comment]
Announce that this is the last major release targeted at Python 2?

**Comment by rieder** [comment]
#356 refactoring of async

**Comment by ipelupessy** [comment]
yes, probably true..

**Comment by ipelupessy** [comment]
Improved async support: allow multiple async request per code, allow code calls to have requests as input

**Comment by rieder** [comment]
I think we're ready for a proper v12 now. I'll build and upload the packages and send out release notes.

**Comment by rieder** [comment]
@ipelupessy I'll send you a final draft first
