### ISSUE TITLE
add python cycler to list of prerequisites

### ISSUE THREAD

**Issue by DavidJJansen** [amusecode/amuse#432]
Many codes and examples fail if the python module 'cycler' is not installed. 

It is used through matplotlib, but apparently not required by it, at least, when installing matplotlib from rpm on CentOS 7, it isn't included. This may be due to matplotlib versions, in Fedora 29 and in Ubuntu 19.04, cycler is installed as dependency of matplotlib.
Perhaps with the move to the pip-based install of amuse, it could be listed as dependency of one of the packages.

**Comment by rieder** [comment]
I think it wasn’t a requirement for earlier versions of matplotlib, but it is now?
Maybe we should require/support a minimum version of matplotlib that does have this prerequisite?

**Comment by DavidJJansen** [comment]
indeed, CentOS of course comes with an older version of matplotlib without cycler. but some of the amuse plot routines or code used in examples requires cycler.
So either require a newer matplotlib, or require cycler as additional dependency will solve the issue.

**Comment by ipelupessy** [comment]
I don't like to add dependencies for trivial tasks like cycler - we could change the examples to not require them, or add a simple implementation as fallback...

**Comment by rieder** [comment]
I’m in favour of a newer matplotlib then. That’s simpler. 
It’s a “soft” dependency currently, maybe we should just install it as a hard dependency of the full “amuse” package (but not “amuse-framework”).
