### ISSUE TITLE
amuse-framework 12.0.0.rc5 fails to install

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#436]
Installation on a clean virtualenv (on macOS) fails with this error:
```
  error: [Errno 2] No such file or directory: 'bin/amusifier'
  ERROR: Failed building wheel for amuse-framework
  Running command /Users/rieder/Env/Amuse2pip3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/p0/3kksqsgd2ll_9xn3yh7m75c00000gn/T/pip-install-tjdtKK/amuse-framework/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  /private/var/folders/p0/3kksqsgd2ll_9xn3yh7m75c00000gn/T/pip-build-env-jhQjs2/overlay/lib/python2.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '12.0.0.rc5' to '12.0.0rc5'
    normalized_version,
  running clean
  running clean_codes
  Cleaning libraries and community codes
  running clean_python
ERROR: Could not build wheels for amuse-framework which use PEP 517 and cannot be installed directly
```
Perhaps related to moving of the amusifier script?

**Comment by ipelupessy** [comment]
my first thought is configure failed...should be visible with -v
I have checked myself and everything seems ok on linux, python 27

**Comment by ipelupessy** [comment]
this is with amuse-framework-12.0.0rc4.post1 .. any difference with rc5?

**Comment by ipelupessy** [comment]
ok, the rc5 version on pypi has a config.mk ... so not properly cleaned up (can you track how this came to be, probably something that can be improved...)

**Comment by rieder** [comment]
Ok, thanks, I’ll check!
I’m sure I did a ‘git clean’ before building the package though...

**Comment by ipelupessy** [comment]
ok, if I do a python setup.py sdist from the amuse-framework dir it doesn't include it even if I don't do git clean...

**Comment by ipelupessy** [comment]
(as it should? it is not in the manifest)

**Comment by rieder** [comment]
Strange... indeed it shouldn’t be included of course.

**Comment by rieder** [comment]
Solution: `git clean -xf` instead of `git clean -f`. Uploaded rc6.
Fixed.
