### ISSUE TITLE
amuse-twobody fails to build

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#444]
```
****************************************************************************************************
Building libraries and codes
****************************************************************************************************
****************************************************************************************************
Building code: twobody, target: all, in directory: build/temp.macosx-10.14-x86_64-2.7/codes/twobody
****************************************************************************************************
make: Map '/Users/rieder/Code/Amuse/packages/amuse-twobody/build/temp.macosx-10.14-x86_64-2.7/codes/twobody' wordt binnengegaan
/Users/rieder/Env/Amuse2pip/share/amuse/build.py --type=py --mode=mpi -x amuse.community.twobody.interface TwoBodyInterface TwoBodyImplementation -o twobody_worker
Usage: build.py [options] name_of_module name_of_class_in_module.
    
    or: build.py --mode=dir name_of_the_code
    
    This script will generate code from the class with name <name_of_class_in_module>. The
    class must be defined in the module <name_of_module>. The module name
    can be a python file or the python module name.
    
    If mode is dir the script will create a directory with all files
    needed to start creating a code interface.
    
    This script handles all code generation for the AMUSE framework. It can
    be used to create C++ or Fortran code to handle the MPI messages, 
    create a header file or create stub code as a start for defining
    the interface between the code and AMUSE.
    
    Examples
    --------
    To generate code for interfacing with MPI do:
        build.py --type=c --mode=mpi test.py TestInterface
    or (for fortran):
        build.py --type=f90 --mode=mpi test.py TestInterface
        
    To generate a header file do (for C):
        build.py --type=h test.py TestInterface
    or (for C++):
        build.py --type=H test.py TestInterface
        
    To generate a stub file do:
        build.py --type=c --mode=stub test.py TestInterface
    or (for fortran):
        build.py --type=f90 --mode=stub test.py TestInterface
        
    To generate create a directory and put files in it do:
        build.py --type=c --mode=dir MyCode
    or (for fortran):
        build.py --type=f90 --mode=dir MyCode
    
    To see a description of all arguments do:
        build.py --help
    
    

build.py: error: No module named twobody.interface
make: *** [Makefile:11: twobody_worker] Fout 2
make: Map '/Users/rieder/Code/Amuse/packages/amuse-twobody/build/temp.macosx-10.14-x86_64-2.7/codes/twobody' wordt verlaten
```

**Comment by ipelupessy** [comment]
this is the annoying "works here" kind of bug...

**Comment by ipelupessy** [comment]
is this with amuse-framework pip installed?

**Comment by rieder** [comment]
yes...

**Comment by rieder** [comment]
this line is puzzling to me:
`build.py: error: No module named twobody.interface`

**Comment by rieder** [comment]
For me it doesn't work either on macOS or on Linux, both with clean environments (or with pip install --upgrade)

**Comment by vantonuccio** [comment]
I confirm the installation problems. I am trying to install on a Scientific Linux system, and I get a long series of errors (one for each package):

    ----------------------------------------
    ERROR: Failed building wheel for amuse-twobody
    Running setup.py clean for amuse-twobody
    ERROR: Complete output from command /opt/Python-2.7.9/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-9A6wax/amuse-twobody/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
    ERROR: running clean
    running clean_codes
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9A6wax/amuse-twobody/setup.py", line 59, in <module>
        data_files=all_data_files,
      File "/tmp/pip-build-env-CifcRt/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/Python-2.7.9/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/Python-2.7.9/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/Python-2.7.9/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "support/setup_codes.py", line 1237, in run
        self.run_command(cmd_name)
      File "/opt/Python-2.7.9/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/opt/Python-2.7.9/lib/python2.7/distutils/dist.py", line 971, in run_command
        cmd_obj.ensure_finalized()
      File "/opt/Python-2.7.9/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "support/setup_codes.py", line 266, in finalize_options
        from amuse import config
      File "/tmp/pip-build-env-CifcRt/overlay/lib/python2.7/site-packages/amuse/__init__.py", line 41, in <module>
        raise ImportError("amuse is not configured correctly")
    ImportError: amuse is not configured correctly
    ----------------------------------------
    ERROR: Failed cleaning build dir for amuse-twobody
  Successfully built amuse-framework
  Failed to build amuse-athena amuse-bhtree amuse-brutus amuse-bse amuse-capreole amuse-evtwin amuse-fastkick amuse-fi amuse-fractalcluster amuse-gadget2 amuse-galactics amuse-galaxia amuse-halogen amuse-hermite amuse-hop amuse-huayno amuse-kepler amuse-kepler-orbiters amuse-mameclot amuse-mercury amuse-mmams amuse-ph4 amuse-seba amuse-secularmultiple amuse-simplex amuse-smalln amuse-sphray amuse-sse amuse-twobody
  ERROR: Could not build wheels for amuse-athena, amuse-bhtree, amuse-brutus, amuse-bse, amuse-capreole, amuse-evtwin, amuse-fastkick, amuse-fi, amuse-fractalcluster, amuse-gadget2, amuse-galactics, amuse-galaxia, amuse-halogen, amuse-hermite, amuse-hop, amuse-huayno, amuse-kepler, amuse-kepler-orbiters, amuse-mameclot, amuse-mercury, amuse-mmams, amuse-ph4, amuse-seba, amuse-secularmultiple, amuse-simplex, amuse-smalln, amuse-sphray, amuse-sse, amuse-twobody which use PEP 517 and cannot be installed directly
..................................

**Comment by rieder** [comment]
I think the other build failures are not directly related to this, so I reopened #440.

**Comment by ipelupessy** [comment]
I have similar problems where an old amuse-framework install (not correctly configured) keeps being used by pip, where a python setup.py build works fine (win the same virtualenv)

**Comment by ipelupessy** [comment]
works if I delete the pip cache... (in ~/.cache/pip, but probably system dependend location)

**Comment by ipelupessy** [comment]
(twobody from pipy fails though)

**Comment by ipelupessy** [comment]
ok, I have committed a provisional fix..

**Comment by ipelupessy** [comment]
its not completely fixed yet, but I know the problem...btw, there seems no guarantee that pip uses an installed prerequisite python package, instead it will happily fetch and build a new one from pypi...

**Comment by rieder** [comment]
not solved yet for me...

**Comment by rieder** [comment]
strangely though, `python setup.py build` works fine.

**Comment by ipelupessy** [comment]
I am working on it..there is a bit of weirdness (prob from the way pip works), but there is also an issue with the amuse code to create scripts for python/java and cython stuff..

**Comment by ipelupessy** [comment]
if I pip from a local file it works too...

**Comment by rieder** [comment]
for me that doesn't work (??)

**Comment by ipelupessy** [comment]
so originally it tried import from amuse.community.twobody.interface during build (which won't work because its not in amuse yet). so changed it to interface, which should be ok since its called from within the directory..the module location is also used in the executable, and that is now also ok since they are not copied to a seperate dir anymore...apparently during the pip, the cwd is no longer in the path...

**Comment by ipelupessy** [comment]
I have pushed a fix.. can you renew the framework, twobody and distributed packages for test?

**Comment by rieder** [comment]
will do

**Comment by rieder** [comment]
doesn't seem to work yet for pip installing the amuse-twobody tarball in testing for me...

**Comment by ipelupessy** [comment]
cleaned everything?

**Comment by rieder** [comment]
yep... Tried a completely fresh virtualenv.

**Comment by rieder** [comment]
maybe modify twobody.py as well?

**Comment by rieder** [comment]
build.log:
```
****************************************************************************************************
Building libraries and codes
****************************************************************************************************
****************************************************************************************************
Building code: twobody, target: all, in directory: build/temp.macosx-10.14-x86_64-2.7/codes/twobody
****************************************************************************************************
make: Map '/private/var/folders/p0/3kksqsgd2ll_9xn3yh7m75c00000gn/T/pip-req-build-iuYEkL/build/temp.macosx-10.14-x86_64-2.7/codes/twobody' wordt binnengegaan
/private/var/folders/p0/3kksqsgd2ll_9xn3yh7m75c00000gn/T/pip-build-env-9DPq97/overlay/share/amuse/build.py --type=py --mode=mpi -x interface TwoBodyInterface TwoBodyImplementation -o twobody_worker
Usage: build.py [options] name_of_module name_of_class_in_module.
    
    or: build.py --mode=dir name_of_the_code
    
    This script will generate code from the class with name <name_of_class_in_module>. The
    class must be defined in the module <name_of_module>. The module name
    can be a python file or the python module name.
    
    If mode is dir the script will create a directory with all files
    needed to start creating a code interface.
    
    This script handles all code generation for the AMUSE framework. It can
    be used to create C++ or Fortran code to handle the MPI messages, 
    create a header file or create stub code as a start for defining
    the interface between the code and AMUSE.
    
    Examples
    --------
    To generate code for interfacing with MPI do:
        build.py --type=c --mode=mpi test.py TestInterface
    or (for fortran):
        build.py --type=f90 --mode=mpi test.py TestInterface
        
    To generate a header file do (for C):
        build.py --type=h test.py TestInterface
    or (for C++):
        build.py --type=H test.py TestInterface
        
    To generate a stub file do:
        build.py --type=c --mode=stub test.py TestInterface
    or (for fortran):
        build.py --type=f90 --mode=stub test.py TestInterface
        
    To generate create a directory and put files in it do:
        build.py --type=c --mode=dir MyCode
    or (for fortran):
        build.py --type=f90 --mode=dir MyCode
    
    To see a description of all arguments do:
        build.py --help
    
    

build.py: error: No module named interface
make: *** [Makefile:11: twobody_worker] Fout 2
make: Map '/private/var/folders/p0/3kksqsgd2ll_9xn3yh7m75c00000gn/T/pip-req-build-iuYEkL/build/temp.macosx-10.14-x86_64-2.7/codes/twobody' wordt verlaten
****************************************************************************************************
********************************************************************************
Building finished
********************************************************************************
```

**Comment by rieder** [comment]
and again, manually building works fine...

**Comment by ipelupessy** [comment]
I have added a desperate debug message...

**Comment by ipelupessy** [comment]
try again? make sure you cleanout pip caches (didn't work here anyway)

**Comment by ipelupessy** [comment]
btw, the pypi amuse-framework package was not updated with the above patch (the previous)

**Comment by rieder** [comment]
True (but locally for testing I have done this)

**Comment by ipelupessy** [comment]
I have found that if you test locally, it may still pull a remote package for building!!

**Comment by ipelupessy** [comment]
ie a local twobody package will be build against the latest remote amuse-framework...

**Comment by ipelupessy** [comment]
that is why I cannot debug this properly locally:-(

**Comment by rieder** [comment]
Ah that’s weird behaviour... I’ll update the framework then.

**Comment by ipelupessy** [comment]
it sems to be working here, for both python 2 and 3...

**Comment by rieder** [comment]
Updated framework on pypi, now it seems to build properly. Thanks!

**Comment by ipelupessy** [comment]
it was a bit painful, but at least learned a few things about pip!

**Comment by vantonuccio** [comment]
I have not succeeded to install amuse 12.0 using pip. Instead I downloaded the zipped version of the distribution (amuse-master.zip, I hope it is the latest version) from the git and ran configure.
This way I build it and can then build up twobody ("gmake -j 4 twobody.code"). However I still have problems with building flash. I already have a full FLASH v. 4.3 distribution, but the documentation on how to make AMUSE to "see" it is smply missing. Instead I always get the same compilation error:
****************************************************************************************************
Building code: flash, target: all, in directory: src/amuse/community/flash
****************************************************************************************************
make[1]: Entering directory `/home-volume/van/software/python/amuse-master/src/amuse/community/flash'
/home/van/software/python/amuse-11.2/build.py --type=f90 interface.py FlashInterface -o worker_code.f90
make -C . download
mpif90 -g -O2 -fPIC -I./src/FLASH4.2.2/object -c -o interface.o interface.F90
make[2]: Entering directory `/home-volume/van/software/python/amuse-master/src/amuse/community/flash'

*** Unfortunately due to flash download restrictions;
interface.F90:73: error: Flash.h: No such file or directory
interface.F90:74: error: constants.h: No such file or directory
interface.F90:75: error: Particles.h: No such file or directory
interface.F90:77: error: Flash_mpi.h: No such file or directory
*** FLASH CANNOT be download automatically by this makefile
interface.F90:2844: Error: Can't open included file 'Flash_mpi.h'
make[1]: *** [interface.o] Error 1
make[1]: *** Waiting for unfinished jobs....
*** Please register and download flash yourself
*** You can do so at http://flash.uchicago.edu/site/flashcode/coderequest/

make[3]: *** No rule to make target `raise_error'.  Stop.
make[2]: *** [download] Error 2
make[2]: Leaving directory `/home-volume/van/software/python/amuse-master/src/amuse/community/flash'
make[1]: *** [src/makefile] Error 2
make[1]: Leaving directory `/home-volume/van/software/python/amuse-master/src/amuse/community/flash'
****************************************************************************************************
********************************************************************************
Building finished
********************************************************************************

.......
I tried to modify "src" in the flash locale Makefile, with no success.

Any suggestions?

**Comment by ipelupessy** [comment]
to build the flash interface you need the flash source code extracted in the src directory...note that probably flash version 4.2.2 is necessary (but I am not sure)

**Comment by ipelupessy** [comment]
please make a new issue for this...
