### ISSUE TITLE
replace SimpleX  C++ MPI bindings with C calls  

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#446]
this is a bit tedious, and causes divergence from mainline simplex; an alternative would be to include a 1 header file implementation, but afaik this doesn't exist

**Comment by rieder** [comment]
There is no mainline simplex version anymore except this one and the one in Arepo (I asked Jan Pieter about that a little while ago), so we can do as we see fit.

**Comment by ipelupessy** [comment]
#542 fixes this

**Comment by ipelupessy** [comment]
fixed by #542
