### ISSUE TITLE
replace c++ binding (datatypes only?) in higpus

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#451]
higpus has wat looks as some remnants of c++ mpi bindings (datatypes like MPI::BOOL) - these should be fixed (ideally on some machine where gpu stuff can be tested)

**Comment by rieder** [comment]
@mariosperaastro can you creatie a pull request for a fix?

**Comment by mariosperaastro** [comment]
@rieder I'll do that!

**Comment by rieder** [comment]
Fixed by #455
