### ISSUE TITLE
Remove generating of cython workers from Makefiles

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#452]
The cython workers aren't being built properly, so this is just causing confusion at the moment.
This is a remnant of a trial project, and I think it's better removed at this point.

**Comment by ipelupessy** [comment]
yes..I think it is still valuable to retain the framework bits to generate cython code (its not really broken, but the configuration is tricky/ broken)..to test a seperate repository with an example code is sufficient...

**Comment by rieder** [comment]
I won't touch the framework bits :).

**Comment by rieder** [comment]
This was done a little while back.
