### ISSUE TITLE
distributed channel chokes on string array  messages

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#46]
see https://github.com/ipelupessy/amuse/tree/distributed_channel_string_error

to be specific: test_c_distributed_implementation.py:TestCDistributedImplementationInterface.test7d
freezes on:

File "/home/inti/code/amuse/amuse/src/amuse/rfi/channel.py", line 1714, in _receive_all
    data_bytes = thesocket.recv(chunk)

This test tests can_handle_array string function with N=100 input using distributed amuse channel. For me it works for N=10, but not for N much bigger (N=14 fails). echo_int works for N=2000000 fine.

**Comment by arjenve** [comment]
I've tested these on the current head, and all seem to work fine (on different architectures).

**Comment by ipelupessy** [comment]
hmm, still broken here..will try to test on different machines

**Comment by ipelupessy** [comment]
I have tested on the strw machine, and it works, but breaks again if i increase the number of strings to 10000, I have updated the branch to increase the test size...maybe you can try again?

**Comment by ipelupessy** [comment]
I think its fixed now
