### ISSUE TITLE
Problem with mpiexec

### ISSUE THREAD

**Issue by alexolza** [amusecode/amuse#467]
Hi, I'm new. I just installed amuse but I can't run any of the examples. The interactive version seems to work (but I don't know what to do with it at the moment).

-I'm using Ubuntu 18.04.

-The installation was done as in  http://amusecode.org/doc/install/howto-install-AMUSE.html because I was unable to install via pip 

-I chose the MPICH2 way, with Hydra process manager.

When testing, not everything went as desired, but I was (naively) expecting amuse to work anyway. Simplex and galaxia codes were not built because of errors, and a few other community codes were also not built ('need special libraries'). I found an error that might be relevant, but I don't know how to fix it.

**OUTPUT FROM nosetests:**

```
...
test27 (test.codes_tests.test_python_implementation.TestInterface) ... Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)
Traceback (most recent call last):
  File "/home/alex/amuse/src/amuse/rfi/python_code.py", line 81, in start
    self.handle_message(message, result_message)
  File "/home/alex/amuse/src/amuse/rfi/python_code.py", line 185, in handle_message
    result = method(*list(keyword_arguments))
  File "/home/alex/amuse/src/amuse/rfi/python_code.py", line 312, in internal__open_port
    outportname.value = MPI.Open_port(None)
TypeError: Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)
ERROR
...
...
Ran 2573 tests in 3758.237s

FAILED (SKIP=333, errors=27)
```

When trying to run an example, I get the following:

```
alex@portatilalex01:~/amuse$ ./amuse.sh ./examples/textbook/sun_venus_earth.py
[mpiexec@portatilalex01] match_arg (utils/args/args.c:159): unrecognized argument pmi_args
[mpiexec@portatilalex01] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
[mpiexec@portatilalex01] parse_args (ui/mpich/utils.c:1597): error parsing input array
[mpiexec@portatilalex01] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1649): unable to parse user arguments
[mpiexec@portatilalex01] main (ui/mpich/mpiexec.c:149): error parsing parameters
```
Can anybody please help me?

**Comment by ipelupessy** [comment]
sorry for the late reply! about your issues:

- which version of mpich are you using?
- I think the pip install failed because of the build issues, you can set an environment variable to
allow build failures (see #465 )
- simplex may not build because of missing C++ mpich bindings, you can either try to install or build with the bindings (I think they are still available). This is a known issue (needs an update for simplex)
- galaxia should build, it may indicate a fortran issue, so if you can provide the error message that would be appreciated!!
- the test failure is not very important (has been seen before for some versionos of MPICH). The feature that fails is not normally used
- for your last error (the example) ,can you try running with mpiexec in front of the command?

**Comment by alexolza** [comment]
No worries, and thank you! 
I changed to sockets and everything seems to be working fine now, and I don't know if I'll need any of the codes that can't run on sockets. For the moment I'm working on the textbook examples and don't have any problem. Anyway, my version of MPICH is 3.3~a2-4.

 And there goes my error message for galaxia (or so I think- I kept text files of most of the output during the installation steps, so please tell me if it's not what you were asking for!). I get a similar one for simplex.

`ERROR: test1 (test.codes_tests.test_galaxia.TestBarAndSpirals3D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/amuse/test/codes_tests/test_galaxia.py", line 8, in test1
    galaxy= BarAndSpirals3D()
  File "/home/alex/amuse/src/amuse/community/galaxia/interface.py", line 959, in __init__
    legacy_interface = BarAndSpiralsInterface(**options)
  File "/home/alex/amuse/src/amuse/community/galaxia/interface.py", line 99, in __init__
    CodeInterface.__init__(self, name_of_the_worker="GalaxyModel_worker", **options)
  File "/home/alex/amuse/src/amuse/rfi/core.py", line 711, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)
  File "/home/alex/amuse/src/amuse/rfi/core.py", line 730, in _start
    self.channel = self.channel_factory(name_of_the_worker, type(self), interpreter_executable = interpreter_executable, **options)
  File "/home/alex/amuse/src/amuse/rfi/channel.py", line 1347, in __init__
    self.full_name_of_the_worker = self.get_full_name_of_the_worker(legacy_interface_type)
  File "/home/alex/amuse/src/amuse/rfi/channel.py", line 1150, in get_full_name_of_the_worker
    raise exceptions.CodeException("The worker application does not exist, it should be at: \n{0}".format('\n'.join(tried_workers)))
CodeException: The worker application does not exist, it should be at: 
/home/alex/amuse/src/amuse/community/galaxia/GalaxyModel_worker
/home/alex/amuse/src/amuse/rfi/GalaxyModel_worker

======================================================================
ERROR: test2 (test.codes_tests.test_galaxia.TestBarAndSpirals3D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/amuse/test/codes_tests/test_galaxia.py", line 12, in test2
    galaxy= BarAndSpirals3D()
  File "/home/alex/amuse/src/amuse/community/galaxia/interface.py", line 959, in __init__
    legacy_interface = BarAndSpiralsInterface(**options)
  File "/home/alex/amuse/src/amuse/community/galaxia/interface.py", line 99, in __init__
    CodeInterface.__init__(self, name_of_the_worker="GalaxyModel_worker", **options)
  File "/home/alex/amuse/src/amuse/rfi/core.py", line 711, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)
  File "/home/alex/amuse/src/amuse/rfi/core.py", line 730, in _start
    self.channel = self.channel_factory(name_of_the_worker, type(self), interpreter_executable = interpreter_executable, **options)
  File "/home/alex/amuse/src/amuse/rfi/channel.py", line 1347, in __init__
    self.full_name_of_the_worker = self.get_full_name_of_the_worker(legacy_interface_type)
  File "/home/alex/amuse/src/amuse/rfi/channel.py", line 1150, in get_full_name_of_the_worker
    raise exceptions.CodeException("The worker application does not exist, it should be at: \n{0}".format('\n'.join(tried_workers)))
CodeException: The worker application does not exist, it should be at: 
/home/alex/amuse/src/amuse/community/galaxia/GalaxyModel_worker
/home/alex/amuse/src/amuse/rfi/GalaxyModel_worker

======================================================================`

**Comment by ipelupessy** [comment]
ok, great!

Do you have the error of the build/install step for galaxia? This error confirms that the worker is indeed not build or installed...

**Comment by ipelupessy** [comment]
the remaining issue is with galaxia I think, see #505 

I am closing this one.. (we close the issues, don't worry! )
