### ISSUE TITLE
Release AMUSE 12.1

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#494]
We have fixed the important #190 bug, which warrants an important AMUSE update. Since this update is bigger than a "micro" update (it changes the savefile format somewhat), this for me warrants a minor update to 12.1 (so that it is obvious that 12.0 is not fully compatible between Py2/Py3, but 12.1 is).
I will try to build, test and release it today.

**Comment by ipelupessy** [comment]
there is still an issue with the io - testing fails...

**Comment by ipelupessy** [comment]
I pushed a fix - just more of the same...you may want to check the compatability again...

**Comment by rieder** [comment]
Will check tomorrow. Having some build issues on macOS today, Xcode 11 seems to break things...

**Comment by rieder** [comment]
Current working tree has a small but important issue with Hermite (name of the worker is inconsistent), fixed (commit following).

**Comment by rieder** [comment]
Also ph4 had a small issue with literature references not being called (since ph4 has no "official" paper). Calling it now so that at least the AMUSE references are shown.

**Comment by rieder** [comment]
Live on PyPI
