### ISSUE TITLE
Problems with wheels / PEP 517 when trying to create a pip package

### ISSUE THREAD

**Issue by franciscaconcha** [amusecode/amuse#496]
I'm trying to create a pip release (python2.7) for a version of AMUSE including a new community code ([vader](https://bitbucket.org/krumholz/vader/src/master/)) and the interface we've developed for it. I based [my pip package](https://pypi.org/project/amuse-vader/) in the ["original" AMUSE pip package](https://pypi.org/project/amuse/). When I try to install my package, I get the following error:

`ERROR: Could not build wheels for amuse-galaxia, amuse-simplex, amuse-mmams, amuse-brutus, amuse-evtwin, amuse-ph4 which use PEP 517 and cannot be installed directly`

I know this error comes from `wheels`, and found [this](https://discuss.python.org/t/pep-517-and-projects-that-cant-install-via-wheels/791) and [this](https://github.com/pypa/pip/issues/6222) about it, but I'm not sure where to go from here. Any help would be very appreciated, it's my first time creating pip packages.

**Comment by ipelupessy** [comment]
hmmm, what are your prerequisites for the pip package - it should only need amuse-framework (and then at least it will not complain about all these other code package) ..further:
are you trying to create a binary package? otherwise, we usually generate a source package:
```
python setup.py sdist 
```
in one of the package directories (under packages/)...

**Comment by PaoloSuin** [comment]
Actually I had the same problem. To solve it I downloaded the tar.gz directory from the sites.
In the directory with makefile, tried to run 'make' from the shell: it reported an error about the absence of '-llapack' and '-lblas', which are ubuntu libraries.

running the command:

`sudo apt-get install liblapack-dev -y ; sudo apt-get install liblapack3 -y ; sudo apt-get install libopenblas-base -y ; sudo apt-get install libopenblas-dev -y ;`

the installation proceeded without problems.

**Comment by ipelupessy** [comment]
I think the Vader package has been merged (this was the same was it?) ; and there is a solution posted..

close
