### ISSUE TITLE
Allow installation of amuse-framework without mpi4py

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#500]
AMUSE can work without mpi (using sockets), so mpi4py should not be a *hard* requirement for AMUSE.
I think we should always try to install it, but the AMUSE installation should be able to continue if mpi4py was not successfully installed.

**Comment by ipelupessy** [comment]
yes..there is an option in the configure to disable mpi..

**Comment by rieder** [comment]
Is that accessible via pip?

**Comment by ipelupessy** [comment]
no..it also needs testing (in fact a lot of the testing framework should be adapted for this)
