### ISSUE TITLE
error when running one textbook script (examples/applications/test_riemann_shock_tube_problem.py)

### ISSUE THREAD

**Issue by ykzivio** [amusecode/amuse#506]
Hi,
I am trying to do this test script to understand how the SPH community code works inside amuse. I attached the error message appears when I try to run the examples/applications/test_riemann_shock_tube_problem.py script. I am running it on CentOS, AMUSE version 12.0.3, Python 2.7.13, and Numpy 1.12.1. And I also attached the config.log and build.log file. I would be very thankful if someone helps me with this.
 
[build.log](https://github.com/amusecode/amuse/files/3703979/build.log)
[config.log](https://github.com/amusecode/amuse/files/3703980/config.log)

![Screenshot from 2019-10-08 14-21-25](https://user-images.githubusercontent.com/54713401/66422066-fee1e100-e9d6-11e9-9312-4687393a6224.png)

**Comment by ipelupessy** [comment]
which CentOS and do you know what version of MPI you have (OpenMPI or MPICH and which version)??

**Comment by ykzivio** [comment]
> which CentOS and do you know what version of MPI you have (OpenMPI or MPICH and which version)??
CentOS-6.5; OpenMPI 1.8.1; MPICH 3.2

**Comment by ipelupessy** [comment]
hmm, it looks a bit like a openmpi problem (the test is working here fine with recent amuse).. have you tried other examples? Do they run or do some/all of them fail? You can try to prepend  the command with ```mpiexec -n 1```

**Comment by ykzivio** [comment]
> hmm, it looks a bit like a openmpi problem (the test is working here fine with recent amuse).. have you tried other examples? Do they run or do some/all of them fail? 

For the test scripts given in the example/application directory, as far as I've tried the following scripts also fail due to the same reason: test_evrard_collapse.py, test_evrard.py and test_steller_merger.py. The test_smallcluster.py runs properly.

I tried to prepend the command, but does not work.

**Comment by ykzivio** [comment]
I cleaned all the installed mpi on my machine and reinstalled the open mpi. This time it makes the test_rieman_shock* code work properly. I am still testing the other test scripts, and I am not sure if this solution will also make the others codes working

**Comment by rieder** [comment]
Please let us know if you have continuing issues. For now I am closing this issue.
