### ISSUE TITLE
Store v2 writeable by default upon opening for read

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#516]
**Describe the bug**
the following:
```
g=read_set_from_file("test.amuse", "amuse")
g.temperature=11. | units.K
```
opens the file test.amuse for reading but if using v2 storage it also changes the file on the HD
this is not sane default behaviour; hardly anybody uses file i/o this way.

to prevent people accidently destroying their data, I have reverted the default asap to version 1

**To Reproduce**
```
from amuse.units import units
from amuse.datamodel import new_cartesian_grid
from amuse.io import read_set_from_file, write_set_to_file
g=new_cartesian_grid((128,128,128), 1. | units.m)
g.rho=10. | units.kg/units.m**3
write_set_to_file(g,"test.amuse", "amuse", append_to_file=False, version="2.0")
```
then:
```
from amuse.units import units
from amuse.datamodel import new_cartesian_grid
from amuse.io import read_set_from_file, write_set_to_file
g=read_set_from_file("test.amuse", "amuse")
g.temperature=11. | units.K
```
observe file size has changed.

**Expected behavior**
files opened for read should not change unless explicitly told to open for read/write. in fact I prefer
a seperate io function for this. 

(related to this is the default option append_to_file=True. This one is also questionable)

**Comment by ipelupessy** [comment]
related to this:
generate a warning when upon opening a file it turns out to be a incorrect (unexpected) version..

**Comment by rieder** [comment]
Note that even with v1, the files are "touched" and the last modified date is changed to current.

**Comment by ipelupessy** [comment]
for me, that is not the case for version="1.0"...

**Comment by ipelupessy** [comment]
so I am pretty certain about this, but could you post a minimal example otherwise?

**Comment by rieder** [comment]
sure:
```zsh
 (Amuse12.1py2)  srieder@remy  ~/test_file_storage  ls -ltr
total 144
-rw-r--r--  1 srieder  staff    238 28 okt 11:51 test_store.py
-rw-r--r--  1 srieder  staff  18832 28 okt 11:51 test-default.amuse
-rw-r--r--  1 srieder  staff  18832 28 okt 11:51 test-store1.amuse
-rw-r--r--  1 srieder  staff  20864 28 okt 11:51 test-store2.amuse
-rw-r--r--  1 srieder  staff    215 28 okt 11:52 test_store_read.py
 (Amuse12.1py2)  srieder@remy  ~/test_file_storage  python test_store_read.py
 (Amuse12.1py2)  srieder@remy  ~/test_file_storage  ls -ltr                  
total 144
-rw-r--r--  1 srieder  staff    238 28 okt 11:51 test_store.py
-rw-r--r--  1 srieder  staff    185 28 okt 11:54 test_store_read.py
-rw-r--r--  1 srieder  staff  18832 28 okt 11:54 test-default.amuse
-rw-r--r--  1 srieder  staff  18832 28 okt 11:54 test-store1.amuse
-rw-r--r--  1 srieder  staff  20864 28 okt 11:54 test-store2.amuse
```
test_store.py:
```python
from amuse.lab import *

p = new_plummer_sphere(100)

write_set_to_file(p, "test-default.amuse", "amuse")
write_set_to_file(p, "test-store1.amuse", "amuse", version="1.0")
write_set_to_file(p, "test-store2.amuse", "amuse", version="2.0")
```
test_store_read.py:
```python
from amuse.lab import *

p = read_set_from_file("test-default.amuse", "amuse")
q = read_set_from_file("test-store1.amuse", "amuse", version="1.0")
r = read_set_from_file("test-store2.amuse", "amuse", version="2.0")
```

The files aren't modified (checked this with diff), but all files have a new timestamp.

**Comment by rieder** [comment]
I do get an error when trying to set the (not yet existing) attribute "temperature" for the particles loaded from a v2 file though:
```
Traceback (most recent call last):
  File "test_store_read.py", line 9, in <module>
    p.temperature = 11 | units.K
AttributeError: 'dict' object has no attribute 'temperature'
```

**Comment by ipelupessy** [comment]
@rieder hmm, for me your scripts give the same result as previously (ie no timestamp change), it might be that this has something to do with underlying hdf5.open behaviour...can you check wheter if you open the files with h5py.open(..,"a") changes your timestamp? 

I think by default:
- files open with read_set_from_file should not be touched and not writeable
- files written to with write_set_to_file should not exist and not appended to (the current behaviour is that existing files are appended to)

**Comment by rknop** [comment]
For the first part (no touching on reading): would it be sufficient to change the load_base method of HDF5FileFormatProcessor (in amuse/io/store.py) to edit the lines:
```
            processor = store_v1.StoreHDF(
                self.filename, 
                open_for_writing = self.allow_writing, 
                append_to_file = self.append_to_file,
                copy_history = self.copy_history
            )
```
(in all 4 places where they appear, for both store_v1 and store_v2) to set open_for_writing=False and append_to_file=False?  Would this have any unpleasant side effects?

**Comment by ipelupessy** [comment]
I am looking at it, setting both to false means that you cannot open them for read/write..I am at least changing the defaults, and maybe add a seperate open_file method

**Comment by ipelupessy** [comment]
I think this was fixed with saner defaults
