### ISSUE TITLE
MESA unavailable

### ISSUE THREAD

**Issue by alexolza** [amusecode/amuse#519]
Hi, I'm on Ubuntu 18.04 and have been using AMUSE for a month. I'm using sockets because I couldn't get MPI to work when I installed. I also couldn't build some of the codes, but I didn't bother because I didn't need them until now (I'd like to use MESA).

 I ran again `make clean`, `make DOWNLOAD_CODES=1`  and got the following:

```Community codes not built (because of errors):
================================================================================
 * flash
 * galaxia
 * krome
 * mesa
 * mocassin
 * mpiamrvac
 * simplex
Optional builds failed, need special libraries:
 * aarsethzare - cython
 * asterisk - java
 * athena - cython
 * bhtree - cython
 * distributed - java
 * fastkick - gpu
 * fi - gl, periodic_gl
 * gadget2 - cython_periodic, cython_normal, cython_periodic_nogravity, cython_nogravity
 * hacs64 - gpu
 * hermite0 - cython
 * higpus - gpu
 * huayno - cython_cl, cl, cl, cl, cl, cl, cl.so, cl.so, cl.so, cl.so, cl.so, cython, cython_mp, mp.so, mp.so, mp.so
 * kepler - cython
 * mi6 - gpu
 * ph4 - gpu
 * phigrape - gl, grape, gl_gpu, gpu
 * rebound - cython
 * seba - cython
 * smalln - cython
 * sse - cython
Optional builds failed, need CUDA/GPU libraries:
 * sapporo_light
 * bonsai
 * etics
 * octgrav
 * pikachu
Optional builds failed, need additional python packages:
 * tupan
================================================================================
Community codes built
================================================================================
* aarsethzare
* adaptb
* asterisk
* athena (mhd,scalar,selfgrav)
* bhtree
* brutus
* bse
* capreole (mpi)
* distributed
* evtwin
* fastkick
* fi (mp,mp,map,map,map_mp,map_mp,periodic)
* fractalcluster
* gadget2 (periodic,normal,periodic_nogravity,nogravity)
* galactics
* hacs64
* halogen
* hermite0
* higpus
* hop
* huayno (mp,mp,mp)
* kepler
* kepler_orbiters
* mameclot
* mercury
* mi6
* mikkola
* mmams
* mmc
* nbody6xx
* ph4
* phigrape (mpi)
* ramses (1d,2d)
* rebound
* sakura
* seba
* secularmultiple
* sei
* smalln
* sphray
* sse
* twobody
================================================================================
42 out of 49 codes built, 5 out of 6 libraries built
`
If I run `examples/textbook/stellar_minimal.py` I get:

`Traceback (most recent call last):

  File "<ipython-input-9-27864fbded5a>", line 1, in <module>
    runfile('/home/alex/amuse/my_tries/evolution/stellar_minimal.py', wdir='/home/alex/amuse/my_tries/evolution')

  File "/usr/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/alex/amuse/my_tries/evolution/stellar_minimal.py", line 46, in <module>
    main(**o.__dict__)

  File "/home/alex/amuse/my_tries/evolution/stellar_minimal.py", line 10, in main
    stellar = MESA()

  File "/home/alex/amuse/src/amuse/community/mesa/interface.py", line 945, in __init__
    InCodeComponentImplementation.__init__(self, MESAInterface(**options), **options)

  File "/home/alex/amuse/src/amuse/community/mesa/interface.py", line 32, in __init__
    CodeInterface.__init__(self, name_of_the_worker="mesa_worker", **options)

  File "/home/alex/amuse/src/amuse/rfi/core.py", line 711, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)

  File "/home/alex/amuse/src/amuse/rfi/core.py", line 730, in _start
    self.channel = self.channel_factory(name_of_the_worker, type(self), interpreter_executable = interpreter_executable, **options)

  File "/home/alex/amuse/src/amuse/rfi/channel.py", line 2157, in __init__
    self.full_name_of_the_worker = self.get_full_name_of_the_worker(legacy_interface_type)

  File "/home/alex/amuse/src/amuse/rfi/channel.py", line 1150, in get_full_name_of_the_worker
    raise exceptions.CodeException("The worker application does not exist, it should be at: \n{0}".format('\n'.join(tried_workers)))

CodeException: The worker application does not exist, it should be at: 
/home/alex/amuse/src/amuse/community/mesa/mesa_worker
/home/alex/amuse/src/amuse/rfi/mesa_worker```

Can you please help me figure out how to get MESA? Thanks in advance!

**Comment by alexolza** [comment]
I got the following output:

`/usr/bin/python setup.py -v build_code --inplace --clean=yes --code-name=mesa
running build_code
building code mesa
cleaning src/amuse/community/mesa
make -C src/amuse/community/mesa clean
make[1]: Entering directory '/home/alex/amuse/src/amuse/community/mesa'
rm -f -f *~ *.pyc *.mod *.o worker_code worker_code.f90 ./src/mesa/lib/libstar.a
rm -f -f mesa_worker mesa_worker_sockets worker_code-sockets.f90
make -C ./mesa_reqs clean
make[2]: Entering directory '/home/alex/amuse/src/amuse/community/mesa/mesa_reqs'
make[2]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa/mesa_reqs'
make[1]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
make -C src/amuse/community/mesa all
make[1]: Entering directory '/home/alex/amuse/src/amuse/community/mesa'
/home/alex/amuse/build.py --type=f90 interface.py MESAInterface -o worker_code.f90
make -C . download
make[2]: Entering directory '/home/alex/amuse/src/amuse/community/mesa'
rm -f -Rf src
mkdir src
/usr/bin/python ./download_svn.py
downloading version 2208 from http://www.amusecode.org/codes/mesa-r2208.tgz to mesa-r2208.tgz
Traceback (most recent call last):
  File "./download_svn.py", line 184, in <module>
    main(**options.__dict__)
  File "./download_svn.py", line 159, in main
    instance.start()
  File "./download_svn.py", line 142, in start
    filename, httpmessage, code = opener.retrieve(url, filename = os.path.join(self.src_directory(),filename))
  File "./download_svn.py", line 53, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 216, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 367, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 380, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 676, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 645, in http_error_302
    headers, data)
  File "/usr/lib/python2.7/urllib.py", line 672, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 216, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 446, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1054, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1271, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 831, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known
Makefile:64: recipe for target 'download' failed
make[2]: *** [download] Error 1
make[2]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
Makefile:45: recipe for target 'src/mesa/install' failed
make[1]: *** [src/mesa/install] Error 2
make[1]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
default ... failed
`

**Comment by rieder** [comment]
Ah, I see. The file "mesa-2208.zip" cannot be downloaded from the AMUSE server. This makes sense, since we recently changed our website.
I'll see if I can change the download urls to somewhere new.

**Comment by rieder** [comment]
I've updated the URL, MESA should now be available again. Please let us know if you have any further issues!

**Comment by alexolza** [comment]
Hi again @rieder , I'm not sure I should open a new issue on this or not:
I'm now using Amuse 12.0 but I'm still unable to get MESA. I've got different output though:
(running make mesa.code DOWNLOAD_CODES=1):

`/usr/bin/python setup.py -v build_code --inplace --clean=yes --code-name=mesa
running build_code
cleaning src/amuse/community/mesa
make -C src/amuse/community/mesa clean
make[1]: Entering directory '/home/alex/amuse/src/amuse/community/mesa'
rm -f -f *~ *.pyc *.mod *.o worker_code worker_code.f90 ./src/mesa/lib/libstar.a
rm -f -f mesa_worker mesa_worker_sockets worker_code-sockets.f90
make -C ./mesa_reqs clean
make[2]: Entering directory '/home/alex/amuse/src/amuse/community/mesa/mesa_reqs'
make[2]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa/mesa_reqs'
make[1]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
building libraries and community codes
build, for logging, see 'build.log'
[17:03:20] building mesa
make -C src/amuse/community/mesa all
make[1]: Entering directory '/home/alex/amuse/src/amuse/community/mesa'
/home/alex/amuse/build.py --type=f90 interface.py MESAInterface -o worker_code.f90
make -C . download
make[2]: Entering directory '/home/alex/amuse/src/amuse/community/mesa'
rm -f -Rf src
mkdir src
/usr/bin/python ./download_svn.py
downloading version 2208 from http://www.amusecode.org/codes/mesa-r2208.tgz to mesa-r2208.tgz
Traceback (most recent call last):
  File "./download_svn.py", line 184, in <module>
    main(**options.__dict__)
  File "./download_svn.py", line 159, in main
    instance.start()
  File "./download_svn.py", line 142, in start
    filename, httpmessage, code = opener.retrieve(url, filename = os.path.join(self.src_directory(),filename))
  File "./download_svn.py", line 53, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 216, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 367, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 380, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 676, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 645, in http_error_302
    headers, data)
  File "/usr/lib/python2.7/urllib.py", line 672, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 216, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 446, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1054, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1271, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 831, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known
Makefile:64: recipe for target 'download' failed
make[2]: *** [download] Error 1
make[2]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
Makefile:45: recipe for target 'src/mesa/install' failed
make[1]: *** [src/mesa/install] Error 2
make[1]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
[17:03:23] building mesa, failed, see 'build.log' for error log
Environment variables
================================================================================
AMUSE_DIR	/home/alex/amuse
BOOSTLIBS	
CC	gcc
CFLAGS	-g -O2 -fPIC
CUDART_LIBS	-lnocudart
CUDA_LIBDIRS	-L/NOCUDACONFIGURED/lib -LNOCUDACONFIGURED/lib64
CUDA_LIBS	-lnocuda
CUDA_SDK	/NOCUDACONFIGURED
CUDA_TK	/NOCUDACONFIGURED
CXX	g++
CXXFLAGS	-g -O2 -fPIC
F90	gfortran
FC	gfortran
FFLAGS	-g -O2 -fPIC
FFTW_FLAGS	
FFTW_LIBS	-lfftw3 -lfftw3_threads
FORTRAN	gfortran
GSL_FLAGS	-I/usr/include
GSL_LIBS	-L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm
JAR	
JAVA	
JAVAC	
MPICC	mpicc
MPICXX	mpicxx
MPIF90	mpif90
MUSE_PACKAGE_DIR	/home/alex/amuse
OPENMP_CFLAGS	-fopenmp
OPENMP_FCFLAGS	-fopenmp
PYTHON	/usr/bin/python
SAPPORO_LIBS	-L/home/alex/amuse/lib/sapporo_light -lsapporo
Community codes not built (because of errors):
================================================================================
 * mesa
================================================================================
0 out of 1 codes built, 0 out of 0 libraries built
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    scripts=[ "bin/amusifier" ],
  File "/home/alex/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/alex/amuse/support/setup_codes.py", line 1229, in run
    BuildCodes.run(self)
  File "/home/alex/amuse/support/setup_codes.py", line 1108, in run
    raise Exception("No succesful builds detected. Aborting.")
Exception: No succesful builds detected. Aborting.
Makefile:136: recipe for target 'mesa.code' failed
make: *** [mesa.code] Error 1
`
Thank you for your help!

**Comment by rieder** [comment]
It looks like the script is still trying to download from the old location. I updated this in the repository, can you check you did a `git pull`?

**Comment by alexolza** [comment]
I did, but I have a different problem now:

```
`alex@portatil-alex:~/amuse$ git pull https://github.com/amusecode/amuse.git
From https://github.com/amusecode/amuse
 * branch                HEAD       -> FETCH_HEAD
Already up to date.
alex@portatil-alex:~/amuse$ make mesa.code DOWNLOAD_CODES=1
python setup.py -v build_code --inplace --clean=yes --code-name=mesa
running build_code
cleaning src/amuse/community/mesa
make -C src/amuse/community/mesa clean
make[1]: Entering directory '/home/alex/amuse/src/amuse/community/mesa'
rm -f -f *~ *.pyc *.mod *.o worker_code worker_code.f90 ./src/mesa/lib/libstar.a
rm -f -f mesa_worker mesa_worker_sockets worker_code-sockets.f90
make -C ./mesa_reqs clean
make[2]: Entering directory '/home/alex/amuse/src/amuse/community/mesa/mesa_reqs'
make[2]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa/mesa_reqs'
make[1]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
building libraries and community codes
build, for logging, see 'build.log'
[10:03:30] building mesa
make -C src/amuse/community/mesa all
make[1]: Entering directory '/home/alex/amuse/src/amuse/community/mesa'
/home/alex/amuse/build.py --type=f90 interface.py MESAInterface -o worker_code.f90
make[1]: /home/alex/amuse/build.py: Command not found
Makefile:89: recipe for target 'worker_code.f90' failed
make[1]: *** [worker_code.f90] Error 127
make[1]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
[10:03:30] building mesa, failed, see 'build.log' for error log
Environment variables
================================================================================
AMUSE_DIR	/home/alex/amuse
BOOSTLIBS	
F90	gfortran
FC	gfortran
FORTRAN	gfortran
JAR	
JAVA	
JAVAC	
MUSE_PACKAGE_DIR	/home/alex/amuse
OPENMP_CFLAGS	
OPENMP_FCFLAGS	
PYTHON	/usr/bin/python
SAPPORO_LIBS	-L/home/alex/amuse/lib/sapporo_light -lsapporo
Community codes not built (because of errors):
================================================================================
 * mesa
================================================================================
0 out of 1 codes built, 0 out of 0 libraries built
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    scripts=[ "bin/amusifier" ],
  File "/home/alex/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/alex/amuse/support/setup_codes.py", line 1230, in run
    BuildCodes.run(self)
  File "/home/alex/amuse/support/setup_codes.py", line 1109, in run
    raise Exception("No succesful builds detected. Aborting.")
Exception: No succesful builds detected. Aborting.
Makefile:136: recipe for target 'mesa.code' failed
make: *** [mesa.code] Error 1
```
`

My error log looks like this:

`****************************************************************************************************
Building libraries and codes
****************************************************************************************************
****************************************************************************************************
Building code: mesa, target: all, in directory: src/amuse/community/mesa
****************************************************************************************************
make[1]: Entering directory '/home/alex/amuse/src/amuse/community/mesa'
/home/alex/amuse/build.py --type=f90 interface.py MESAInterface -o worker_code.f90
make[1]: /home/alex/amuse/build.py: Command not found
Makefile:89: recipe for target 'worker_code.f90' failed
make[1]: *** [worker_code.f90] Error 127
make[1]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
****************************************************************************************************
********************************************************************************
Building finished
********************************************************************************`

**Comment by rieder** [comment]
You’ll need to re-run configure as well.

**Comment by alexolza** [comment]
It said installation was successful now, but it still couldn't build (and I can't see the package under amuse/packages either):

```
`mesa installation was successful.

************************************************
************************************************
************************************************




make -s --no-print-directory -C ./mesa_reqs star FFLAGS="-g -O2 -fPIC"
gfortran -fno-range-check   -fbounds-check -g -g -O2 -fPIC  -g -O2 -fPIC -I./src/mesa/include -c -ffree-form -I./src/mesa/star/make -I./mesa_reqs -o interface.o interface.f
mpif90 -g -O2 -fPIC -g -O2 -fPIC   -I/home/alex/amuse/lib/forsockets worker_code.f90 interface.o mesa_reqs/run_star_support.o mesa_reqs/run_star_extras.o mesa_reqs/calibrate.o mesa_reqs/isochrone.o mesa_reqs/pgstar_stub.o mesa_reqs/create_zams.o mesa_reqs/sample_zams.o mesa_reqs/run_star.o -o mesa_worker -L./src/mesa/lib -lstar -ldiffusion -lionization -lmlt -latm -lkaro -lcolors -leos -lkap -ljina -lweak -lnet -lscreen -lrates -lneu -lchem -lnum -linterp_2d -linterp_1d -lutils -lalert -lconst -lmtx  -lmesalapack -lmesablas  -L/home/alex/amuse/lib/forsockets -lforsockets  
worker_code.f90:490:10:

       use FortranSocketsInterface
          1
Fatal Error: Can't open module file ‘fortransocketsinterface.mod’ for reading at (1): No such file or directory
compilation terminated.
Makefile:86: recipe for target 'mesa_worker' failed
make[1]: *** [mesa_worker] Error 1
make[1]: Leaving directory '/home/alex/amuse/src/amuse/community/mesa'
[10:55:54] building mesa, failed, see 'build.log' for error log
Environment variables
================================================================================
AMUSE_DIR	/home/alex/amuse
BOOSTLIBS	
CC	gcc
CFLAGS	-g -O2 -fPIC
CUDART_LIBS	-lnocudart
CUDA_LIBDIRS	-L/NOCUDACONFIGURED/lib -LNOCUDACONFIGURED/lib64
CUDA_LIBS	-lnocuda
CUDA_SDK	/NOCUDACONFIGURED
CUDA_TK	/NOCUDACONFIGURED
CXX	g++
CXXFLAGS	-g -O2 -fPIC
F90	gfortran
FC	gfortran
FFLAGS	-g -O2 -fPIC
FFTW_FLAGS	
FFTW_LIBS	-lfftw3 -lfftw3_threads
FORTRAN	gfortran
GSL_FLAGS	-I/usr/include
GSL_LIBS	-L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm
JAR	
JAVA	
JAVAC	
MPICC	mpicc
MPICXX	mpicxx
MPIF90	mpif90
MUSE_PACKAGE_DIR	/home/alex/amuse
OPENMP_CFLAGS	-fopenmp
OPENMP_FCFLAGS	-fopenmp
PYTHON	/usr/bin/python
SAPPORO_LIBS	-L/home/alex/amuse/lib/sapporo_light -lsapporo
Community codes not built (because of errors):
================================================================================
 * mesa
================================================================================
0 out of 1 codes built, 0 out of 0 libraries built
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    scripts=[ "bin/amusifier" ],
  File "/home/alex/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/alex/amuse/support/setup_codes.py", line 1230, in run
    BuildCodes.run(self)
  File "/home/alex/amuse/support/setup_codes.py", line 1109, in run
    raise Exception("No succesful builds detected. Aborting.")
Exception: No succesful builds detected. Aborting.
Makefile:136: recipe for target 'mesa.code' failed
make: *** [mesa.code] Error 1
` 
```

**Comment by ipelupessy** [comment]
it seems the libraries are not build yet; if you do:
```
make framework
```
they should be build

**Comment by alexolza** [comment]
Thank you very much, it looks like MESA is working fine now!
