### ISSUE TITLE
Convert AMUSE packages to pkgutil-style namespace packages

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#531]
I believe this style is most appropriate for AMUSE:
https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages
The "native" alternative is not suitable since we want to be able to use alternatives to pip.

The main change will be to __init__.py in the AMUSE root, which should change to only this line:
```python
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```
We'll have to figure out if this will cause any troubles.

I'm not sure yet how this method deals with multiple levels of subpackages (since e.g. community codes install under amuse.community), perhaps amuse.community.__init__ will also need to change.

**Comment by rieder** [comment]
I think the __init__.py in community, ext and perhaps elsewhere should also be just the line above.

**Comment by rieder** [comment]
This would mean we have to fix a lot of imports that currently use `from amuse import X` and `from amuse.community import Y`... That's probably a good thing though.

**Comment by ipelupessy** [comment]
I have played aound with this, I am not yet convinced that we we match the use case (it seems this is more about joining the namespace of packages in seperate directories)..the docs for this are not super clear..the ```__init__.py``` requirement seems very limiting...

**Comment by rieder** [comment]
I agree it's limiting, but I do think it's similar to what we're doing (and not unworkable).
Note that one of the subpackages installs a module in the package root, which is what amuse-framework also does.

**Comment by ipelupessy** [comment]
well..I don;t like the fact that apparently the inits can only contain one line - not only is that limiting, but I also do not understand why that should be the case...I can see that both packages should contain the exact same ```__init__.py``` in the shared directory..we should understand what happens if you do put something there...

**Comment by rieder** [comment]
I don't like that either. I'm not sure if just letting them be identical (probably with this specific top line) would also be OK, we should find out. The current situation seems to result in weird problems (like unintended consequences when you're removing one package, but possibly more).

**Comment by rieder** [comment]
From https://setuptools.readthedocs.io/en/latest/setuptools.html#namespace-packages:
`You must NOT include any other code and data in a namespace package’s __init__.py. Even though it may appear to work during development, or when projects are installed as .egg files, it will not work when the projects are installed using “system” packaging tools – in such cases the __init__.py files will not be installed, let alone executed.`

**Comment by rieder** [comment]
so I guess we should try to get rid of code that currently uses \_\_init\_\_.py...

**Comment by rieder** [comment]
I've done a little more investigating on this. I think the native 3.3+ method might be fine after all:
- we're Python3 only now
- we install via pip (either as individual packages, for which we should fix this issue, or in development mode, for which it doesn't matter)

**Comment by rieder** [comment]
this requires that "namespace" directories (directories in which subpackages are installed) don't have an `__init__.py`.
I think the relevant directories in AMUSE are
- community
- ext
So I am now attempting to get rid of the `__init__.py` files in these directories (branch patch-packaging).

**Comment by rieder** [comment]
(ext doesn't have an `__init__.py` to begin with)
