### ISSUE TITLE
stellar_type units is incomplete

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#549]
units.stellar_type seems to lack a description for stars at the bottom end of the mass spectrum - e.g. brown dwarfs / planets. The description internally in SeBa seems more complete. Perhaps they should be added?
Pro: more complete description of information in the stellar evolution code.
Con: this could be confusing since other codes may not distinguish between these types.

**Comment by ipelupessy** [comment]
yes, I think they can be added (there is no requirement that a particular stellar evolution code supports a given type)
