### ISSUE TITLE
Hardware requirements for stellar_wind.py

### ISSUE THREAD

**Issue by GFTwrt** [amusecode/amuse#566]
Hi,
I have a question about the hardware recommendations in combination with stellar_wind.py.
I'd like to do a simulation of our solar system generating the solar wind of our sun by stellar_wind.py, setting the planets not to planetesimal like common but simulating them more like a star at their real surface temperature. Maybe even as derived class from planetesimal including just the radius.
What hardware is needed for such a simulation? Is a Laptop ok? Is a GPU needed? What RAM would be needed?

Thank You for your answer
GFTwrt

**Comment by spzwart** [comment]
Dear GFTwrt,

A laptop will suffice for developing the script and mybe for a few production-quality calculations. But for more extensive runs (higher mass-resolution in the wind or a more extensive parameter seach) I would run on a workstation or up.
Simon

**Comment by GFTwrt** [comment]
Thank You for your answer!

Since I'm private researcher I'm very limited in budget. I need to buy some new hardware. My 5 year old Laptop is for sure not enough. So what is your interpretation of a workstation? 8 GB or 128 GB of RAM, quad-core, octa-core more cores? Nvidia-GeForce-900, GeForce GTX 1660 Ti, Titan RTX - I have no Idea for this type of simulation. At my job do we run Electromagnetic Simulation environment in FEM with 128 GB and Nvidia-Titan Xp 
GFTwrt

**Comment by rieder** [comment]
It's hard to answer that question without the specifics - I would recommend you develop the script and test at low-resolution on your laptop. Then determine how much higher resolution (i.e. how many more particles) you would need and extrapolate from there.
