### ISSUE TITLE
Documentation could not build

### ISSUE THREAD

**Issue by GFTwrt** [amusecode/amuse#590]
Hello,
got the error
> phinx-build -b latex -d build/doctrees -D latex_paper_size=a4  . build/latex
> Running Sphinx v1.8.5
> Extension error:
> Could not import extension matplotlib.sphinxext.only_directives (exception: No module named 'matplotlib.sphinxext.only_directives')

seams to be related with
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917754

Is this directive really necessary? how to skip it?

**Comment by ipelupessy** [comment]
the documentation build for the pds/latex doc needs to be fixed (is has been disabled we are only building the html on https://amuse.readthedocs.io ), but I am not sure we saw this exact problem..

**Comment by ipelupessy** [comment]
online docs now building. closing
