### ISSUE TITLE
CUDA calls outdated

### ISSUE THREAD

**Issue by GFTwrt** [amusecode/amuse#592]
Hello,

I'm using UBUNTU 19.10 (eoan) which uses CUDA10 https://packages.ubuntu.com/source/eoan/nvidia-cuda-toolkit. (GeForce RTX 2070, on Ryzen 7 3800)
I can compile newer codes like "fastkick" with CUDA Support. But older codes like "bonsai" needs to be ported to higher "gpu-architecture". Example sapporo_2 sets the flag "-arch=sm_20" which is outdated since CUDA 9 and already set to deprecated in Version 8. Please have look to the build.log attached.

I also tried cython and cython3. The codes where not compiled. 

Community codes not built (because of errors):
================================================================================
 * bonsai
 * bonsai2
 * distributed
 * etics
 * pikachu
 * simplex
Optional builds failed, need special libraries:
 * aarsethzare - cython
 * asterisk - java
 * athena - cython
 * bhtree - cython
 * fi - gl, periodic_gl
 * gadget2 - cython_periodic, cython_normal, cython_periodic_nogravity, cython_nogravity
 * hacs64 - gpu
 * hermite - cython
 * higpus - gpu
 * huayno - cython_cl, cl, cl, cl, cl, cl, cl.so, cl.so, cl.so, cl.so, cl.so, cython, cython_mp, mp.so, mp.so, mp.so
 * kepler - cython
 * mi6 - gpu
 * mosse - cython
 * phigrape - gl, grape, gl_gpu
 * seba - cython
 * smalln - cython
 * sse - cython
Optional builds failed, need additional python packages:
 * tupan

https://stackoverflow.com/questions/28932864/cuda-compute-capability-requirements 
CUDA VERSION   Min CC   Deprecated CC  Default CC  Max CC
5.5 (and prior) 1.0       N/A             1.0
6.0             1.0       1.0             1.0
6.5             1.1       1.x             2.0
7.x             2.0       N/A             2.0
8.0             2.0       2.x             2.0      6.2
9.x             3.0       N/A             3.0      7.0
10.x            3.0       N/A             3.0      7.5

[build.log](https://github.com/amusecode/amuse/files/4220613/build.log)

Can you help?

**Comment by ipelupessy** [comment]
@jbedorf can you have a look at the saporro and bonsai??

**Comment by GFTwrt** [comment]
Hello, please keep in mind: not just saporro and bonsai have this problem. Other CUDA codes are in the same pit. (Have a look to the attached build.log)

**Comment by ipelupessy** [comment]
Closing. reopen if necessary. CUDA stuff will need some maintenance; but atm I cannot test this easily..
