### ISSUE TITLE
amusifier not found

### ISSUE THREAD

**Issue by GFTwrt** [amusecode/amuse#594]
Hello,

today I did git pull. afterwards ./configure and make. Before the pull i got 47 codes build. now only  
```
Community codes built
================================================================================
* asterisk
* gadget2
* galactics
* higpus
* mameclot
================================================================================
5 out of 52 codes built, 5 out of 6 libraries built
```
The build log reports 
make[1]: amusifier: Befehl nicht gefunden  (command not found) for most codes

**Comment by spzwart** [comment]
did you set the varous environment variables to indecate there your amuse
distro lives?

Simon

**Comment by ipelupessy** [comment]
yes, if you don't do a pip install, you need to set the PYTHONPATH (that was already the case) and PATH (this was not mandatory previously), eg:
```
export PYTHONPATH=/home/user/amuse/src:${PYTHONPATH}
export PATH=/home/user/amuse/bin:${PATH}
```
it was done to take care of bugs when building inside vs in the root dir.
note you can also install an amuse development package using virtualenv (then the above environment stuff is taken care of):
```
virtualenv env
source env/bin/activate
git clone https://github.com/amusecode/amuse
cd amuse
pip install -e .
python setup.py develop_build 
```

**Comment by GFTwrt** [comment]
Hello,
I follow:
1. https://amuse.readthedocs.io/en/latest/install/index.html
2.https://amuse.readthedocs.io/en/latest/install/install-prerequisites-ubuntu.html
3. https://amuse.readthedocs.io/en/latest/install/howto-install-AMUSE.html#configuring-the-code

There was no need to set any environment variable before your change. The ./configure was setting up correctly anything. I use this way because of the "easy" install via pip fails https://github.com/amusecode/amuse/issues/592
From my point of fiew using autoconfiguration should actually make it unnecessary to set variables before configuring.

**Comment by ipelupessy** [comment]
I am updating the install instructions
