### ISSUE TITLE
Sign of Energy

### ISSUE THREAD

**Issue by GFTwrt** [amusecode/amuse#595]
Hello,
I've checked Listing 2.1 (Book: The art of Amuse) with brutus by streaming the requests of potential and kinetic energy by usage of C++ function std::string out = ektot.toString(); to a file. I was surprised by the sign of the potential energy which was negative. By checking the python side of the interface I found that code.potential_energy delivers a negative number too. (Other Codes delivers the same signing.)

So out of my point of view the python lines (Listing 2.1):
    Ekin = gravity.kinetic_energy 
    Epot = gravity.potential_energy

    Etot = Ekin + Epot
do not deliver the total energy but the Lagrangian.

**Comment by ipelupessy** [comment]
For gravitational dynamics the zero point of the potential is taken at infinity; the potential well goes to -infinity hence the potential energy is negative (as is the total energy for a bound system)...

**Comment by ipelupessy** [comment]
issue has been clarified, closing
