### ISSUE TITLE
Qparameter verbosity

### ISSUE THREAD

**Issue by iambernie** [amusecode/amuse#6]
Can we remove the print statements in the `Qparameter` method or at least give the user the option to silence them?

```
>>> from amuse.ic.plummer import new_plummer_model
>>> model = new_plummer_model(1000)
>>> model.Qparameter()
making graph
constructing MST
Q: 1.53074998216
1.5307499821583916
>>> 
```

**Comment by spzwart** [comment]
Dear Bernie,

We will look into this on Tuesday.

Cheers,
Simon

----- Reply message -----
