### ISSUE TITLE
Community code stuck when initiating CodeInterface

### ISSUE THREAD

**Issue by JuliaWasala** [amusecode/amuse#602]
Hi, I've been writing an interface for my own nbody gpu code, the interface compiles but once I try to run a testscript, nothing happens. I've determined that the code runs up to the initialization of CodeInterface in the __init__ method of my own class interface in interface.py. 
I have not modified core.py in any way, what could cause this issue? Other gpu nbody codes such as ph4 (in gpu mode) work fine with the test script.

**Comment by rieder** [comment]
Hi Julia,

Without looking at the interface, this is very hard to answer. 
Do you have this available somewhere?

Steven

**Comment by BattleBunny** [comment]
Hi Steven,

I’ve attached the .py and .cc interfaces.

Van: Steven Rieder <notifications@github.com>
Beantwoorden - Aan: amusecode/amuse <reply@reply.github.com>
Datum: dinsdag 17 maart 2020 om 20:46
Aan: amusecode/amuse <amuse@noreply.github.com>
CC: Julia Wasala <juliawasala@outlook.com>, Author <author@noreply.github.com>
Onderwerp: Re: [amusecode/amuse] Community code stuck when initiating CodeInterface (#602)

Hi Julia,

Without looking at the interface, this is very hard to answer.
Do you have this available somewhere?

Steven

**Comment by rieder** [comment]
I'm afraid that attachments don't come through on github. You could upload it to this thread though.

**Comment by BattleBunny** [comment]
[interface.zip](https://github.com/amusecode/amuse/files/4345539/interface.zip)

**Comment by rieder** [comment]
Thank you. Could you also attach the test script, and specify which aspect currently fails?
From a first glance (all I have time for at this moment), your interface is very basic at the moment. I would advice using an interface such as the one for Hermite as a guide to a more complete gravitational interface.

**Comment by BattleBunny** [comment]
[testscript.py.zip](https://github.com/amusecode/amuse/files/4345609/testscript.py.zip)
