### ISSUE TITLE
PyTest Failure on Depreciated Units Function Call

### ISSUE THREAD

**Issue by JPGlaser** [amusecode/amuse#605]
**Describe the bug**
When running PyTest on the latest pip version of amuse, I get the following warning:
```
anaconda3/lib/python3.7/site-packages/amuse/units/quantities.py:1407: DeprecationWarning: PyArray_SetNumericOps is deprecated. Use PyUFunc_ReplaceLoopBySignature to replace ufunc inner loop functions instead.
    true_divide = numpy_true_div_operator
```

**To Reproduce**
Run PyTest on a code which references amuse.units.

**Comment by JPGlaser** [comment]
Any updates on this front?

~ Joe

**Comment by rieder** [comment]
Hi Joe,
I don't get this error when I test it now, could you check if it has been fixed for you as well?

**Comment by rieder** [comment]
I think it's been fixed
