### ISSUE TITLE
Gadget2 endrun with error not picked up by amuse-framework==13.1.0 when using OpenMPI 3.3 on Debian 10 --> AMUSE script continues to run full power

### ISSUE THREAD

**Issue by tlrh314** [amusecode/amuse#608]
**Describe the bug**
GADGET-2 endrun calls with an error are not picked up by the AMUSE framework (13.1.0) when using openmpi (3.3) on Debian 10. This causes the worker instances to continue 'running', i.e. using resources but not doing any calculations.

**To Reproduce**
```python
def kill_gadget(number_of_workers):
    from amuse.units import units, nbody_system
    from amuse.ic.plummer import new_plummer_sphere

    from amuse.community.gadget2.interface import Gadget2
    gravity = Gadget2(
        number_of_workers=number_of_workers,
        redirection="none"
    )
    gravity.parameters.gadget_output_directory = "folder/does/not/exist"
    gravity.commit_parameters()

if __name__ == "__main__":
    from amuse.support.exceptions import CodeException
    from amuse.support.exceptions import AmuseException

    try:
        kill_gadget(1)
    except CodeException as e:
        print("Code throws error")  # no bug b/c CodeException is raised as expected
    try:
        kill_gadget(4)
    except CodeException as e:
        print("Worker dies without communicating this back to AMUSE")
        raise  # yes bug b/c CodeException is not raised and workers keep using resources
```

**Expected behavior**
The expected behaviour of the framework is to notice the underlying worker(s) died and raise an instance of `amuse.support.exceptions.CodeException` as a result.

**Logs**
```txt

This is Gadget, version `2.0'.

Running on 1 processors.

Allocated 25 MByte communication buffer per processor.

Communication buffer has room for 284938 particles in gravity computation
Communication buffer has room for 109226 particles in density computation
Communication buffer has room for 86231 particles in hydro computation
Communication buffer has room for 79920 particles in domain decomposition


Hubble (internal units) = 0.1
G (internal units) = 43007.1
UnitMass_in_g = 1.989e+43 
UnitTime_in_s = 3.08568e+16 
UnitVelocity_in_cm_per_s = 100000 
UnitDensity_in_cgs = 6.76991e-22 
UnitEnergy_in_cgs = 1.989e+53 

error in opening file 'folder/does/not/exist/cpu.txt'
task 0: endrun called with an error level of 1


Code throws error

This is Gadget, version `2.0'.

Running on 4 processors.

Allocated 25 MByte communication buffer per processor.

Communication buffer has room for 284938 particles in gravity computation
Communication buffer has room for 109226 particles in density computation
Communication buffer has room for 86231 particles in hydro computation
Communication buffer has room for 79920 particles in domain decomposition


Hubble (internal units) = 0.1
G (internal units) = 43007.1
UnitMass_in_g = 1.989e+43 
UnitTime_in_s = 3.08568e+16 
UnitVelocity_in_cm_per_s = 100000 
UnitDensity_in_cgs = 6.76991e-22 
UnitEnergy_in_cgs = 1.989e+53 

error in opening file 'folder/does/not/exist/cpu.txt'
task 0: endrun called with an error level of 1

**Nothing happens here, but top/htop shows 400% CPU usage** 

Killed <-- manually
```

**Environment (please complete the following information):**
 - OS and version: Debian GNU/Linux 10 (buster), Linux 4.9.0-6-amd64 `#1` SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
 - Compiler: gcc (Debian 8.3.0-6) 8.3.0
- Python 3.7.3
- AMUSE is installed via pip in a virtualenv, but the issue is also present when building from source
- amuse==13.1.0
- amuse-framework==13.1.0
- amuse-gadget2==13.1.0
- mpi4py==3.0.3
- numpy==1.18.2
- scipy==1.4.1
- virtualenv 15.1.0

The output of `mpicxx -v` is as follows
```txt
Using built-in specs.
COLLECT_GCC=/usr/bin/g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)
```

**Additional context**
- The step to reproduce is just an easy way to get GAGET-2 to endrun with an error, but actual errors encountered during production runs are also not picked up by the AMUSE framework.

- The issue can be alleviated with
```python
    gravity = Gadget2(
        number_of_workers=number_of_workers,
        channel_type="sockets",
        redirection="none"
    )

```
which results in 
```txt
amuse.support.exceptions.CodeException: lost connection to code

During handling of the above exception, another exception occurred:

path/to/venv/lib/python3.7/site-packages/amuse/rfi/core.py", line 123, in __call__
    raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}'".format(self.specification.name, type(self.interface).__name__, ex))
amuse.support.exceptions.CodeException: Exception when calling function 'commit_parameters', of code 'Gadget2Interface', exception was 'lost connection to code'
Exception ignored in: <function CodeInterface.__del__ at 0x7f3ba7da39d8>
```

**Comment by ipelupessy** [comment]
will try to look into this..

**Comment by ipelupessy** [comment]
ideally there should be an exception, however its a bit involved due to the way the error is generated in gadget..however I can easily add an MPI_abort - this will shutdown everything though...

**Comment by ipelupessy** [comment]
do you have an indication about which kind of errors trigger this in a production run?

**Comment by tlrh314** [comment]
Awesome, thanks for looking into the issue! Did you confirm that this is indeed a bug?

Do I understand correctly that the proposed solution could be to implement an MPI_abort in the endrun call that GADGET-2 makes, and that should trigger the AMUSE framework to pick up that the underlying worker died? 

One example of a production run died after printing `begin Peano-Hilbert order` with an error along the lines of `task 3 maximum number 1500 of tree-nodes reached for particle 1782, endrun called with an error level of -1`. I changed my scripts quite substantially by now so I do not have an isolated minimum example to reproduce the issue, but I can try to run into the issue again. However, the minimum working example that I provided runs much faster than waiting for the Nbody model to run into the issue haha.

**Comment by ipelupessy** [comment]
yea, its a bug in so far as the behaviour should be indeed be that errors in the code should lead to an exception in the framework..

the proposed solution (more of a bandaid) with the MPI_abort is not so nice (since it tends to bring down the whole MPI run (including the framework side), its quite a hard stop...at least this prevents hangs...

I don't need another example (the error you mention message you mention is enough!)..

I will think a bit if I can adapt endrun to exit more gracefully...

**Comment by ipelupessy** [comment]
ok, I have pushed the "fix"... now an error in gadget stops everything for number_of_workers>1, ideally the behaviour should be same as for number_of_workers=1..but I am not sure this is possible without rewriting large parts of gadget...for now this is acceptable (what you think @rieder ?)

**Comment by ipelupessy** [comment]
permanently provisionally fixed, closing.
