### ISSUE TITLE
huayno worker on GPU, amuse v12,13

### ISSUE THREAD

**Issue by computerworkers** [amusecode/amuse#610]
Having all amuse requirements in place, 

` ./configure --enable-cuda`

and `making' from source huayno, fails to build huayno_worker_cl.

From what I can see, huyano's Makefile has hard-coded parameters. Is there any reason why?
See for instance:
`OPENCL = /home/inti/libraries/cuda`
`STDCL = /home/inti/libraries/coprthr`

I would expect these parameters to be taken from the current environment.
Also the target 'all' is hard-coded to

`all:	huayno_worker`

 meaning that `huayno_worker_cl` will never be built without human intervention. 

Finally, would having the CUDA-provided CL library instead of the OpenCL library make any difference to the compilation of ` huayno_worker_cl`? 
When the logs show

`Optional builds failed, need special libraries:`
` huayno - cython_cl, cl.so, mp.so`

to which libraries it is referring?

PS: the problems described are present in both v12 and v13.

Many thanks in advance.

**Comment by ipelupessy** [comment]
yes, the opencl enabled workers of huayno are a bit experimental, and need manual configuration. Cython workers will also not work (it also needs some manual configuration but it is deprecated and will be removed). The all: target will restrict the build targets when doing a manual build from the directory, the framework builds (```make huayno.code``` from the root, package builds) however pick up the extra targets and will try to build the other workers...

the cl workers need an opencl library (CUDA or something else) and the coprthr library (https://github.com/browndeer/coprthr)...

**Comment by ipelupessy** [comment]
I looked at it a bit more carefully, and it should use any configured opencl correctly and if the coprthr library is also installed in the same directories it will also work..so I think the opencl detection in the configure may be broken...

**Comment by ipelupessy** [comment]
I can confirm that you don't need to touch the Makefile if OpenCL and the coprthr libs are installed..to see if the configure has picked up the OpenCL libs:
```
amusifier --get-amuse-configmk
``` 
and check the values for FOUND_CL, CL_LIBS and CL_FLAGS 

coprthr can be a bit tricky to install though...

**Comment by computerworkers** [comment]
Thanks for your messages. I think there is a problem with the configure script. It seems to check for both CL/cl.h etc and OpenCL/cl.h and if it does not find the latter it concludes that there is no CL installed.
This is the relevant part of the config run:
```
checking CL/cl.h usability... yes
checking CL/cl.h presence... yes
checking for CL/cl.h... yes
checking OpenCL/cl.h usability... no
checking OpenCL/cl.h presence... no
checking for OpenCL/cl.h... no

```
and here is the relative config log

```
configure:6512: checking CL/cl.h usability
configure:6512: gcc -c -g -O2   conftest.c >&5
configure:6512: $? = 0
configure:6512: result: yes
configure:6512: checking CL/cl.h presence
configure:6512: gcc -E   conftest.c
configure:6512: $? = 0
configure:6512: result: yes
configure:6512: checking for CL/cl.h
configure:6512: result: yes
configure:6512: checking OpenCL/cl.h usability
configure:6512: gcc -c -g -O2   conftest.c >&5
conftest.c:57:23: fatal error: OpenCL/cl.h: No such file or directory
...
configure:6512: checking OpenCL/cl.h presence
configure:6512: gcc -E   conftest.c
conftest.c:24:23: fatal error: OpenCL/cl.h: No such file or directory

```

and therefore

```
CL_CFLAGS=''
CL_LIBS=''
FOUND_CL='no'

DEFS='-DPACKAGE_NAME=\"amuse\" -DPACKAGE_TARNAME=\"amuse\" -DPACKAGE_VERSION=\"12.0.0\" -DPACKAGE_STRING=\"amuse\ 12.0.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAG
E_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPE
S_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_MPI=1 -DHAVE_MPI=1 -DHAVE_MPI=1 -DHAVE_OPENMP=1 -DHAVE_CL_CL_H=1'
```

libstdcl (coprthr) is installed correctly and sourced okay.

**Comment by ipelupessy** [comment]
I think it is fine if it finds either _ -lopencl:
```
...
checking CL/cl.h usability... yes
checking CL/cl.h presence... yes
checking for CL/cl.h... yes
checking OpenCL/cl.h usability... no
checking OpenCL/cl.h presence... no
checking for OpenCL/cl.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking for OpenCL library... -lOpenCL   <- should be found
...
```
but it can be a bit fiddly about the lib....

**Comment by computerworkers** [comment]
```
checking CL/cl.h usability... yes
checking CL/cl.h presence... yes
checking for CL/cl.h... yes
checking OpenCL/cl.h usability... no
checking OpenCL/cl.h presence... no
checking for OpenCL/cl.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking for OpenCL library... no
```

**Comment by ipelupessy** [comment]
so you should check whether the libOpenCL is correctly installed .. i had the same problem 
described here:
https://flanaras.wordpress.com/2017/01/31/setup-opencl-on-opensuse-intel-integrated-gpu/
instead of linking the libOpenCL.so.1 , I searched for a package that provided libOpenCL.so ...but I am scratching my head a bit on this...

**Comment by computerworkers** [comment]
Puzzling..CL is installed correctly:

```
nvcc -lOpenCL test.cpp

./a.out

1 OpenCL Platforms found

 CL_PLATFORM_NAME: 	NVIDIA CUDA
 CL_PLATFORM_VERSION: 	OpenCL 1.2 CUDA 10.1.120
OpenCL Device Info:

 4 devices found supporting OpenCL on: NVIDIA CUDA
...
```

**Comment by computerworkers** [comment]
mmm..on Monday I will take a good look at the m4 file relative to the CL tests..

**Comment by computerworkers** [comment]
I checked the m4 file and it is kosher. Because our CL library comes with CUDA, by launching configure with --with-opencl=CUDA_HOME lets configure find the lib. I am now waiting to see how the compilation ends and what errors/warnings I get on the compiled workers. If huayno_cl compiles well, I will notify you so you can close this ticket.
I assume the huayno_cython worker because experimental (as you mentioned), will fail to build.
Cheers,
l.

**Comment by ipelupessy** [comment]
I think the kernels are compiled at run time, so ideally you would want to test a run with the opencl worker..for me this not working atm...

**Comment by computerworkers** [comment]
Just tested a run, but huayno_mp is used instead of huayno_cl. Is there a particular way to instruct huayno to use CL?

**Comment by ipelupessy** [comment]
```
h=Huayno(mode="opencl")
```

**Comment by computerworkers** [comment]
Well, it does work. It launches huayno_cl successfully, but it terminates after a while with
`
mpi4py.MPI.Exception: MPI_ERR_SPAWN: could not spawn processes
`
even though I set `export OMPI_MCA_rmaps_base_oversubscribe=yes`

The same thing does not happen when requesting `mode=openmp`. Ideas?

**Comment by ipelupessy** [comment]
hmm, can you see if the cl worker does any work (and maybe start with debugger="gdb" option)?

**Comment by computerworkers** [comment]
It seems that huayno_worker_cl gets executed by the allocated GPUs and then stops abruptly with `mpi4py.MPI.Exception: MPI_ERR_SPAWN: could not spawn processes`.  The python code is launched with mpiexec/mpirun. Running the code by just launching python does not produce any results.

**Comment by ipelupessy** [comment]
what happens if you instantiate the worker with channel_type="sockets" ?

**Comment by computerworkers** [comment]
It works fine, but no GPUs

**Comment by computerworkers** [comment]
I also tested that mpi4py and OpenMPI are in sync.

**Comment by ipelupessy** [comment]
the opencl part of huayno has been reworked to not use coprthr, so the original issue is no longer relevant. any remaining issues should be reraised in a new issue, closing.
