### ISSUE TITLE
Problem running Amuse in GPU cluster

### ISSUE THREAD

**Issue by blackhole-canada** [amusecode/amuse#613]
Hello all, 

I am trying to run Amuse in Graham Gpu cluster in Canada. I have successfully installed amuse from source file which gave me the ph4_gpu. When I am running it using CPU it is running perfectly fine. But when I am running it in GPU mode using the following slurm job submission I am getting the error: 

#!/bin/bash
#SBATCH --gres=gpu:v100:1
#SBATCH --cpus-per-task=3
#SBATCH --mem=12G

/home/adas45/amuse/amuse.sh /home/adas45/code/test.py

Error: 

Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[62881,1],0]
  Exit code:    127
--------------------------------------------------------------------------
dt_snap = 0.004000000000000000 [Myr] dt = 0.0002000000000000000 [Myr]
Traceback (most recent call last):
  File "/home/adas45/amuse/src/amuse/rfi/channel.py", line 1750, in accept_worker_connection
    return server_socket.accept()
  File "/home/adas45/amuse/prerequisites/lib/python3.7/socket.py", line 212, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adas45/code/3_finite_constant_constant.py", line 785, in <module>
    grav = ph4(converter, mode="gpu")
  File "/home/adas45/amuse/src/amuse/community/ph4/interface.py", line 471, in __init__
    legacy_interface = ph4Interface(**keyword_arguments)
  File "/home/adas45/amuse/src/amuse/community/ph4/interface.py", line 34, in __init__
    **options
  File "/home/adas45/amuse/src/amuse/rfi/core.py", line 752, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)
  File "/home/adas45/amuse/src/amuse/rfi/core.py", line 780, in _start
    self.channel.start()
  File "/home/adas45/amuse/src/amuse/rfi/channel.py", line 1826, in start
    self.socket, address = self.accept_worker_connection(server_socket, self.process)
  File "/home/adas45/amuse/src/amuse/rfi/channel.py", line 1754, in accept_worker_connection
    raise exceptions.CodeException('could not connect to worker, worker process terminated')
amuse.support.exceptions.CodeException: could not connect to worker, worker process terminated

**Comment by spzwart** [comment]
Are you sure it is a gpu problem.
AMUSE does not work very well with slurm, but if you declare the following
export OMPI_MCA_rmaps_base_oversubscribe=yes
export OMPI_MCA_mpi_warn_on_fork=0
slurm is less objecting against amuse's way to use spawn.

Simon

**Comment by JPGlaser** [comment]
When you built from source, what does your config file say it is using for the CUDA home directory?

I use to run into similar problems a few years back, which stemmed from not having it reference a CUDA that wasn't built off the same version of OpenMPI as AMUSE was referencing.

~ Joe

**Comment by blackhole-canada** [comment]
> When you built from source, what does your config file say it is using for the CUDA home directory?
> 
> I use to run into similar problems a few years back, which stemmed from not having it reference a CUDA that wasn't built off the same version of OpenMPI as AMUSE was referencing.
> 
> ~ Joe

Hi Joe, 

Thank you for the reply. I am not sure where to look for the Cuda directory in the config file. Should I use --enable-mpi --enable-openmp while configuring Amuse? What is the proper way of configuring it. All I did was ./configure --enable-cuda. Also do I need to install Cuda separately in the Amuse prerequisites? 

I tried to switch to mpich2 and I am facing a new problem now. It is creating a deadlock while submitting the job via slurm showing "step creation temporarily disabled, retrying". Even salloc is showing the same problem.

**Comment by JPGlaser** [comment]
Sorry for the delay getting back to you; I was making sure our instructions still work for compiling AMUSE 13.1.

We use the following command to build on our local GPU cluster:
```
./configure --enable-cuda --with-cuda-libdir=$cudalibdir --enable-sapporo2
```
where *$cudalibdir* is set as:
```
export cudalib=`find $PATH_TO_CUDA_DRIVERS -name libcuda.so | grep lib64`
export cudalibdir=${cudalib%/*}
```

Hope this helps!

~ Joe G.
