### ISSUE TITLE
unit_converter in Lagrangeradii

### ISSUE THREAD

**Issue by blackhole-canada** [amusecode/amuse#614]
I am trying to compute the Lagrangeradii of a cluster using the built in particle attributes function. But my particles are in SI units. I am not sure what arguement to use for "unit_converter" in the 

LagrangianRadii(stars, unit_converter=None, mf=[0.01,0.02,0.05,0.1,0.2,0.5,0.75,0.9,1], cm=None, number_of_neighbours=7, reuse_hop=False, hop=HopContainer()):

Should I use something like a si_to_generic?

**Comment by rieder** [comment]
You could use something like this for the converter:
```
converter = nbody_system.nbody_to_si(stars.mass.sum(), 1 | units.parsec)
```

**Comment by MJCWilhelm** [comment]
The unit converter is used by the Hop module, which is used to compute the 'density centre' (sort of a center of mass?). This module uses dimensionless units internally, so you need a unit converter if your particles units are SI, as you would with an N-body code. 

The quantities in the converter shouldn't matter conceptually, but there are some numerical effects (in my tests, the errors were of order ~10^-10 to ~10^-7). It is generally good practice to set them to the characteristic scales of the problem (like the total mass).
