### ISSUE TITLE
Building AMUSE touches fi/src/globals.h

### ISSUE THREAD

**Issue by stevemcmillan** [amusecode/amuse#616]
I cloned and built a clean copy of AMUSE.  Now git status says I have a modified version of fi/src/globals.h.  I built but did not use fi, and am concerned that a future push may overwrite something in that module.

**To Reproduce**
make all
git status | grep modified 

**Expected behavior**
I expected fi/src/globals.h not to appear on the list as modified.

**Logs**
Unnecessary.

**Environment (please complete the following information):**
 - macOS Catalina 10.15.4
 - Compiler: gcc9

**Additional context**
N/A

**Comment by ipelupessy** [comment]
this is also annoying me - the globals is patched during the build, but I think its something with windows vs unix newlines...

**Comment by ipelupessy** [comment]
fixed
