### ISSUE TITLE
memory leak when writing files

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#619]
In the minimum example script below (which just writes a backup of a particle set), python memory usage seems to increase each time it is called. I don't see why though... How do I prevent this?
```python
from amuse.io import write_set_to_file
from amuse.ic.gasplummer import new_plummer_gas_model
from amuse.units import nbody_system

def save_copy(p, t):
    write_set_to_file(p.savepoint(t), "test.hdf5", "amuse", append_to_file=False, version="2.0", return_working_copy=False, close_file=True,)
    return

p = new_plummer_gas_model(1000000)
for i in range(50):
    save_copy(p, i | nbody_system.time)
```

**Comment by rieder** [comment]
nb, the `version="2.0", return_working_copy=False, close_file=True` flags don't seem to affect this at all.

**Comment by rieder** [comment]
the 'savepoint' option seems to be the culprit... not sure why?

**Comment by ipelupessy** [comment]
savepoint saves state of the particle set in memory, so its supposed to increase mem usage?

**Comment by ipelupessy** [comment]
the bigger question is why you don't see the increase for version 2.0?

**Comment by ipelupessy** [comment]
just to clarify: savepoint pushes the current state of the particle set on the stack (labeling with the timestap)..the history can be iterated over with p.iter_history or retrieved as p.history

**Comment by ipelupessy** [comment]
savepoint returns the saved state

**Comment by rieder** [comment]
So what would be the right method of saving a particleset with a timestamp? 
The method I tried here comes from the AMUSE book (p. 2-30), but clearly leads to a memory leak and should not be used...

**Comment by ipelupessy** [comment]
```p.collection_attributes.timestamp=...``` will work

**Comment by ipelupessy** [comment]
we could add something to write_set_to_file:
```
write_set_to_file(p. filename. fileformat, timestamp= ..)
```
or
```
write_set_to_file(p. filename. fileformat, attributes=dict(timestamp= .., ..) )
```

**Comment by rieder** [comment]
Ok. I'm fine with this in principle, though it is confusing and I think it requires better documentation.

@spzwart and @stevemcmillan: maybe there should be an erratum for the AMUSE book regarding this issue? This method of writing a savefile is probably not one we want to advertise as is currently done in the book (e.g. p 2-30 and others)...

**Comment by JPGlaser** [comment]
Has a solution for this memory leak been found? I think I am starting to run into this error in some of my larger runs causing the OS to kill the job.

~ Joe G.

**Comment by stevemcmillan** [comment]
Inti posted a fix for this on the amusecode git repo on April 24.

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by ipelupessy** [comment]
also, the p.savepoint(t) should not be used, unless that is what you really want: it pushes the current particle set state down the (history) stack (so that was the cause of the increasing memory usage)

**Comment by ipelupessy** [comment]
fixed
