### ISSUE TITLE
units.quantity should not override numpy operations

### ISSUE THREAD

**Issue by mhvk** [amusecode/amuse#622]
Right now, `units.quantity` works in part by overriding the numpy operations using `np.set_numeric_ops` - this quite bad practice since it affects any use of numpy outside of amuse in the same session (if nothing else, slowing it down). It is also slated to be removed from numpy (it raises `DeprecationWarning`, as I found while working on https://github.com/astropy/astropy/pull/10196 - the test case kept on giving that warning, which in astropy tests is turned into an error).

I would strongly suggest moving to the standard method for this, which is to have an `__array_ufunc__` method - see https://numpy.org/doc/stable/reference/arrays.classes.html?highlight=__array_ufunc__#numpy.class.__array_ufunc__ 

If you need inspiration, see astropy's `Quantity` for a possible implementation. 

p.s. From a quick look it might be worth considering just moving over to using astropy's implementation, at least under the hood, as we are quite a bit more complete, being able to deal not just with all ufuncs, including `np.sin`, etc., but also most numpy functions such as `np.concatenate` (using the very recent `__array_function__` method).

**Comment by rieder** [comment]
Thanks @mhvk! I agree I would very much prefer to use standard methods wherever possible - I think this is probably one of those things that just went unnoticed.
Regarding using astropy's implementation of quantities "under the hood" or overall: I would love for that to work and I think it's entirely possible if we put our time towards this. I would be willing to do so at some point if we can find time to sit together (virtually) with other AMUSErs and Astropy people.

However, we would also need to consider how this would affect AMUSE-related projects like OMUSE and HYMUSE, for which we certainly wouldn't want to introduce an Astropy dependency...

**Comment by mhvk** [comment]
@rieder - I've been wondering about splitting off the units/quantity module from astropy (ideally to something like numpy or scipy), but it is obviously quite a bit of an effort (and some of the numpy/scipy developers feel so strongly units should be part of the dtype, that I suspect it would take more than a little convincing).

**Comment by rieder** [comment]
I would love for units/quantities to be a numpy/scipy/independent feature rather than an astropy one...

**Comment by ipelupessy** [comment]
yea, I think the set_numeric_ops stuff can be removed..I think at the time we decided against overriding numpy operators; now it can be done with ```__array_ufunc__```

**Comment by ipelupessy** [comment]
fixed
