### ISSUE TITLE
How to control the key IDs generated by AMUSE

### ISSUE THREAD

**Issue by stevemcmillan** [amusecode/amuse#623]
I am cautiously rewriting the multiples module to use data structures like encounters and streamline the design, but to retain the physics I think works, and I want to be able to check frequently that I haven't materially changed the module's operation by writing a verbose test script and comparing the output with the original multiples code.  Eventually this will fail as features are added, but while I am simply refactoring I need to know I haven't changed anything.  

The verbose output involves printing out particle sets of multiple systems.  Unfortunately, it appears that the keys used for particles are randomly generated each time the (unchanged) script runs.  Does anyone know how to force AMUSE to generate the same key names each time around?

**Comment by rieder** [comment]
You could pre-generate a set of keys (a list of numbers) and pass it to a particle set with the keyword 'keys=':
```python
p = Particles(5)
keys = p.key
q = Particles(keys=keys)
```

**Comment by rieder** [comment]
Perhaps more useful in your case would be to pass a simpler key generator:
```python
from amuse.datamodel import Particles
from amuse.datamodel.base import BasicUniqueKeyGenerator
n = 10
p = Particles(n, keys_generator=BasicUniqueKeyGenerator())
q = Particles(n, keys_generator=BasicUniqueKeyGenerator(
    lowest_unique_key=p.key.min())
)
```
But please note that this is risky when creating/deleting particles as they might get the same key if you don't pass the correct `lowest_unique_key`...
