### ISSUE TITLE
Code is slow when using get_hydro_state_at_point() method

### ISSUE THREAD

**Issue by kyliow** [amusecode/amuse#628]
Hi there,

Thanks for your time. I'm using the instruction shown in page 5-22 of AMUSE textbook to make density maps of my SPH simulations. I create a density map at every timestep, starting from an isothermal molecular cloud. However, I notice a significant slowdown at later times, presumably when there exists very dense regions in the simulations, and the slowdown happens at the method get_hyrdo_state_at_point(). 

For my test model with 1 million SPH particles, ran using Fi, it takes about 2-3 minutes per timestep at earlier times, but about 1-2 hours per timestep at later times. May I ask if this slowdown is expected? If yes, why; and if not, how to improve? 

Thanks in advance :) 

Regards, Kong

**Comment by rieder** [comment]
Hi Kong,
Does this happen when you include stars via Bridge? If so, is there a correlation with the number of stars?
Cheers

**Comment by kyleastro** [comment]
> Hi Kong,
> Does this happen when you include stars via Bridge? If so, is there a correlation with the number of stars?
> Cheers

Hi Steven, 
This is from a separate visualisation script, not the main script that runs the simulation, i.e. no bridge code is involved in this visualisation script. Sorry but I don't understand how including the bridge code in this visualisation script would help, or am I missing something here?

Basically, what I have in this visualisation script is to first read the gas particles from the dumpfile of the simulation script. I add the gas particles to the sph code, then use sph.get_hydro_state_at_point() and pyplot.imshow() to plot the density map, then finally remove the gas particles from the sph code. This is repeated for every timestep. 

Apologies for being unclear previously. Hope my problem is clearer now. Thanks :)

**Comment by rieder** [comment]
So running this visualisation standalone on a savefile at early times is fast, whereas a savefile from later times is much slower?
If this is the case, could you check if the savefiles are about the same size?

**Comment by kyleastro** [comment]
> So running this visualisation standalone on a savefile at early times is fast, whereas a savefile from later times is much slower?

Yup :)

> If this is the case, could you check if the savefiles are about the same size?

Yes they are about the same size. In fact it starts of slightly larger (115MB) than the latest savefile (111MB).

**Comment by rieder** [comment]
can you attach the visualisation script?

**Comment by kyleastro** [comment]
[visual.txt](https://github.com/amusecode/amuse/files/4651624/visual.txt)
It should work after changing the extension to .py. I attach the whole (rather simple) script to preserve everything including potential bugs. Thank you!
