### ISSUE TITLE
Encounter in the Multiples module: What is the maximum number of stars to be part of the SmallN integration ?

### ISSUE THREAD

**Issue by timroland** [amusecode/amuse#629]
Hello there,

I have a technical question concerning the SmallN code which I use to resolve encounters within the "Multiples" module. If I understand correctly, when a collision is detected, encountered stars and potential perturbers are passed to the SmallN code to resolve the event. My concern relates to the number of perturbers, and therefore my question is the following:
**What happens if tens of stars (up to ~100) are considered as perturbers and added to the scattering experiment ?** (apart from slowing down tremendously the computation...) Since the SmallN code is designed to handle systems of less than ten particles, should I absolutely prevent such events to happen ?

I think I will have to tweak the parameter `neighbor_perturbation_limit` which regulate the perturbation threshold, but it seems to be really system dependant. That's why I am looking for some information to get to the best compromise.

NB : I have similar N-body configurations than thos of Joshua Wall in his paper https://arxiv.org/abs/1901.01132. However his description suggests a condition to test perturbers in a different way (equation 26). Is it something replacing what is currently implemented on the multiple module or added on top of it ? (That's perhaps an additional question to @stevemcmillan or @spzwart)

Thanks in advance,

Timothé.

**Comment by spzwart** [comment]
Dear Timothe,

You can, using smallN integrate systems with more than 10 particles. It is simply not ideal. But why not use the standard Hermite, Ph4 or Huayno integrators then, in those cases?
Cheers,
Simon

**Comment by stevemcmillan** [comment]
Timothé,

    The option to include perturbers in the smalln calculation is not used by default.  The idea was to take into account the tidal fields of “bystanders,” but including the perturbers can create some very artificial outcomes, since smalln will try to run the entire system to completion, and the logic in smalln is not well suited to removing stars 1 by 1 as they disappear into the tidal background.  The preferred (default) approach is to allow any perturber above some threshold (default 0.02) to veto the smalln calculation.  That puts more burden on the n-body integrator, but it avoids the very problem you are describing.  I suspect that with better design we could run the smalln calculation in a sphere and remove stars as they get too far away, but that is not how it is currently written.

    Josh’s Eq. 26 is used only for analysis of the results.  He used the standard AMUSE multiples module.  The equation is conceptually similar to the definition used in multiples.  If he had taken the magnitude of the vector force difference instead of the difference in force magnitudes, the dimensionless quantity \gamma_p in that equation would be essentially the same as the dimensionless perturbation \gamma defined by Aarseth (and used in NBODY6), as well as the criterion used to identify perturbers in multiples.

Hope this helps,

Steve McMillan

Stephen L. W. McMillan
Department Head and Professor of Physics, Drexel University
+1 215-895-2709/2723, FAX +1 215-895-2940, steve@physics.drexel.edu

**Comment by timroland** [comment]
Ok, thanks a lot. Yes it helps.
Those questions on how to handle multiple systems are really interesting.
Cheers,
Timothé Roland.
