### ISSUE TITLE
Travis testing isn't working for Linux/OpenMPI and macOS

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#631]
Travis testing should work for all cases. I made a new branch to work on this.

**Comment by rieder** [comment]
macOS testing fails with `checking whether the C compiler works... no`.

**Comment by ipelupessy** [comment]
I think we could explore some other continuous integration service...

**Comment by rieder** [comment]
Yes that's definitely an option. Do you know any that would be better?

I'm now attempting to set up homebrew on my old mac, so I can replicate the Travis environment better.
This is something I had meant to do anyway.

**Comment by ipelupessy** [comment]
no - though can check with other people...(tomorrow)
