### ISSUE TITLE
Bridge gets stuck using ph4 (at least) in GPU mode

### ISSUE THREAD

**Issue by rknop** [amusecode/amuse#638]
**Describe the bug**
Using Bridge to connect ph4 and Fi.  When ph4 is in CPU mode, everything runs.  When ph4 is in GPU mode, the code stops on or after the first evolution of the individual codes that the bridge is connecting.

**To Reproduce**
I've attached gravhydrotest.py.  Change mode="gpu" to mode="cpu" in the ph4 instantiation, and the code runs through to the end.  With mode="gpu", the code hangs up after the first kick/drift (see gravhydrotest_gpu.log).

**Expected behavior**
I expect the bridge to function when ph4 is in GPU mode just as it does when ph4 is in CPU mode.

**Logs**
I've attached two files.  gravhydrotest_cpu.log is stdout with mode="cpu" on ph4, and gravhydrotest_gpu.log is stdout with mode="gpu" on ph4.  The cpu version ran in a second or so.  I interrupted the gpu version after about a minute.

**Environment (please complete the following information):**
 - OS and version: Devuan GNU/Linux ascii
 - Compiler: gcc 6.3, python 3.5

**Additional context**
GPU is GeForce GTX TITAN Z
[gravhydrotest.py.zip](https://github.com/amusecode/amuse/files/4735237/gravhydrotest.py.zip)

[gravhydrotest_cpu.log](https://github.com/amusecode/amuse/files/4735238/gravhydrotest_cpu.log)
[gravhydrotest_gpu.log](https://github.com/amusecode/amuse/files/4735239/gravhydrotest_gpu.log)

**Comment by rieder** [comment]
@rknop are you still experiencing this?
Unfortunately I don't have a Sapporo-compatible GPU to test this with myself...
