### ISSUE TITLE
Codes with multiple integrators: add individual literature references

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#64]
Rebound has the option of using various integrators (IAS15, WHFast etc.). These have separate literature references, which should be added to the literature output of AMUSE as well.

**Comment by rieder** [comment]
Is it possible to do a "LiteratureReferencesMixIn" for other things than classes, like functions?

**Comment by rieder** [comment]
@arjenve @ipelupessy any ideas about this? It may be relevant for other codes that have various integrators (like Huayno(?) and FDPS at some point) as well.

**Comment by ipelupessy** [comment]
I think you can add the references to the rebound docstring for the moment...the other things are nice, but not possible at the moment I think...

**Comment by rieder** [comment]
Ok, that's a decent first step. I'll add the required references to the Rebound interface.

**Comment by ipelupessy** [comment]
close since partially solved, rest is prob wontfix
