### ISSUE TITLE
Decouple amuse and seba repositories

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#643]
The main repository for SeBa development is currently the same as the main AMUSE repository. 
Since both are actively developed and largely independent of each other, I think it would be better to decouple these repositories (and use a download script to get SeBa for AMUSE). That way both can have distinct versions with clear change logs. Also would make it clearer who is responsible for each part.
This should be possible while retaining the file histories.

**Comment by rieder** [comment]
@silviatoonen @ipelupessy I hope to hear your thoughts on this.

**Comment by ipelupessy** [comment]
I have no preference either way..

**Comment by rieder** [comment]
it can be done using 'git subtree split'. I made a splitoff in https://github.com/rieder/seba to see how this would work.

**Comment by ipelupessy** [comment]
btw, seba build is currently broken

**Comment by ipelupessy** [comment]
and there are a lot of warnings of the "no return statement in function returning non-void" type. Despite being just a warning this can cause nasty seg fault errors.

**Comment by ipelupessy** [comment]
for example:
```
#include <stdio.h>

int f()
{
}

int main()
{
  printf("calling returnless nonvoid\n");
  f();
  return 0;
}
```
compiling this with:
```g++ test.c```
and then running segfaults on recent gcc

**Comment by spzwart** [comment]
Steven,
I am not in favor of decoupling SeBa from AMUSE-framework.
The reason is that I think that AMUSE should come with a full suit of minimal codes, and I would count SeBa as the fundamental stellar/binary evolution code in AMUSE.

Simon

**Comment by rieder** [comment]
I fully agree on that point, and I don't think this is at risk by decoupling the repositories.
Not even with the "developer" installation - we can use git subtree (https://www.atlassian.com/git/tutorials/git-subtree) to link repositories.

**Comment by ipelupessy** [comment]
it does complicate a little bit...the earlier git submodules where not so nice in this respect, don't know about subtrees..

**Comment by rieder** [comment]
subtree is supposed to be a lot better in this respect. Still, requires some testing to find out exactly.

**Comment by rieder** [comment]
> and there are a lot of warnings of the "no return statement in function returning non-void" type. Despite being just a warning this can cause nasty seg fault errors.

@silviatoonen did you notice this?

**Comment by silviatoonen** [comment]
If the subtree option works well, I'd be in favour of that. It's been a bit messy previously with the Amuse development and the SeBa development through one another. 
Ps I've fixed the bug in SeBa. 
PSPS There are indeed a lot of warnings, and with compilers getting more strict as time goes by, these will give issues at some time/ some platforms. Most of them go above my level of C-compiling. I'm happy to sit down with someone that does

**Comment by ipelupessy** [comment]
ok, thanks!
for the rest: I would try to fix the missing return type warnings asap by adding returns (or converting functions to void - the problem is that for c++ its not legal to have a function that has a return type return nothing, even if the return value is not used...), the other things are probably not so critical...

**Comment by rieder** [comment]
> If the subtree option works well, I'd be in favour of that. It's been a bit messy previously with the Amuse development and the SeBa development through one another.
Maybe we should test if this is an adequate solution sometime this/next week?

**Comment by rieder** [comment]
@silviatoonen I've created a splitoff repository for SeBa: https://github.com/amusecode/SeBa.
This contains the full commit history from the AMUSE repository related to SeBa. 
Currently, SeBa lives in both repositories - which is not ideal, obviously. It would be best if any further development is done in the new repository, which we can then download into AMUSE in the same way as how we treat other community codes (like PeTar - I'll submit a PR for that next).
For any current (but not yet committed) development, maybe it's best to just copy it over to the new repository.

**Comment by ipelupessy** [comment]
the new repo needs a readme...

**Comment by rieder** [comment]
Added a very basic Readme, based on the info in the amuse interface.py. Needs updating.
