### ISSUE TITLE
SimpleX crashes on second call with multiple workers

### ISSUE THREAD

**Issue by MJCWilhelm** [amusecode/amuse#651]
**Describe the bug**
When running SimpleX with >1 worker, the code crashes on a second call of the evolve_model function. I've tracked down the error to the send_new_vertex_list function (part of the (re)commit_particles function), to the line where the vertices are being sent (starting with '{MPI_Status status;'), it appears to be some vector out-of-bounds error.

**To Reproduce**
Set up a SimpleX simulation with number_of_workers=2 and call evolve_model twice. I've attached a minimal example.

[simplex_minimal.py.txt](https://github.com/amusecode/amuse/files/4836389/simplex_minimal.py.txt)

**Environment (please complete the following information):**
- Fedora 31
- gcc version 9.3.1
- the standard environment of Leiden Observatory

**Comment by ipelupessy** [comment]
For me the script works.. (gcc 10.1.1 +mpich)

**Comment by MJCWilhelm** [comment]
This also worked on my own laptop, so I think it's an issue with the environment on those computers (the way mpi works there is... interesting). I'll close the issue.
