### ISSUE TITLE
mass_min support for other IMFs than Salpeter

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#653]
The new_salpeter_mass_distribution function in AMUSE has support for a mass_min keyword, while other IMFs (e.g. those in brokenimf.py) don't support this. 
We may want to make this keyword more universal.

**Comment by spzwart** [comment]
absolutely. this was an ever returning concern/irritation. time to do something about it.....
Simon

**Comment by rieder** [comment]
Fixed in #655.
