### ISSUE TITLE
MPFR detection issues

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#662]
**Describe the bug**
sometimes (always?) the pkg-config for mpfr does not add the correct directories for the -I and -L flags, typically this doesn't matter, but some (mac) configurations  do not seem to find it then..

**To Reproduce**
see the discussion in issue #609 

**Expected behavior**
correct detection of mpfr location

**Environment (please complete the following information):**
mainly macos

**Additional context**
I have not yet found another project where this is done correctly...

**Comment by rieder** [comment]
This is a duplicate of #209
