### ISSUE TITLE
How to install amuse in Windows?

### ISSUE THREAD

**Issue by fertiss** [amusecode/amuse#664]

**Comment by ipelupessy** [comment]
the recommended way of installing AMUSE on windows (10 only) is through the windows subsystem for linux (WSL) 2, is that an option?

**Comment by fertiss** [comment]
yes ok, whatever is the best way.

**Comment by ipelupessy** [comment]
ok, then the procedure is as follows:
  - install WSL 2 as per microsoft instructions (https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2 )
  - install ubuntu (or another linux distro) from the windows store
  - start up the ubuntu image and follow the AMUSE install instructions for linux

**Comment by JPGlaser** [comment]
I can confirm this works fine on Windows 10 using the Ubuntu distro install from the Windows Store. This includes installing via pip although compiling from source can help fix any errors that come up.

~ Joe G.

**Comment by rieder** [comment]
Multipass (https://multipass.run) is another way of installing Ubuntu (on Windows, but also on macOS and even Linux). This works very well in my limited experience so far.

**Comment by ipelupessy** [comment]
closing as solved

vagrant is another option btw
