### ISSUE TITLE
Slower runtime and large increase in file size using bridge

### ISSUE THREAD

**Issue by amaheshwari25** [amusecode/amuse#666]
Hello,

I'm working on evolving a globular cluster using AMUSE N-body codes (BHTree specifically, for now) based on its own self-gravity and a background MW potential, using `galpy`'s `to_amuse` functionality and then the `bridge` in AMUSE. I've been finding that the runtime has increased drastically, along with the file size when trying to save various model checkpoints to a HDF5 file, and was wondering if there is some way around these increases. 

For more details, I'm running a King model of N=20,000 upto t=20 n-body times. Just evolving this by itself with BHTree takes roughly 4 minutes, whereas with the gravitational potential it takes upto 4 hours – is this an expected increase? 

What I especially don't understand is the file size increase: previously saving roughly 4-5 different timestamps in the GC evolution to an HDF5 file was ~40 Mb, whereas now with the MW potential bridge runs, the same number of checkpoints is ~600 Mb. Why does this happen, and if I'm just trying to save the same sort of data (mass, x, y, z, vx, vy, vz) of the particles and don't care about any other history, is there any way to make the file more lightweight?

The main parts of my code to save the model state are below: 
`channel_grav_to_stars = grav_code.particles.new_channel_to(model, attributes=["mass", "x", "y", "z", "vx", "vy", "vz"])`
...
`io.write_set_to_file(model.savepoint(evol_time), write_fname, append_to_file=True, format="hdf5")`
where `grav_code` is based on the call to `BHTree()` earlier on, that is added to the bridge along with the MW potential. 

Thank you so much in advance, and please let me know if I can clarify any part of my question!

**Comment by spzwart** [comment]
Dear Arya,

the checkpointing in writing files is known to contain a memory leak, but
that cannot explain your experienced problems. without more details about
your script it's hard to see what could be wrong. There are probably
seversl unrelated issues. the long runt rime may be caused by an N^2
operation in the bridge step. you could use the treecode to replace that
N^2 operation. another problem may be the bridge timestep. what timestep
are you using? The larger filesize is very puzzeling. maybe you are
appening more data snapshots than you think. As I said before, without a
better understamding of your script, it's hard to know precisely.

cheers,
Simon

**Comment by amaheshwari25** [comment]
Hi Simon, 
Thank you for your prompt reply! I have attached the operative portions of my script — there are some extraneous references to other functions (like plotting, etc) that I have commented out — so hopefully that can help in elucidating the issue. 

Can you explain what you mean by using the treecode to replace the N^2 operation in bridge and how I would do that? I wasn't sure exactly what timestep to use for the bridge, so I didn't set any, assuming it would default to a reasonable value. Is that a problem? 

Thank you again for your help,
Arya
[script.txt](https://github.com/amusecode/amuse/files/5077428/script.txt)

**Comment by spzwart** [comment]
thank Arya,

Not setting a bridge timestep is not a good idea, and initialising it
properly surely will improve things. you should read my book on amuse, then
things get a lot more clear. check out the hierarchical coupling chapter.
in your case, a bridge time step of order unity, in N-body time units, will
probably speed-up things.
good luck,
'john'

**Comment by amaheshwari25** [comment]
Ah, ok, thank you so much! I will read up on that and try that fix and let you know if it clears things up.

Arya
