### ISSUE TITLE
CalculateFieldForCodesUsingRemove : A Bridge too far .. ? 

### ISSUE THREAD

**Issue by christianboily** [amusecode/amuse#667]
Sorry for asking but it seems like the gas self-gravity is lost when coupled simply with a bridge to a gravity code. 

I tried to compute the gravity field (acc, pot) of SPH gas elements using my experience from the gravity_gas.py script in the textbook/ depository, to something like this : 

    hydro = Hydro(Gadget2, ism, eps)
    model_time = 0 | units.Myr

    tree_code = BHTree(converter, mode="openmp")
    in_dict = dict( verbose=True, required_attributes=['mass', 'x','y','z'] ) # , particles_in_set="gas_particles" )                         
    gravity_for_hydro = CalculateFieldForCodesUsingRemove( tree_code, hydro.code, **in_dict )

then create a bridge : the gravity code computes the orbit of a pair of stars in the background gas, a classic example : 

    gravhydro = bridge.Bridge(use_threading=False)
    gravhydro.add_system(gravity, (gravity_for_hydro,), True)
    gravhydro.add_system(hydro, (gravity_for_hydro,gravity,), True)  # True/False : forced sybchronisation - cmb                             

    gravhydro.timestep = 0.1 | units.yr

But when I loop over the system gravhydro, I get that "gadget2" is not an iterable item. Do you have an idea what may be going wrong ? 

thanks in advance, 

chris b.

**Comment by MJCWilhelm** [comment]
get_gravity_at_point and get_potential_at_point are indeed not implemented in the gadget2 interface (they simply return -2), a number of students in the AMUSE course have run into this. They instead used fi and/or bhtree when bridging, but some noticed that gadget2 ran much faster than fi.

**Comment by ipelupessy** [comment]
closing; get_gravity_at_point and get_potential_at_point  would be a seperate issue
