### ISSUE TITLE
slot issue in nosetests 

### ISSUE THREAD

**Issue by ritikshah44** [amusecode/amuse#668]
nosetests -v
Invalid MIT-MAGIC-COOKIE-1 key/home/ritik_shah/Desktop/amuse/src/amuse/community/symple/test.py:85: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
/home/ritik_shah/Desktop/amuse/src/amuse/units/generic_unit_converter.py:189: RuntimeWarning: overflow encountered in double_scalars
  return new_quantity(number * factor, new_unit)
amuse.community.kepler.test_kepler.test1 ... inner semi = 1,  ecc = 0.5
m1, m2, m3 = 0.5 0.5 0.5
v_inf = 0,  energy3 = 0,  impact_parameter = 0
mean_anomaly = -0.001
outer semi = 0,  ecc = 1
k->get_normal_unit_vector() = 0.929321  0.275974  -0.245357
k->get_periastron() = 0
k->get_separation() = 79.3701,  k->get_time() = -272.165
*time = -272.165
ok
amuse.community.kepler_orbiters.test_kepler.test_kepler ... ok
amuse.community.kepler_orbiters.test_kepler.test_kepler_almost_parabolic ... #---WARNING: Floating point precision used may be lower than required.
#---err flag: None
#   dt0: 0x1.921fb54442d18p+2, m: 0x1p+0, e2: 0x0p+0, r0x: 0x1.ad7f296f0f7c2p-24, r0y: 0x1.398dcdcbeca2cp-36, r0z: 0x0p+0, v0x: -0x1.981c32a81a0c7p-2, v0y: 0x1.17822c45d0297p+12, v0z: 0x0p+0
#   r0: 0x1.ad7f29e183f46p-24, r0v0: 0x1.5658fa9410f8fp-25, v0sqr: 0x1.312cfed9d3e82p+24, u0sqr: 0x1.312cffd9d3e8p+24, alpha0: -0x1.ffffffb456671p-1
#---
#---WARNING: Maximum iteration steps reached in 'findroot' function. Trying again with two steps of size dt0/2.
#---err flag: -1
#   dt0: 0x1.921fb54442d18p+2, m: 0x1p+0, e2: 0x0p+0, r0x: 0x1.ad7f296f0f7c2p-24, r0y: 0x1.398dcdcbeca2cp-36, r0z: 0x0p+0, v0x: -0x1.981c32a81a0c7p-2, v0y: 0x1.17822c45d0297p+12, v0z: 0x0p+0
#   dt: 0x1.921fb54442d18p+2, r0: 0x1.ad7f29e183f46p-24, r0v0: 0x1.5658fa9410f8fp-25, v0sqr: 0x1.312cfed9d3e82p+24, u0sqr: 0x1.312cffd9d3e8p+24, alpha0: -0x1.ffffffb456671p-1, s0: 0x1.921fb508d5f8ep+2, s: 0x1.919e3f196c84dp+2, ss: -0x1.921fb680e55f7p+3
#---
#---WARNING: Floating point precision used may be lower than required.
#---err flag: None
#   dt0: 0x1.921fb54442d18p+1, m: 0x1p+0, e2: 0x0p+0, r0x: 0x1.ad7f296f0f7c2p-24, r0y: 0x1.398dcdcbeca2cp-36, r0z: 0x0p+0, v0x: -0x1.981c32a81a0c7p-2, v0y: 0x1.17822c45d0297p+12, v0z: 0x0p+0
#   r0: 0x1.ad7f29e183f46p-24, r0v0: 0x1.5658fa9410f8fp-25, v0sqr: 0x1.312cfed9d3e82p+24, u0sqr: 0x1.312cffd9d3e8p+24, alpha0: -0x1.ffffffb456671p-1
#---
ok
amuse.community.kepler_orbiters.test_kepler.test_kepler_parabolic ... #---WARNING: Floating point precision used may be lower than required.
#---err flag: None
#   dt0: 0x1p+0, m: 0x1p+0, e2: 0x0p+0, r0x: 0x1p+0, r0y: 0x0p+0, r0z: 0x0p+0, v0x: 0x0p+0, v0y: 0x1.6a09e6688f3b6p+0, v0z: 0x0p+0
#   r0: 0x1p+0, r0v0: 0x0p+0, v0sqr: 0x1.00000000dbe7p+1, u0sqr: 0x1p+1, alpha0: 0x1.b7cdf60c31221p-32
#---
ok
amuse.community.kepler_orbiters.test_kepler.crash_test ... --------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 1
slots that were requested by the application:

  /home/ritik_shah/Desktop/amuse/src/amuse/community/kepler_orbiters/keplerorbiters_worker

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------
ERROR
amuse.community.kepler_orbiters.test_kepler.crash_test2 ... --------------------------------------------------------------------------
All nodes which are allocated for this job are already filled.
--------------------------------------------------------------------------
ERROR
amuse.community.kepler_orbiters.test_kepler.test_softening ... ERROR
test1 (amuse.community.mmc.amuselib.test_support.supportInterfaceTests) ... ERROR
test2 (amuse.community.mmc.amuselib.test_support.supportInterfaceTests) ... ERROR
[ritik-shah:82417] 3 more processes have sent help message help-orte-rmaps-base.txt / orte-rmaps-base:all-available-resources-used
[ritik-shah:82417] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[ritik-shah:82401] [[55674,1],0] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 653
[ritik-shah:82401] [[55674,1],0] ORTE_ERROR_LOG: Unreachable in file dpm/dpm.c at line 653
Exception ignored in: <function CodeInterface.__del__ at 0x7fe4c0568040>
Traceback (most recent call last):
  File "/home/ritik_shah/Desktop/amuse/src/amuse/rfi/core.py", line 755, in __del__
    self._stop()
  File "/home/ritik_shah/Desktop/amuse/src/amuse/rfi/core.py", line 845, in _stop
    self._stop_worker()
  File "/home/ritik_shah/Desktop/amuse/src/amuse/rfi/core.py", line 123, in __call__
    raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}'".format(self.specification.name, type(self.interface).__name__, ex))
amuse.support.exceptions.CodeException: Exception when calling function '_stop_worker', of code 'KeplerInterface', exception was 'Error in code: no error message - code probably died, sorry.'
Failure: ImportError (cannot import name 'clock' from 'time' (unknown location)) ... ERROR
test01 (amuse.community.sakura.ggf.old_test_sakura.TestSakura) ... ERROR
test03 (amuse.community.sakura.ggf.old_test_sakura.TestSakura) ... ERROR
test05 (amuse.community.sakura.ggf.old_test_sakura.TestSakura) ... ERROR
test06 (amuse.community.sakura.ggf.old_test_sakura.TestSakura) ... ERROR
test09 (amuse.community.sakura.ggf.old_test_sakura.TestSakura) ... ERROR
test11 (amuse.community.sakura.ggf.old_test_sakura.TestSakura) ... ERROR
test01 (amuse.community.sakura.ggf.old_test_sakura.TestSakuraInterface) ... ERROR
test02 (amuse.community.sakura.ggf.old_test_sakura.TestSakuraInterface) ... ERROR
test03 (amuse.community.sakura.ggf.old_test_sakura.TestSakuraInterface) ... ERROR
test05 (amuse.community.sakura.ggf.old_test_sakura.TestSakuraInterface) ... ERROR
test0 (amuse.community.sei.test_sei.TestSei) ... ERROR
test0 (amuse.community.sei.test_sei.TestSeiInterface) ... ERROR

I am getting this slot issue many times and don't know how to solve it also the Invalid " MIT-MAGIC-COOKIE-1 " issue

**Comment by ipelupessy** [comment]
probably oversubscribe fixes,
closing.
