### ISSUE TITLE
installin prerequisites via ./install.py install

### ISSUE THREAD

**Issue by kiya1990** [amusecode/amuse#674]
Hi there,
I used the git clone https://github.com/amusecode/amuse.git to download the AMUSE and follow the steps to install the prerequisites through the python, but when I run $> ./install.py install ,  I will face the following error... can anyone help how can I resolve it?

/home/kiyarash/amuse/prerequisites/install/_temp/h5py-2.4.0/h5py/defs.c:651:10: fatal error: hdf5_hl.h: No such file or directory
  651 | #include "hdf5_hl.h"
      |          ^~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "./install.py", line 758, in <module>
    _commands[x](names, skip)
  File "./install.py", line 683, in install
    INSTALL.build_apps(names, skip)
  File "./install.py", line 561, in build_apps
    function(temp_app_dir)
  File "./install.py", line 239, in h5py_build
    self.run_application([PYTHON,'setup.py','build'],cwd=path)
  File "./install.py", line 234, in run_application
    raise Exception("Error when running <" + commandline + ">")
Exception: Error when running </home/kiyarash/amuse/prerequisites/bin/python3 setup.py build>

**Comment by ipelupessy** [comment]
thanks for the report, it looks similar to issues reported in #672, so the install.py should probably be updated..

**Comment by ipelupessy** [comment]
I have updated the libs, but I think you may run into the same problem - its probably because of the '--disable-hl',  line in the install.py...its not necessary for the newest hdf5, however h5py does not yet build against this...you can try commenting out this line and the --enable-threadsafe line.. (lines 251 and 254)

**Comment by kiya1990** [comment]
> I have updated the libs, but I think you may run into the same problem - its probably because of the '--disable-hl', line in the install.py...its not necessary for the newest hdf5, however h5py does not yet build against this...you can try commenting out this line and the --enable-threadsafe line.. (lines 251 and 254)

I commented out these two lines but again I ran into the problem as follows:

checking for library containing H5Fflush... no
configure: error: Can't find or link to the hdf5 library. Use --disable-netcdf-4, or see config.log for errors.
Traceback (most recent call last):
  File "./install.py", line 758, in <module>
    _commands[x](names, skip)
  File "./install.py", line 683, in install
    INSTALL.build_apps(names, skip)
  File "./install.py", line 561, in build_apps
    function(temp_app_dir)
  File "./install.py", line 365, in netcdf_build
    self.run_application(x, path, env=env)
  File "./install.py", line 234, in run_application
    raise Exception("Error when running <" + commandline + ">")
Exception: Error when running <./configure --prefix=/home/kiyarash/amuse/amuse-13.2.0/prerequisites>

**Comment by kiya1990** [comment]
dear @ipelupessy
I commented out these two lines but again I ran into the problem as follows:

**checking for library containing H5Fflush... no
configure: error: Can't find or link to the hdf5 library. Use --disable-netcdf-4, or see config.log for errors.
Traceback (most recent call last):
File "./install.py", line 758, in
_commands[x](names, skip)
File "./install.py", line 683, in install
INSTALL.build_apps(names, skip)
File "./install.py", line 561, in build_apps
function(temp_app_dir)
File "./install.py", line 365, in netcdf_build
self.run_application(x, path, env=env)
File "./install.py", line 234, in run_application
raise Exception("Error when running <" + commandline + ">")
Exception: Error when running <./configure --prefix=/home/kiyarash/amuse/amuse-13.2.0/prerequisites>**
...............................................................................................................
I'm trying to resolve it by following the steps according to https://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html#build_default
 
this is happened exactly in #672 
I would appreciate if you have any idea to deal with this problem

**Comment by ipelupessy** [comment]
my apologies, I don't think this has been followed up properly.

closing as in #672 please reopen as seperate issue if problem persists
