### ISSUE TITLE
Installing bonsai 

### ISSUE THREAD

**Issue by Elchupakabro** [amusecode/amuse#676]
After executing 
`make bonsai.code`
Got the following error
> /usr/local/cuda-11.0/bin/nvcc    -arch sm_30 -I./include -ptx CUDAkernels/build_tree.cu -o build_tree.ptx
nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture`

**Environment**
 - Mint 20

**Comment by rieder** [comment]
Cuda keeps removing previously supported architectures - this is very annoying to keep up with... @jbedorf could you think of a way to change the compiler flags depending on the version of Cuda used?

**Comment by jbedorf** [comment]
One way would be not to specify the architecture and hope that the code does not break using whatever default the CUDA compiler picks. Although the compiler might create multiple versions such that at runtime the right version is picked. That will increase the build time, but should reduce the number of issues related to architecture deprecations.

**Comment by rieder** [comment]
Sounds preferable to me.

**Comment by rieder** [comment]
@Elchupakabro could you pull the most recent AMUSE and try making Bonsai again?

**Comment by Elchupakabro** [comment]
Seems it worked for bonsai. But bonsai2 is still bugged for some reason.

чт, 17 сент. 2020 г. в 11:43, Steven Rieder <notifications@github.com>:

**Comment by jbedorf** [comment]
For Bonsai2 you would have to modify the Makefiles yourself in the folders that are downloaded by the setup script. The bonsai2 source/make files are not directly integrated in the amuse repository.
