### ISSUE TITLE
AMUSE with Xcode 12 / on macOS 11 "Big Sur"

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#680]
Xcode 12 has now been released, in advance of macOS 11 "Big Sur".
For now I would advice everyone **not to upgrade yet** to either, since we don't know how well AMUSE and our prerequisites will install with these.
I'll test Xcode 12 soon and the new macOS when it is released, and will update when I know more.

**Comment by rieder** [comment]
A bug preventing OpenMPI from being installed with MacPorts has now been fixed, and I can now install AMUSE on macOS 11.1. 
One important bit of guidance: you will need to do `export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` (best add it to your .profile / .zprofile) or configure will fail.

Since the versioning of macOS has now changed (e.g. a minor version upgrade used to be 10.14.1->10.14.2, now it's 11.0->11.1), software may/will complain more about these updates. Hopefully this will be fixed soon but we have no control over this.
Currently this affects binary MacPorts libraries like fftw-3, which are currently built for 11.0 and will fail to link on 11.1. Annoyingly, these will need to installed/built from source with 'port install -s' until MacPorts fixes this.

(cc @stevemcmillan)

**Comment by pasolar** [comment]
Hi, 
i have been using AMUSE for a year, and i use macOS 10.15 Catalina, I would like to know if anyone  was able to run AMUSE on MacOS 11.5.2 'Big Sur' or higher , and if you had problems with the upgrade, thanks.
