### ISSUE TITLE
Petar test / runtime issue

### ISSUE THREAD

**Issue by christianboily** [amusecode/amuse#682]
hello, I have been successful at running PeTar on a MaxOSX (10.14.8) without a GPU - laptop - but the 
installation on Ubuntu 18.04 + GPU K40  leads to the code not being setup : 

> ```
> - [Amuse-13_2] astromaster:~/Amuse/Petar> python run_.py
> - Create code Petar : 
> - --------------------------------------------------------------------------
> - [[23344,1],0]: A high-performance Open MPI point-to-point messaging module
> - was unable to find any relevant network interfaces:
> - 
> - Module: OpenFabrics (openib)
> -   Host: astromaster
> - 
> - Another transport will be used instead, although this may result in
> - lower performance.
> - --------------------------------------------------------------------------
> - -------------------------------------------------------
> - Child job 2 terminated normally, but 1 process returned
> - a non-zero exit code.. Per user-direction, the job has been aborted.
> - -------------------------------------------------------
> - 
> ```
> 

My script is a simple test run - the one used on my laptop : see attached .py file 

I also found no specific issues when compiling the code on either machines. The log file is attached. 

Any idea what the issue may be ? Also I did not find a test script in the Amuse tree : has anyone a sample code available ? 

Cheers, chris b. 
[logfile.txt](https://github.com/amusecode/amuse/files/5282797/logfile.txt)

[run_.py.txt](https://github.com/amusecode/amuse/files/5282802/run_.py.txt)

**Comment by rieder** [comment]
Hi Chris,

PeTar is still quite new, so we expect the occasional bug.
Having said that, we have done some testing and updating to PeTar just these last few weeks.
Could you try with the current version on github (just also pushing a new package to PyPI now)?
Your script works for me, apart from the final `code.stop()` (fixed in https://github.com/lwang-astro/PeTar/pull/9, but @lwang-astro will have to merge this first).

**Comment by lwang-astro** [comment]
The merge is finished, you can pull the new version of PeTar.

**Comment by rieder** [comment]
Thanks @lwang-astro! I updated the PeTar package again to include this bugfix.

**Comment by christianboily** [comment]
hi, thanks for your feedback! I did a pull + make peter.code but got the same result. Question : *must* the path to coda_sdk be explicitly given in the configuration file .. ?

**Comment by rieder** [comment]
Hi @christianboily ,
I'm not sure if PeTar in AMUSE already works with the GPU - I don't think it does yet. So it won't matter then...
I assume you did `make petar.code` (typo)?
Could you run it with `code = PeTar(converter, redirection="none")`?

**Comment by christianboily** [comment]
hi back - yes that was a typo, but not with redirection = "none" I get this error message 

----------------
(null) noticed that process rank 0 with PID 9202 on node astromaster exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

ie it seems like the code crashes as it is being loaded, perhaps a memory allocation error ? This is my 
compiler version 

g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

Are you using a more recent one ? On my OSX machine, I am using g++-9 .. (I don't have root access on the Ubuntu machine).

**Comment by rieder** [comment]
Yes I'm using gcc 9... I don't have access to any machine with gcc 5 or lower at the moment, so I can't test this. Perhaps PeTar requires a more modern gcc, what do you think @lwang-astro ?

**Comment by lwang-astro** [comment]
The c++ compiler must support C++11 standard. Besides, you may need to set OMP_STACKSIZE=128M in the environment variables

**Comment by christianboily** [comment]
Hi again, I have been running PeTar @ amuse and PeTar @ stand-alone so far with some success. For the stand-alone version, I appreciate very much the coupling to the Galpy module of external potentials, the results appear coherent etc. A great tool. 

So I of course caught the idea of using the same setup in Amuse : bridging PeTar to a Galpy potential using the to_amuse() 
utility advertised on the Galpy doc pages. But sadly a Bridge requires to set a softening length (epsilon_squared) and PeTar does not accept one. Is there a simple work around this issue, or can one "add" a dummy parameter to PeTar so that the Bridge does not complain ? By the way, I did try to build the Bridge with the zero_smoothing parameter : 

```
> cluster_code = Petar(converter,number_of_workers=1, mode="openmp")
> # Setup gravity bridge
> gravity= bridge.Bridge(use_threading=False)
> # Stars in cluster_code depend on gravity from external potential mwp_amuse (i.e., MWPotential2014)
> gravity.add_system(cluster_code, partners=(mwp_amuse,), zero_smoothing=True ) # MWP is the Galpy external pot
> 
```
thinking that would prevent setting epsilon_squared but that seems to have no effect. Any suggestion how one should brigde PeTar .. ? (Note - the Galpy to_amuse() utility only works with a  single node - tested with BHTree, ph4, nb6xx, phigpu .. - so has limited scope so far but I think it is a very useful tool.)

cheers
