### ISSUE TITLE
Bonsai with two or more workers

### ISSUE THREAD

**Issue by yohai-scinet** [amusecode/amuse#683]
I'm not able to use Bonsai with two or more workers on the same node (one worker / GPU seems to work). I'm using commit ae62e26. The test code is:

    #!/usr/bin/env python3
    from amuse.units import constants, units, nbody_system
    from amuse.community.bonsai.interface import Bonsai as interface
    from amuse.ic.plummer import new_plummer_sphere

    if __name__=='__main__':
        convert_nbody = nbody_system.nbody_to_si(4.0E+05 | units.MSun, 20 | units.parsec)
        plummer = new_plummer_sphere(32768, convert_nbody)
        sys = interface(convert_nbody, mode="gpu", redirection='none', number_of_workers=2)
        sys.particles.add_particle(plummer)
        sys.evolve_model(0.125 | nbody_system.time)
        sys.stop()

The error is:

    NSAMP [0]: sample: -2147483648 nrate: nan finalrate: 0 localTree.n: 32768                     previous: 0 timeLocal: 0.003253 prevTimeLocal: 0.003253 
    Cuda driver error <CUDA_ERROR_INVALID_VALUE> in file './include/my_cuda.h' in line 1592.
    NSAMP [1]: sample: -2147483648 nrate: nan finalrate: 0 localTree.n: 32768                     previous: 0 timeLocal: 0.003345 prevTimeLocal: 0.003345 
    Cuda driver error <CUDA_ERROR_INVALID_VALUE> in file './include/my_cuda.h' in line 1592.

The full output is here [bonsai_output.txt](https://github.com/amusecode/amuse/files/5287522/bonsai_output.txt). Thanks!

**Comment by rieder** [comment]
@jbedorf any ideas?

**Comment by rieder** [comment]
@yohai-scinet I guess this is Bonsai rather than Bonsai2, right? Could you try if Bonsai2 works?

**Comment by spzwart** [comment]
indeed Yohai,
it is the single gpu version of bonsay that's in amuse. we nevet got around
how to make the multiple node to work, and fow the way we use bonsai and
amuse this did not teally matter. sorry for not being able to be more
positive about this..
simom

**Comment by jbedorf** [comment]
Neither bonsai or bonsai2 work with multi-workers inside AMUSE. Bonsai2 only works with multiple workers outside of AMUSE if you run it standalone.

**Comment by yohai-scinet** [comment]
Thanks for the the explanation guys.
