### ISSUE TITLE
ph4 run slows down significantly at increased times?

### ISSUE THREAD

**Issue by amaheshwari25** [amusecode/amuse#685]
Hi, 

I'm trying to run some simulations with ph4 on a cluster of 2000 stars, with a timestep of 0.2 (bridged with a static MW potential imported from galpy). It seems that the ph4 code is slowly down significantly as the n-body time of simulation increases: I had noticed this a little in some initial runs, but after some print statements to debug this seems very clear. When t is around 1 nbody time, the ph4 code seems to be progress 0.2 nbody times roughly every 3 seconds, yet when it gets to around 20 nbody times, there now is about 20-30 seconds between each step of 0.2 nbody times. 

Does anyone have any idea why this might be happening? I'm not sure if there's some issue with my code — I'm hoping that's the case, rather than this being an actual problem with the ph4 code ... Please let me know!

**Comment by rieder** [comment]
ph4 uses a dynamic timestep. As you get a denser star cluster, it will take shorter internal time steps and therefore run slower. This is especially true if you form any binaries.

**Comment by JPGlaser** [comment]
@rieder is 100% correct here. It is likely that unless you have something to deal with dynamical binaries (like the Multiples interface) that you will continue to see this ramp up through the mass segregation phase. There are a few examples on how to Bridge Multiples+PH4 with GalPy or the like in the textbook towards the back. If you need extra help, hit me up directly at astroglaser@gmail.com. This is my bread-and-butter.

~ Joe G.

**Comment by rieder** [comment]
You could also try to use the new petar gravity code (Wang et al. 2020), which uses algorithmic regularisation to deal with binaries. The AMUSE interface for it is available now.

**Comment by amaheshwari25** [comment]
Ok, thanks so much for the help; that explains a lot. We are not particularly focused on the core/densest region of the GC, insofar as a timestep that's too large doesn't allow the core region to affect the outer region that is being stripped off (we're more focused on streams formations). As such, is there a way (and does it make sense?) to set a larger timestep by hand to speed up our runs?

Thanks for pointing out the petar code. Is its precision / energy error good compared to a code like ph4? All we're really trying to do right now is evolve a GC (N=2000 right now, but higher N would be better!) in the MW potential to see if and how streams begin to form — would you recommend petar for this? 

Thank you both so much!

**Comment by rieder** [comment]
Yes, I would certainly recommend petar for that.

**Comment by spzwart** [comment]
you should be perfectly able to use ph4 for that. but without the code it
is hard to guess what you are doing...

**Comment by amaheshwari25** [comment]
Hello, 

I've been starting to test things out with petar recently again, and I was wondering if someone could explain how petar timestepping works. I'm curious because I see that the timestep parameter is read-only, and while evolving a N=20000 GC for a short time (upto 1 n-body time, with snapshots at times like 0.05, 0.1, 0.3 n-body times, etc), the GC with a concentration parameter W of 5 ran a lot faster than one with a concentration parameter of 10.  

Is it some sort of dynamic timestep based on GC density? Could I get a bit more clarification on what factors are taken into account when computing the timestep (and whether there is anything the user (me) needs to fine-tune—perhaps dt_soft, the "tree time step")? 

Thank you for your help!
