### ISSUE TITLE
Problem with using pipe operator for units in py3.9+

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#687]
Python 3.9 and 3.10 have adopted PEPs 584 (1) and 604 (2) respectively. These use the pipe operator, and this might very well collide with our use of the pipe operator for creating quantities.

We will need to find a solution for this relatively soon. 

1: https://www.python.org/dev/peps/pep-0584/
2: https://www.python.org/dev/peps/pep-0604/

**Comment by rieder** [comment]
One obvious solution would be to adopt Astropy's system of units. We have discussed this before and it seems like this would be another reason to do so. 
This is of course not ideal for other *muse projects, as we don't want them to depend on astropy.
A hybrid solution could also be an option, where we move to the * operator for creating quantities but still use our own unit system. I'm unsure about the consequences this would have for distinguishing quantities and units though (how is this done in Astropy?).

**Comment by spzwart** [comment]
Sounds like a perfect topic for our workshop in the last week of October.

Simon
