### ISSUE TITLE
Error when 'make petar.code'

### ISSUE THREAD

**Issue by kyliow** [amusecode/amuse#698]
Hello all, 

I wanted to install PeTar community code in my AMUSE, and I did 'make petar.code' but it failed. Attached here is the output. Understandably my question is incomplete as I'm not sure what other information is needed to fix this issue, so please let me know if you need more info. Please also direct me to other similar issues with solution if any. Thanks in advance :)

Regards,
Kong
 
[make_petar_output2.txt](https://github.com/amusecode/amuse/files/5480975/make_petar_output2.txt)

**Comment by kyliow** [comment]
Hi all, to add on to my enquiry, from the log, it seems like this is the problem:

> worker_code.cc:1085:27: error: ‘mpi_recv_header’ was not declared in this scope
     mpi_recv_header(parent);

Seems like there is a bug in worker_code.cc. May I ask how would I fix this bug? Thanks!

**Comment by rieder** [comment]
Hi,
worker_code.cc is automatically generated by 'make' ('amusifier --type=c interface.py petarInterface -o worker_code.cc')
It looks like MPI includes are not found. This might be a bug in the Makefile, I'll check that.

**Comment by rieder** [comment]
just to check, it's just PeTar that doesn't build?
Could you try to do a `make clean && make` in the `src/amuse/community/petar` dir, and if this fails also in the `src/amuse/community/ph4` dir?

**Comment by kyliow** [comment]
Hi Steven,

Thanks for your help. Yes only PeTar didn't build when I do 
`
make framework hermite.code seba.code fi.code petar.code phantom.code
`
from the instruction you sent me. 

I tried `make clean && make` for both petar and ph4, but only petar gave me error while ph4 was built successfully (i.e. I see ph4_worker exists but not petar_worker).

**Comment by rieder** [comment]
It looks like PeTar is using g++ to build - this is wrong, it should be mpicxx.
Did you set CXX to something manually? What is the value for MPICXX in config.mk?

**Comment by kyliow** [comment]
No I didn't set anything myself. MPICXX=g++ in config.mk. CXX=g++ in config.mk too.

**Comment by rieder** [comment]
Could you please re-run `./configure` in the AMUSE root dir? It should detect mpicxx and set the variable.

**Comment by kyliow** [comment]
Hi Steven, so I did `./configure` and then rerun `make petar.code` and for other community codes. Petar is now successfully built, but unfortunately Fi is not this time (Fi was built previously). Attached below is the output when I ran `make fi.code`. 
[make_fi_output.txt](https://github.com/amusecode/amuse/files/5488051/make_fi_output.txt)

**Comment by rieder** [comment]
for Fi you'll need to load the correct (= matching your MPI compilers) fftw module.

**Comment by kyliow** [comment]
Thanks to your advice, I rerun `./configure` after loading the fftw module, and Fi code is built successfully now. Thanks and I'll close this issue.
