### ISSUE TITLE
Issue with Flash.Code Build on Sterile CentOS7

### ISSUE THREAD

**Issue by JPGlaser** [amusecode/amuse#701]
**Describe the bug**
Building `FLASH` with `AMUSE` results in an error despite: all other codes working perfectly; `FLASH` being in the correct directory thanks to `Torch`; and being in a sterile CentOS 7 environment.

**To Reproduce**
See included `singularity` recipe file.

**Expected behavior**
For the file to be found and the build to proceed.

**Logs**
```
+ make flash.code
/usr/local/anaconda/bin/python setup.py -v build_code --inplace --clean=yes --code-name=flash
running build_code
cleaning src/amuse/community/flash
make -C src/amuse/community/flash clean
make[1]: Entering directory `/opt/amuse/src/amuse/community/flash'
rm -f -f *.so *.o *.pyc worker_code.cc worker_code.h #flash.par
rm -f *~ flash_worker worker_code.f90
make -C src clean
make[2]: Entering directory `/opt/amuse/src/amuse/community/flash/src'
rm -f *.o *.a
make[2]: Leaving directory `/opt/amuse/src/amuse/community/flash/src'
make[1]: Leaving directory `/opt/amuse/src/amuse/community/flash'
building libraries and community codes
build, for logging, see 'build.log'
[18:28:04] building flash
make -C src/amuse/community/flash all
make[1]: Entering directory `/opt/amuse/src/amuse/community/flash'
/opt/amuse/build.py --type=f90 interface.py FlashInterface -o worker_code.f90
make -C src all
make[2]: Entering directory `/opt/amuse/src/amuse/community/flash/src'
mpif90 -g -O2 -fPIC -c -o test.o test.f90
rm -f libflash.a
ar ruv libflash.a test.o
ar: creating libflash.a
a - test.o
ranlib libflash.a
make[2]: Leaving directory `/opt/amuse/src/amuse/community/flash/src'
mpif90 -g -O2 -fPIC -Isrc/FLASH4.6.2/object -c -o base_grid_interface.o base_grid_interface.F90
base_grid_interface.F90:417.6:

  use Grid_interface, only : Grid_getBlkIndexLimits
      1
Fatal Error: Can't open module file 'grid_interface.mod' for reading at (1): No such file or directory
make[1]: *** [base_grid_interface.o] Error 1
make[1]: Leaving directory `/opt/amuse/src/amuse/community/flash'
[18:28:05] building flash, failed, see 'build.log' for error log
Environment variables
================================================================================
AMUSE_DIR	/opt/amuse
BOOSTLIBS	
CC	gcc
CFLAGS	-g -O2 -fPIC
CUDA_LIBDIRS	-L/usr/local/cuda/lib -L/usr/local/cuda/lib64
CUDA_LIBS	-lcuda  -L/usr/local/cuda/lib64 -lcudart
CUDA_SDK	/TOBEFIXED
CUDA_TK	/usr/local/cuda
CXX	g++
CXXFLAGS	-g -O2 -fPIC
F90	gfortran
FC	gfortran
FFLAGS	-g -O2 -fPIC
FFTW_FLAGS	
FFTW_LIBS	-lfftw3 -lm   -lfftw3_threads
FORTRAN	gfortran
GSL_FLAGS	
GSL_LIBS	-lgsl -lgslcblas -lm
JAR	
JAVA	/bin/java
JAVAC	
MPICC	mpicc
MPICXX	mpicxx
MPIF90	mpif90
MUSE_PACKAGE_DIR	/opt/amuse
OPENMP_CFLAGS	-fopenmp
OPENMP_FCFLAGS	-fopenmp
PYTHON	/usr/local/anaconda/bin/python
SAPPORO_LIBS	-L/opt/amuse/lib/sapporo_light -lsapporo
Community codes not built (because of errors):
================================================================================
 * flash
================================================================================
0 out of 1 codes built, 0 out of 0 libraries built
```

**Environment (please complete the following information):**
```
# Torch Container                                             #
# =====================                                             #
#                                                                   #
# This container offers a build of Torch of of CentOS 7             #
# from the official Dockers containers.                             #
#                                                                   #
# singularity build centos8_torch.simg torch.recipe                 #
#                                                                   #
#####################################################################
Bootstrap: docker
From: centos:7

%help
  Helpful information to come. This container is running the following:
  - CentOS      7.0.0
  - HDF5        1.8.12
  - Hypre       2.11.2
  - netCDF CXX  4.2.8
  - netCDF C    4.3.3
  - netCDF F90  4.2-16
  - zlib        1.2.7
  - FLASH       4.6.2
  - OpenMPI3    3.1.3

%labels
  CREATOR Joe Glaser

%runscript
exec echo "The runscript is the containers default runtime command!"

%files
  FLASH4.6.2.tar.gz /opt/
  singularity.centos7/Makefile.h /opt/

%environment
SHELL=/bin/bash
export SHELL
export PATH="/usr/local/anaconda/bin:$PATH"
export AMUSE_DIR=/opt/amuse
export FLASH_DIR=/opt/FLASH4.6.2
export TORCH_DIR=/opt/torch
export PYTHONPATH="/opt/amuse/src:$PYTHONPATH"
module load mpi

%post
  echo "The post section is where you can install, and configure your container."
# Install the EPEL Repo
  yum search epel-release
  yum info epel-release
  yum -y install epel-release
# Do an Update and Upgrade
  yum -y update
  yum -y upgrade
# Install Useful Commands
  yum -y install sudo which nano wget bzip2 git cmake \
    ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1

# Install AMUSE Base Requirements
  yum -y install curl libcurl* devtoolset-8 gettext* zlib*
# Install OpenMPI3 and Append the Path Variable
  yum -y install openmpi3*
  export PATH=/usr/lib64/openmpi3/bin:$PATH
# Install HDF5 with OpenMPI3 Support
  yum -y install hdf5 hdf5-devel hdf5-openmpi3*
# Install NetCDF (No OpenMPI Support Due to Dependence on v1.10)
  yum -y install netcdf netcdf-devel \
    netcdf-cxx-devel netcdf-cxx-static netcdf-cxx \
    netcdf-fortran-devel netcdf-fortran-static netcdf-fortran
# Install FFTW
  yum -y install fftw fftw-devel fftw-libs*
# Install GSL, GMP & MPFR
  yum -y install gsl gsl-devel gmp gmp-devel mpfr mpfr-devel

# Install FLASH Requirements
  yum -y install hypre hypre-devel papi papi-devel papi-static libIDL libIDL-devel

# Install CUDA
  wget https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda-repo-rhel7-11-1-local-11.1.1_455.32.00-1.x86_64.rpm
  rpm -i cuda-repo-rhel7-11-1-local-11.1.1_455.32.00-1.x86_64.rpm
  yum clean all
  yum -y install nvidia-driver-latest-dkms cuda
  yum -y install cuda-drivers

# install anaconda
  if [ ! -d /usr/local/anaconda ]; then
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
      -O ~/anaconda.sh && \
      bash ~/anaconda.sh -b -p /usr/local/anaconda && \
      rm ~/anaconda.sh
  fi

# Set Anaconda Path
  export PATH="/usr/local/anaconda/bin:$PATH"

# install the bare minimum
  pip install numpy scipy astropy matplotlib
  env MPICC=/usr/lib64/openmpi3/bin/mpicc pip install mpi4py
  pip install h5py pytest docutils quilt gsl
  conda install gmp mpfr nose
  conda clean --tarballs

# Install AMUSE
  cd /opt
  git clone https://github.com/amusecode/amuse.git
  cd amuse
  ./configure --enable-cuda
  make framework
  make kepler.code
  make ph4.code
  make seba.code
  make smalln.code
  pip install rebound

# Install FLASH
  cd /opt
  tar -zxvf FLASH4.6.2.tar.gz
  cd FLASH4.6.2
  mkdir sites/singularity.centos7
  mv /opt/Makefile.h sites/singularity.centos7/Makefile.h
  ./setup -auto -3d Sedov --site=singularity.centos7
  #cd object
  #make

# Install Torch
  cd /opt
  git clone https://bitbucket.org/torch-sf/torch.git
  cd torch
  export AMUSE_DIR=/opt/amuse
  export FLASH_DIR=/opt/FLASH4.6.2
  export TORCH_DIR=/opt/torch
  yes | ./install.sh

# Install AMUSE FLASH_Worker
  export FLASH_DIR=/opt/FLASH4.6.2
  cd /opt/amuse/
  make flash.code
```

**Additional context**

**Comment by rnaranjoromero** [comment]
> **Describe the bug** Building `FLASH` with `AMUSE` results in an error despite: all other codes working perfectly; `FLASH` being in the correct directory thanks to `Torch`; and being in a sterile CentOS 7 environment.
> 
> **To Reproduce** See included `singularity` recipe file.
> 
> **Expected behavior** For the file to be found and the build to proceed.
> 
> **Logs**
> 
> ```
> + make flash.code
> /usr/local/anaconda/bin/python setup.py -v build_code --inplace --clean=yes --code-name=flash
> running build_code
> cleaning src/amuse/community/flash
> make -C src/amuse/community/flash clean
> make[1]: Entering directory `/opt/amuse/src/amuse/community/flash'
> rm -f -f *.so *.o *.pyc worker_code.cc worker_code.h #flash.par
> rm -f *~ flash_worker worker_code.f90
> make -C src clean
> make[2]: Entering directory `/opt/amuse/src/amuse/community/flash/src'
> rm -f *.o *.a
> make[2]: Leaving directory `/opt/amuse/src/amuse/community/flash/src'
> make[1]: Leaving directory `/opt/amuse/src/amuse/community/flash'
> building libraries and community codes
> build, for logging, see 'build.log'
> [18:28:04] building flash
> make -C src/amuse/community/flash all
> make[1]: Entering directory `/opt/amuse/src/amuse/community/flash'
> /opt/amuse/build.py --type=f90 interface.py FlashInterface -o worker_code.f90
> make -C src all
> make[2]: Entering directory `/opt/amuse/src/amuse/community/flash/src'
> mpif90 -g -O2 -fPIC -c -o test.o test.f90
> rm -f libflash.a
> ar ruv libflash.a test.o
> ar: creating libflash.a
> a - test.o
> ranlib libflash.a
> make[2]: Leaving directory `/opt/amuse/src/amuse/community/flash/src'
> mpif90 -g -O2 -fPIC -Isrc/FLASH4.6.2/object -c -o base_grid_interface.o base_grid_interface.F90
> base_grid_interface.F90:417.6:
> 
>   use Grid_interface, only : Grid_getBlkIndexLimits
>       1
> Fatal Error: Can't open module file 'grid_interface.mod' for reading at (1): No such file or directory
> make[1]: *** [base_grid_interface.o] Error 1
> make[1]: Leaving directory `/opt/amuse/src/amuse/community/flash'
> [18:28:05] building flash, failed, see 'build.log' for error log
> Environment variables
> ================================================================================
> AMUSE_DIR	/opt/amuse
> BOOSTLIBS	
> CC	gcc
> CFLAGS	-g -O2 -fPIC
> CUDA_LIBDIRS	-L/usr/local/cuda/lib -L/usr/local/cuda/lib64
> CUDA_LIBS	-lcuda  -L/usr/local/cuda/lib64 -lcudart
> CUDA_SDK	/TOBEFIXED
> CUDA_TK	/usr/local/cuda
> CXX	g++
> CXXFLAGS	-g -O2 -fPIC
> F90	gfortran
> FC	gfortran
> FFLAGS	-g -O2 -fPIC
> FFTW_FLAGS	
> FFTW_LIBS	-lfftw3 -lm   -lfftw3_threads
> FORTRAN	gfortran
> GSL_FLAGS	
> GSL_LIBS	-lgsl -lgslcblas -lm
> JAR	
> JAVA	/bin/java
> JAVAC	
> MPICC	mpicc
> MPICXX	mpicxx
> MPIF90	mpif90
> MUSE_PACKAGE_DIR	/opt/amuse
> OPENMP_CFLAGS	-fopenmp
> OPENMP_FCFLAGS	-fopenmp
> PYTHON	/usr/local/anaconda/bin/python
> SAPPORO_LIBS	-L/opt/amuse/lib/sapporo_light -lsapporo
> Community codes not built (because of errors):
> ================================================================================
>  * flash
> ================================================================================
> 0 out of 1 codes built, 0 out of 0 libraries built
> ```
> 
> **Environment (please complete the following information):**
> 
> ```
> # Torch Container                                             #
> # =====================                                             #
> #                                                                   #
> # This container offers a build of Torch of of CentOS 7             #
> # from the official Dockers containers.                             #
> #                                                                   #
> # singularity build centos8_torch.simg torch.recipe                 #
> #                                                                   #
> #####################################################################
> Bootstrap: docker
> From: centos:7
> 
> %help
>   Helpful information to come. This container is running the following:
>   - CentOS      7.0.0
>   - HDF5        1.8.12
>   - Hypre       2.11.2
>   - netCDF CXX  4.2.8
>   - netCDF C    4.3.3
>   - netCDF F90  4.2-16
>   - zlib        1.2.7
>   - FLASH       4.6.2
>   - OpenMPI3    3.1.3
> 
> %labels
>   CREATOR Joe Glaser
> 
> %runscript
> exec echo "The runscript is the containers default runtime command!"
> 
> %files
>   FLASH4.6.2.tar.gz /opt/
>   singularity.centos7/Makefile.h /opt/
> 
> %environment
> SHELL=/bin/bash
> export SHELL
> export PATH="/usr/local/anaconda/bin:$PATH"
> export AMUSE_DIR=/opt/amuse
> export FLASH_DIR=/opt/FLASH4.6.2
> export TORCH_DIR=/opt/torch
> export PYTHONPATH="/opt/amuse/src:$PYTHONPATH"
> module load mpi
> 
> %post
>   echo "The post section is where you can install, and configure your container."
> # Install the EPEL Repo
>   yum search epel-release
>   yum info epel-release
>   yum -y install epel-release
> # Do an Update and Upgrade
>   yum -y update
>   yum -y upgrade
> # Install Useful Commands
>   yum -y install sudo which nano wget bzip2 git cmake \
>     ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1
> 
> # Install AMUSE Base Requirements
>   yum -y install curl libcurl* devtoolset-8 gettext* zlib*
> # Install OpenMPI3 and Append the Path Variable
>   yum -y install openmpi3*
>   export PATH=/usr/lib64/openmpi3/bin:$PATH
> # Install HDF5 with OpenMPI3 Support
>   yum -y install hdf5 hdf5-devel hdf5-openmpi3*
> # Install NetCDF (No OpenMPI Support Due to Dependence on v1.10)
>   yum -y install netcdf netcdf-devel \
>     netcdf-cxx-devel netcdf-cxx-static netcdf-cxx \
>     netcdf-fortran-devel netcdf-fortran-static netcdf-fortran
> # Install FFTW
>   yum -y install fftw fftw-devel fftw-libs*
> # Install GSL, GMP & MPFR
>   yum -y install gsl gsl-devel gmp gmp-devel mpfr mpfr-devel
> 
> # Install FLASH Requirements
>   yum -y install hypre hypre-devel papi papi-devel papi-static libIDL libIDL-devel
> 
> # Install CUDA
>   wget https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda-repo-rhel7-11-1-local-11.1.1_455.32.00-1.x86_64.rpm
>   rpm -i cuda-repo-rhel7-11-1-local-11.1.1_455.32.00-1.x86_64.rpm
>   yum clean all
>   yum -y install nvidia-driver-latest-dkms cuda
>   yum -y install cuda-drivers
> 
> # install anaconda
>   if [ ! -d /usr/local/anaconda ]; then
>     wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
>       -O ~/anaconda.sh && \
>       bash ~/anaconda.sh -b -p /usr/local/anaconda && \
>       rm ~/anaconda.sh
>   fi
> 
> # Set Anaconda Path
>   export PATH="/usr/local/anaconda/bin:$PATH"
> 
> # install the bare minimum
>   pip install numpy scipy astropy matplotlib
>   env MPICC=/usr/lib64/openmpi3/bin/mpicc pip install mpi4py
>   pip install h5py pytest docutils quilt gsl
>   conda install gmp mpfr nose
>   conda clean --tarballs
> 
> # Install AMUSE
>   cd /opt
>   git clone https://github.com/amusecode/amuse.git
>   cd amuse
>   ./configure --enable-cuda
>   make framework
>   make kepler.code
>   make ph4.code
>   make seba.code
>   make smalln.code
>   pip install rebound
> 
> # Install FLASH
>   cd /opt
>   tar -zxvf FLASH4.6.2.tar.gz
>   cd FLASH4.6.2
>   mkdir sites/singularity.centos7
>   mv /opt/Makefile.h sites/singularity.centos7/Makefile.h
>   ./setup -auto -3d Sedov --site=singularity.centos7
>   #cd object
>   #make
> 
> # Install Torch
>   cd /opt
>   git clone https://bitbucket.org/torch-sf/torch.git
>   cd torch
>   export AMUSE_DIR=/opt/amuse
>   export FLASH_DIR=/opt/FLASH4.6.2
>   export TORCH_DIR=/opt/torch
>   yes | ./install.sh
> 
> # Install AMUSE FLASH_Worker
>   export FLASH_DIR=/opt/FLASH4.6.2
>   cd /opt/amuse/
>   make flash.code
> ```
> 
> **Additional context** Add any other context about the problem here.

Hi, you have to execute these lines after the flash ./setup command:
cd object
make
 
this error occurs because "use Grid_interface" expect a compiled object/module.
