### ISSUE TITLE
stellar_type units is incomplete: 

### ISSUE THREAD

**Issue by silviatoonen** [amusecode/amuse#702]
With TRES & SeBa in mind, it would be great to also have the stellar type 'brown dwarf'. Could this be stellar type be added to AMUSE's list? If it's not useful for others, I can adjust the AMUSE interface to SeBa, and have SeBa's stellar class of brown dwarf be considered a planet for AMUSE.

linked to issue #549  and #633

**Comment by rieder** [comment]
Done.
