### ISSUE TITLE
stellar_type unit brown dwarf

### ISSUE THREAD

**Issue by silviatoonen** [amusecode/amuse#704]
The stellar_type unit brown dwarf is not working for SeBa. 
Following SeBa I would expect a Brown dwarf for objects with masses between 0.0075 and 0.075. Below this a planet is (correctly) formed with stellar_type 18. Above it a low mass star with stellar type 1 is formed. However in the range 0.0075-0.075 a low mass star is formed, despite the existence of the BD class. 
related to #702

**Comment by rieder** [comment]
The relevant code for this is in SeBa's interface.cc (138-...):
```C
local int translate_stellar_type_to_int(stellar_type stp, const real mass) {

  switch (stp) {
    case Brown_Dwarf:
      return 19;
    case Main_Sequence: 
      if (mass<0.1) {
            return 0;
      }
      return 1;
```
So the stellar type internally in SeBa is not returning `Brown_Dwarf` then I guess?

**Comment by silviatoonen** [comment]
If I run SeBa by itself, it works fine. The stellar type brown dwarf is returned. Seems to be an amuse issue.

**Comment by rieder** [comment]
Hmm... did you update both SeBa and AMUSE to the latest git version and recompile?

**Comment by silviatoonen** [comment]
I pulled the latest version of AMUSE, assuming this contains the 'latest' version of SeBa (latest in the old repository), did a pip install, ran make. This is before the original but report.  Is it different on your system?
