### ISSUE TITLE
issue with evolve_model in Gadget-2

### ISSUE THREAD

**Issue by pasolar** [amusecode/amuse#705]
Hi,

- I made a gas cloud (with SPH particles) and used Gadget-2 to evolve, when I use some particles to evolve the system I have this problem.

       Traceback (most recent call last):
       File "/Users/paulo/Amuse-env/lib/python3.6/site-packages/amuse/rfi/core.py", line 120, in __call__
        dtype_to_result = self.interface.channel.recv_message(call_id, self.specification.id, handle_as_array)
       File "/Users/paulo/Amuse-env/lib/python3.6/site-packages/amuse/rfi/channel.py", line 1164, in recv_message
        raise exceptions.CodeException("Error in code: " + error_message)
      amuse.support.exceptions.CodeException: Error in code: no error message - code probably died, sorry.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "paulo_newsMerger.py", line 643, in <module>
         accret1, t1, num1, acc_rate1 = main(N,mtot,rvir,t,T,Rsink,dt,20,1|units.MSun)
           File "paulo_newsMerger.py", line 374, in main
            hydro.evolve_model(time)
           File "/Users/paulo/Amuse-env/lib/python3.6/site-packages/amuse/support/methods.py", line 168, in __call__
           result = self.method(*list_arguments, **keyword_arguments)
           File "/Users/paulo/Amuse-env/lib/python3.6/site-packages/amuse/support/methods.py", line 168, in __call__
           result = self.method(*list_arguments, **keyword_arguments)
        File "/Users/paulo/Amuse-env/lib/python3.6/site-packages/amuse/support/methods.py", line 168, in __call__
        result = self.method(*list_arguments, **keyword_arguments)
       File "/Users/paulo/Amuse-env/lib/python3.6/site-packages/amuse/support/methods.py", line 267, in __call__
        return self.method(*list_arguments, **keyword_arguments)
       File "/Users/paulo/Amuse-env/lib/python3.6/site-packages/amuse/rfi/core.py", line 123, in __call__
       raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}' ".format(self.specification.name, type(self.interface).__name__, ex)) 
      amuse.support.exceptions.CodeException: Exception when calling function 'evolve_model', of code 'Gadget2Interface', exception was 'Error in code: no error message - code probably died, sorry.'

-  I used redirection = "none" to be able to know what happened, they are the last 2 steps before the problem

       Begin Step 939, Time: 9.65308, Systemstep: 0.00165722
       domain decomposition... 
        NTopleaves= 106
       work-load balance=1   memory-balance=1
        domain decomposition done. 
        begin Peano-Hilbert order...
        Peano-Hilbert done.
        Start force computation...
        Tree construction.
        Tree construction done. 
         Begin tree force.
          tree is done.
           Start density computation...
            Start hydro-force computation...
            force computation done.
         Start time-stepping evaluation ...
 
        ---> number of timestep active gas particles:      1000 
       0) ---> number of timestep shrinked gas neighbors:       0 
       1.43741797656e+13 s
       mass+gas right after acc= 100011.0
       no density_threshold

       Begin Step 940, Time: 9.66343, Systemstep: 0.00140862
       domain decomposition... 
       NTopleaves= 106
       work-load balance=1   memory-balance=1
       domain decomposition done. 
       begin Peano-Hilbert order...
       Peano-Hilbert done.
       Start force computation...
       Tree construction.
       task 0: maximum number 1200 of tree-nodes reached.
       for particle 996
       task 0: endrun called with an error level of 1

- the initial condition for the gas cloud is:

1.  number SPH particles : 1000
2. time max : 1.0e6 yr
3. time step : 1000 or 10000 [yr]

-if I have 500 SPH particles the code run but this particles are very few. Do you have any idea what happened ?

Thanks in advance :), Cheers 

Paulo

**Comment by spzwart** [comment]
Dear Paulo,

It would help to see the script. But, simply stated, I thinkt hat your particle number is simply too small..
Almien
Simon

**Comment by pasolar** [comment]
Hi @spzwart 

- this is a fragment of my script 

      def gas(self):
		li_CPU= 10
		converter=nbody_system.nbody_to_si(self.Mtot,self.Rvir)
		gas=new_plummer_gas_model(self.N,convert_nbody=converter)
		hydro=Gadget2(converter, InitGasTemp=self.T ,EnergyFile = "energy.txt",redirection="none")
		hydro.parameters.begin_time = 0.0 | units.yr
		hydro.parameters.time_max = 2*self.t_end
		hydro.parameters.max_size_timestep = 0.5*self.dt
		return hydro,converter,gas`

      'while time<t_end:
		    #time = float(i)*dt
		    time += dt/2.
		    hydro.evolve_model(time)
		    print (hydro.model_time)`

- The problem is when I use a lot of SPH particles, for example, the code works fine when I use 500 SPH particles, but if I have 700 SPH particles, I have the problem, so the problem occurs when I evolve the script to 1.e6 [yr] but if I evolve to 1.e5 [yr] the code works fine with any number of particles

Cheers
Paulo

**Comment by rieder** [comment]
In SPH, 700 particles is a very small number. Remember that density etc are calculated by smoothing over 50 or so neighbouring particles. If you have few particles, this may be difficult to calculate correctly due to fragmentation. You should probably try with at least a factor 10 more particles.

**Comment by pasolar** [comment]
Hi @rieder 

Thanks for answer my question. I Know that I used few particles, so the problem is when I have a lot of particles, for example, the script breaks when I have 10.000 or 300.000 SPH particles, so more than 1000 SPH particles I have the problem when I evolve the code to 1.e6[yr], but if I evolve the code to 1.e5 [yr] the script work fine with 100.000 or more SPH particles.
Cheers
