### ISSUE TITLE
Fi can't handle dm_particles leaving box

### ISSUE THREAD

**Issue by MJCWilhelm** [amusecode/amuse#710]
**Describe the bug**
If a dm_particle were to leave the simulation box in Fi, any subsequent call that tries to access the dm_particles returns a -1 error (presumably meaning the particle can't be found), and the particle is not removed from AMUSE's particle set. This behavior is similar to what happens when gas_particles leave the box, but in that case a call to 'update_particle_set' removes the particle. That does not work for dm_particles. This function (as defined in Fi's interface.py) only mentions sph and gas particles, and no dm and star particles.

**To Reproduce**
Set up an instance of FI, add a dm_particle with a velocity such that it reaches the edge of the simulation box within a reasonable time, and evolve to that time. Afterwards, access the particle in AMUSE. I've included a small example.

[fi_dm_error.py.txt](https://github.com/amusecode/amuse/files/5679735/fi_dm_error.py.txt)

**Comment by ipelupessy** [comment]
yea, work around is to check whether particles leave the box in python (and/or make a bigger box...)

**Comment by ipelupessy** [comment]
I am closing this, as there is a workaround; feel free to reopen if really needed...
