### ISSUE TITLE
Obsolete, incomplete and otherwise non-working community code interfaces

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#721]
Some of the interfaces in AMUSE are obsolete, incomplete or otherwise not working.
These interfaces should be updated, completed or removed rather than linger on.

Some examples of incomplete interfaces:
- ~~ramses (nowhere near complete, see #503)~~
- krome (downloading fails)
- mocassin (building fails, test doesn't include evolve step)
- sphray (tests work but don't include the evolve step which fails)

Obsolete interfaces:
- adaptb (made obsolete by Brutus)
- octgrav (made obsolete by Bonsai)

**Comment by rieder** [comment]
As a rule, I think each community code should
- have a working example script
- have a test script that includes at the very least one evolve step and a test for each parameter

**Comment by ipelupessy** [comment]
krome is fixed now (downloads and builds)

**Comment by ipelupessy** [comment]
and tests also work ok

**Comment by ipelupessy** [comment]
I think sphray should work ok

**Comment by ipelupessy** [comment]
otherwise, an error report would be handy

**Comment by ipelupessy** [comment]
adaptb can probably be deleted
mocassin need to be checked
octgrav I am not sure (since I don't know well enough when bonsai works (ie which hardware) vs octgrav?)

**Comment by ipelupessy** [comment]
see above
