### ISSUE TITLE
Error downloading patches for mesa

### ISSUE THREAD

**Issue by yaronwe** [amusecode/amuse#725]
Hi,
When compiling amuse version 13.2.0 I got an error downloading the patches for the community code Mesa. As a resault the code didn't compile. I found out that if I edit one line in the file src/amuse/community/mesa/patch_files.py it fixes the issue.
The change is adding the letter "b" after the letter "r" in this line: version_re = re.compile(rb'(\d).(\d\d)')

**Comment by rieder** [comment]
Thanks for reporting!

Could you let us know what system you're using (which OS, python version etc)?
On my setup (macOS 11.1, python 3.9.1) Mesa seems to build alright without any changes.
