### ISSUE TITLE
Do not find community codes after an AMUSE development install

### ISSUE THREAD

**Issue by timroland** [amusecode/amuse#737]
Hello all, 

Maybe a silly question: I've just made a new update of my amuse framework and rebuilt all the codes. Everything worked well but I realize that I cannot import any community codes anymore... 
It just do not find the subdirectories in amuse/community/
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-64793f1c75ad> in <module>
      1 from amuse.units import units
----> 2 from amuse.community.ph4.interface import ph4

ModuleNotFoundError: No module named 'amuse.community.ph4'

```

PS: I used to rebuild AMUSE in developer mode the old-fashioned way with:
```
./configure --enable-cuda
make clean 
make DOWNLOAD_CODES=1
```
It may be obsolete now, isn't it ? I also test with the script ```setup.py develop_build```; everything is correctly built too but I still have the same problem.

I have missed something but I do not know what...

Many thanks in advance.

**Comment by MJCWilhelm** [comment]
The `setup.py develop_build` should be the correct method. Note that you can also do `make framework` for the framework, and then `make {CODE}.code` for individual codes if you don't want to wait for all codes to build. 

It's strange that it should not find the codes after an update, as far as I know the location of amuse is passed on before building the codes. Did you use `pip install -e .` to install amuse, or just add it to the python path? If the first, you could try to uninstall and reinstall amuse with pip.

**Comment by timroland** [comment]
Ok thanks, uninstall and reinstall was finally the best solution. I think I had 2 competitive version installed, one with just the framework and one in developer mode which was shadowed by the first one I suppose.
