### ISSUE TITLE
Multiple workers don't compile with gfortran 10.2.1

### ISSUE THREAD

**Issue by MJCWilhelm** [amusecode/amuse#738]
**Describe the bug**
When compiling a fortran community code [1] with gfortran 10.2.1, the compiler throws type mismatch errors on compiling the worker_code. This happens in various mpi functions. 

[1] I tried fi, sse, mmc and capreole, all had the same error. 

**To Reproduce**
Build a fortran community code using gfortran 10.2.1

**Logs**
One of the errors in the build.log (full log is attached):

worker_code.f90:429:26:

  417 |           call MPI_SEND(header_out, HEADER_SIZE, MPI_INTEGER, 0, 999, parent, ioerror);
      |                        2  
......
  429 |             call MPI_SEND(doubles_out, header_out(HEADER_DOUBLE_COUNT), MPI_REAL8, 0, 999, parent, ioerror)
      |                          1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).

[build.log](https://github.com/amusecode/amuse/files/6034765/build.log)

**Environment (please complete the following information):**
 - Fedora 33
 - gfortran 10.2.1

**Additional context**
I have run into gfortran type errors before when using a more recent version than others, so if I may speculate this is gfortran cracking down on improper type casting.

**Comment by rieder** [comment]
I haven't encountered this myself with gcc-10.2 on macOS, could be Linux specific?

**Comment by rieder** [comment]
Certainly gcc-10 has become more strict by default.
Options for a fix are:
- restore "old" behaviour with a flag (see recent fix for MESA)
- fix underlying source code by replacing offending types with the 'correct' ones.

The former is way easier and probably good enough.

**Comment by MJCWilhelm** [comment]
Yep that works, at least for fi! Shall I add it to the other fortran code makefiles as well? Will that also work with older gfortran versions?

**Comment by rieder** [comment]
(for reference: the fix for MESA was setting the flags `-fallow-invalid-boz -std=legacy` in MPIFC)

**Comment by rieder** [comment]
Probably setting `-fallow-argument-mismatch` would be enough. Better to not overdo it.

**Comment by rieder** [comment]
Not sure about other compiler versions. We'll have to test.

**Comment by ipelupessy** [comment]
was this fixed ok? Note that the worker_code.f90 is generated and should be fixed by fixing the source code to not trigger the warning...if its the community code than the -fallow-argument-mismatch may be acceptable...
(I have fixed some errors already, but apparently not all)

**Comment by ipelupessy** [comment]
and also note that it may be the MPI implementation which may be at fault (ie its overloading not correctly), which MPI were you using @MJCWilhelm ?? if its the MPI that is at fault, you should use -fallow... flag in the meantime... (you can also do this globally at configure time: configure FCFLAGS=-g- O2 -fallow-argument-mismatch etc)

**Comment by ipelupessy** [comment]
closing as multiple fixes are mentioned
