### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by gravitas21** [amusecode/amuse#743]
I followed the installation steps mentioned on the website and installed all the required pre-requisites. But the installation failed and showed the following message at the end:

> Exception: No succesful builds detected. Aborting.
    ----------------------------------------
    ERROR: Failed building wheel for amuse-galactics
  Failed to build amuse-galactics
  ERROR: Could not build wheels for amuse-galactics which use PEP 517 and cannot be installed directly
  ----------------------------------------
>WARNING: Discarding https://files.pythonhosted.org/packages/7b/18/ca4dc004edcfeb8d2326bacab8ae3926e76ecbe2d43f80b061d56ad5c847/amuse-12.0.0.post1.tar.gz#sha256=d8108d37ed7556d2f2f2c1b0b68a311a468961e2f31ffbde3e498e9c025c6149 (from https://pypi.org/simple/amuse/). Command errored out with exit status 1: /home/dell/Amuse-env/bin/python3 /home/dell/Amuse-env/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5k0lmz3w/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'amuse-framework>=12.0.0rc3' 'amuse-athena>=12.0.0rc3' 'amuse-bhtree>=12.0.0rc3' 'amuse-brutus>=12.0.0rc3' 'amuse-bse>=12.0.0rc3' 'amuse-capreole>=12.0.0rc3' 'amuse-evtwin>=12.0.0rc3' 'amuse-fastkick>=12.0.0rc3' 'amuse-fi>=12.0.0rc3' 'amuse-fractalcluster>=12.0.0rc3' 'amuse-gadget2>=12.0.0rc3' 'amuse-galactics>=12.0.0rc3' 'amuse-galaxia>=12.0.0rc3' 'amuse-halogen>=12.0.0rc3' 'amuse-hermite>=12.0.0rc3' 'amuse-hop>=12.0.0rc3' 'amuse-huayno>=12.0.0rc3' 'amuse-kepler>=12.0.0rc3' 'amuse-kepler-orbiters>=12.0.0rc3' 'amuse-mameclot>=12.0.0rc3' 'amuse-mercury>=12.0.0rc3' 'amuse-mmams>=12.0.0rc3' 'amuse-ph4>=12.0.0rc3' 'amuse-seba>=12.0.0rc3' 'amuse-secularmultiple>=12.0.0rc3' 'amuse-simplex>=12.0.0rc3' 'amuse-smalln>=12.0.0rc3' 'amuse-sphray>=12.0.0rc3' 'amuse-sse>=12.0.0rc3' 'amuse-twobody>=12.0.0rc3' Check the logs for full command output.
  Using cached amuse-12.0.0.tar.gz (1.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/dell/Amuse-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k3puvjtk/amuse_f1b0a544f2d6426f818d16d9c98fb0ea/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k3puvjtk/amuse_f1b0a544f2d6426f818d16d9c98fb0ea/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z1a52j60
         cwd: /tmp/pip-install-k3puvjtk/amuse_f1b0a544f2d6426f818d16d9c98fb0ea/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k3puvjtk/amuse_f1b0a544f2d6426f818d16d9c98fb0ea/setup.py", line 2, in <module>
        from support.version import version, main_version
    ModuleNotFoundError: No module named 'support'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d5/32/fa654727641a271b367bd48b82338c8233c5b94f2ff4f40f4e3ae86cb077/amuse-12.0.0.tar.gz#sha256=bfee88e3f1ae5cabb6b1ac9d186dcdb26425915b49682164665e61523b94ac44 (from https://pypi.org/simple/amuse/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement amuse
ERROR: No matching distribution found for amuse
 ------------------------------

This issue remains for amuse-galactics whether I do it on the Amuse-env environment or in a conda virtual environment.

**Comment by gravitas21** [comment]
UPDATE: The pip installation issue still remains. But when I tried to install via the source code according to https://github.com/amusecode/amuse/blob/master/doc/install/install-ubuntu-1804-virtualenv-python3.rst for **Ubuntu 20.04**, I got the following message:
>Community codes not built (because of errors):
================================================================================
 * distributed
 * flash
 * krome
 * mocassin
 * rebound
Optional builds failed, need special libraries:
 * asterisk - java
 * fastkick - gpu
 * fi - gl, periodic_gl
 * hacs64 - gpu
 * higpus - gpu
 * huayno - cl, cl, cl, cl, cl, mp.so, mp.so, mp.so
 * mi6 - gpu
 * ph4 - gpu
 * phigrape - gl, grape, gl_gpu, gpu
Optional builds failed, need CUDA/GPU libraries:
 * sapporo_light
 * bonsai
 * bonsai2
 * etics
 * octgrav
 * pikachu
Optional builds failed, need additional python packages:
 * tupan
================================================================================
Community codes built
================================================================================
* aarsethzare
* adaptb
* asterisk
* athena (mhd,scalar,selfgrav)
* bhtree
* brutus
* bse
* capreole (mpi)
* evtwin
* fastkick
* fi (mp,mp,map,map,map_mp,map_mp,periodic)
* fractalcluster
* gadget2 (periodic,normal,periodic_nogravity,nogravity)
* galactics
* galaxia
* hacs64
* halogen
* hermite
* higpus
* hop
* huayno (mp,mp,mp)
* kepler
* kepler_orbiters
* mameclot
* mercury
* mi6
* mikkola
* mmams
* mmc
* mobse
* mosse
* mpiamrvac (acc,2d,2dacc,1dacc,1d)
* nbody6xx
* petar
* ph4
* phigrape (mpi)
* ramses (1d,2d)
* sakura
* seba
* secularmultiple
* sei
* simplex
* smalln
* sphray
* sse
* symple
* twobody
================================================================================
47 out of 52 codes built, 5 out of 6 libraries built


I intend to use REBOUND specifically, is this an open issue being solved? Also, can I safely regard the rest of the code to have been installed properly now? I do not need the CUDA/GPU dependent libraries.

**Comment by spzwart** [comment]
rebound has to be downloaded separately by
make rebound.code
you may have to set something like
DOWNLOADS_CODES=1
it looks like your installation will be okay. you can install cuda support
if you like,but reboud is not gpu enabled.
Ph4, Huayno, and nbody6++gpu and several other codes are.

good luck,
simon

**Comment by gravitas21** [comment]
@rieder Hello, I was not trying to install any specific version actually. Just did the generic `pip install amuse`.
The pip install automatically went up to AMUSE 12.0 after trying newer versions 12.1, 12.2, 12.3 first. Then it gave the above pip error after it failed at AMUSE 12.0.

**Comment by rieder** [comment]
> The pip install automatically went up to AMUSE 12.0 after trying newer versions 12.1, 12.2, 12.3 starting at 13.0 first. Then it gave the above pip error after it failed at AMUSE 12.0.

This is very surprising, and it should definitely not happen. Pip should never automatically try older versions and I don't see this behaviour anywhere else...
Also, 13.0 is not the latest version, 2021.3.0 is.

**Comment by gravitas21** [comment]
The source code installation worked though as @simon pointed out. Thank you for the reply. For rebound, I tried the command `make rebound.code DOWNLOAD_CODES=1` inside the amuse directory (made by git clone) and got the following message:
> /home/dell/anaconda3/envs/amuse/bin/python setup.py -v build_code --inplace --clean=yes --code-name=rebound
running build_code
cleaning src/amuse/community/rebound
make -C src/amuse/community/rebound clean
make[1]: Entering directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
rm -f -f *.so *.o *.pyc worker_code.cc worker_code.h 
rm -f *~ rebound_worker worker_code.cc
rm -f -Rf src/rebound/src/*.o
rm -f -Rf src/rebound/src/*.so
rm -f -Rf src/librebound.a
make -C src/rebound clean
make[2]: Entering directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
make[2]: *** src/rebound: No such file or directory.  Stop.
make[2]: Leaving directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
make[1]: [Makefile:75: clean] Error 2 (ignored)
make[1]: Leaving directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
building libraries and community codes
build, for logging, see 'build.log'
[17:24:41] building rebound
make -C src/amuse/community/rebound all
make[1]: Entering directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
amusifier --type=c interface.py ReboundInterface -o worker_code.cc
amusifier --type=h interface.py  -i amuse.support.codes.stopping_conditions.StoppingConditionInterface ReboundInterface -o worker_code.h
make -C . download
make[2]: Entering directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
rm -f -Rf .pc
rm -f -Rf src
mkdir src
/home/dell/anaconda3/envs/amuse/bin/python ./download.py
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
mv: cannot stat 'rebound-31d117bdc92182073d0941c331f76e95f515bfc6': No such file or directory
downloading version 31d117bdc92182073d0941c331f76e95f515bfc6 from https://github.com/hannorein/rebound/archive/31d117bdc92182073d0941c331f76e95f515bfc6.zip to 31d117bdc92182073d0941c331f76e95f515bfc6.zip
downloading finished
unpacking 31d117bdc92182073d0941c331f76e95f515bfc6.zip
done
/home/dell/anaconda3/envs/amuse/bin/python ./patch_files.py
checking if quilt is installed ...  no
applying patches to source code
make[2]: Leaving directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
make -C src/rebound all CC=gcc
make[2]: Entering directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
make[2]: *** src/rebound: No such file or directory.  Stop.
make[2]: Leaving directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
make[1]: *** [Makefile:88: src/librebound.a] Error 2
make[1]: Leaving directory '/home/dell/Documents/amuse/src/amuse/community/rebound'
[17:24:45] building rebound, failed, see 'build.log' for error log
Environment variables
================================================================================
AMUSE_DIR	/home/dell/Documents/amuse
BOOSTLIBS	
CC	gcc
CFLAGS	-g -O2 -fPIC
CUDART_LIBS	-lnocudart
CUDA_LIBDIRS	-L/NOCUDACONFIGURED/lib -LNOCUDACONFIGURED/lib64
CUDA_LIBS	-lnocuda
CUDA_SDK	/NOCUDACONFIGURED
CUDA_TK	/NOCUDACONFIGURED
CXX	g++
CXXFLAGS	-g -O2 -fPIC
F90	gfortran
FC	gfortran
FFLAGS	-g -O2 -fPIC
FFTW_FLAGS	
FFTW_LIBS	-lfftw3 -lfftw3_threads
FORTRAN	gfortran
GSL_FLAGS	
GSL_LIBS	-lgsl -lgslcblas -lm
JAR	
JAVA	/usr/bin/java
JAVAC	
MPICC	mpicc
MPICXX	mpicxx
MPIF90	mpif90
MUSE_PACKAGE_DIR	/home/dell/Documents/amuse
OPENMP_CFLAGS	-fopenmp
OPENMP_FCFLAGS	-fopenmp
PYTHON	/home/dell/anaconda3/envs/amuse/bin/python
SAPPORO_LIBS	-L/home/dell/Documents/amuse/lib/sapporo_light -lsapporo
Community codes not built (because of errors):
================================================================================
 * rebound
================================================================================
0 out of 1 codes built, 0 out of 0 libraries built
Traceback (most recent call last):
  File "/home/dell/Documents/amuse/setup.py", line 74, in <module>
    setup(
  File "/home/dell/anaconda3/envs/amuse/lib/python3.9/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/dell/anaconda3/envs/amuse/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/dell/anaconda3/envs/amuse/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/dell/anaconda3/envs/amuse/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dell/Documents/amuse/support/setup_codes.py", line 1214, in run
    BuildCodes.run(self)
  File "/home/dell/Documents/amuse/support/setup_codes.py", line 1093, in run
    raise Exception("No succesful builds detected. Aborting.")
Exception: No succesful builds detected. Aborting.
make: *** [Makefile:124: rebound.code] Error 1
-------------------------------

Am I missing something? Do I need to do `pip install rebound` separately as well?
