### ISSUE TITLE
add detection of lapack and blas to configure

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#748]
**Is your feature request related to a problem? Please describe.**
galaxia and new mesa are using lapack and blas, these are normally found ok, but could be added to configure (m4 scripts available)

**Describe alternatives you've considered**
leaving as is, since it doesn't seem to be a big problem, though that is not true since galaxia install sometimes fails
because of this

**Comment by rieder** [comment]
Yes we should add these.

**Comment by ipelupessy** [comment]
well...galaxia which is part of the core set of amuse packages depends on it..

**Comment by ipelupessy** [comment]
but ok with it to change the error into a warning

**Comment by rieder** [comment]
Done, it's now a warning.
