### ISSUE TITLE
Effective EOS in SPH code

### ISSUE THREAD

**Issue by PaoloSuin** [amusecode/amuse#754]
Is there a way to implement an effective EOS using an SPH code (Fi or Gadget)? I am trying to get something like Dale et al (2015), with an density dependent adiabatic index such that 

gamma = 0.75 if rho < rho1
gamma = 1 if (rho > rho1 and rho < rho2)
ecc...

**Comment by spzwart** [comment]
Dear Paolo,

In principle: yes. But you will have to hack the source code to do that.
We also have Phantom now in AMUSE, which is a more modular SPH code.
We consider incorporating other codes that do already have such options, but at the moment it is probaby easiest to hack the source code, recompile and run.

Simon

**Comment by PaoloSuin** [comment]
Thank you for your fast reply.
I'll try as you say
Plus, if I wanted to set the critical density rho1 as parameter for the hydro code, to be set from the Amuse script with the other hydro_code.parameters, is there a documentation or tutorial to which I can refer to?

**Comment by spzwart** [comment]
Dear Paolo,

I would go by the book: Astrophysical Recipes: https://iopscience.iop.org/book/978-0-7503-1320-9
if you download it from your university's domain the book is free.
Maybe you like to make your new EOS an option in the code. We normally do not do this, but it may be an interesting addition to the particular code. In that case, you may want to make an interface function to change EOS, and after testing, upload it to the AMUSE git repository.
Good luck,
Simon

**Comment by PaoloSuin** [comment]
At the moment I am looking for a personal usage solution, but I''ll give it an attempt once implemented.
Many thanks for your precious help
