### ISSUE TITLE
Crash caused by get_convective_envelope_radius

### ISSUE THREAD

**Issue by igifford** [amusecode/amuse#767]
Hi!

**Describe the bug**
This is a crash that occurs 'randomly' based off of a sequence of binaries I'm generating. Depending on the seed I'm using, the crash will occur at a different numbered binary and I may not run into the problem depending on where that binary is.

**To Reproduce**
This problem seems to be specific to the script I'm executing - 
[dwd_serial.txt](https://github.com/amusecode/amuse/files/6510493/dwd_serial.txt)

Here's a pickle file that pertains to a sequence that produces the event. This is saved up to two binaries prior to the error -
[random_state.txt](https://github.com/amusecode/amuse/files/6510515/random_state.txt)

The steps to running the code and reproducing the error are as follows -

mkdir _rundata.1
mkdir _plots
cp dwd_serial.txt dwd_serial.py
cp random_state.txt _rundata.1/random_state.p
python3 dwd_serial.py 1 5 

**Expected behavior**
I didn't expect any exceptions to be raised regarding an evolutionary step in the binaries I'm generating.

**Environment (please complete the following information):**
 - OS and version: [Ubuntu 20.04.2 LTS Linux]
 - Compiler: [gcc-7]
 - Python version: [3.8.5]
 - Numpy version:[1.19.4]
 - AMUSE and SeBa versions:[13.2.0]

**Additional context**
For context, A colleague and I are utilizing SeBa to generate and evolve binary stars to observe the initial conditions of systems that result in type Ia supernovae.
We'll generate and evolve ~ 100,000 binaries each on 10 different nodes. Jobs will start to fail shortly after submitting them. Eventually all jobs will fail. If we're doing small runs (~1,000 binaries), we generally won't run into this error.
Also, attached is the error I receive - 
[get_conv_error.txt](https://github.com/amusecode/amuse/files/6510610/get_conv_error.txt)

Thanks for your time!

**Comment by spzwart** [comment]
Thanks for the big report.

Well, I guess that trying to get th
*e radius of the convective envelope of a white dwarfs is a little extreme.
*

*SeBa, however, should not crash on this. And, I am sure this has been
tested many many times: I'll have a look.*

*But then, looking at your script, I would recommend to read the AMUSE
book: Astrophysical Recipes.*
*In particular to prevent you from doing a lot of work that we already did
for you, like*

*make_Kroupa_mass_function which generates the mass function you
implemented yourself.*

*Maybe also get your hands on a python style file manual.*
