### ISSUE TITLE
Timestep of sph particles in Fi and Gadget2?

### ISSUE THREAD

**Issue by ReinosoB** [amusecode/amuse#768]
How can I retrieve the timestep for each sph particle in both Fi and Gadget2?

**Comment by ipelupessy** [comment]
that is not possible at the moment.

**Comment by ReinosoB** [comment]
Hi @ipelupessy, I have been trying to include a new function to retrieve the timestep of every particle in Fi. I managed
to succesfully compile the code and get the timesteps from my python script but it would be useful if someone else can
check the implementation, maybe should I describe the modifications I made?

**Comment by ipelupessy** [comment]
@ReinosoB sorry for the late reaction, missed this: if its still an issue you could make a pull request  where we can take a look at it (even if we don't merge).

In any case will close this issue.
