### ISSUE TITLE
AMUSE installation problem on Mac

### ISSUE THREAD

**Issue by astro-alice** [amusecode/amuse#773]
Hello!
I am having difficulty figuring out why amuse won't install via pip install amuse.
I am an undergrad working with @JPGlaser this summer in a REU!

> (base) MacBook-Pro-3:~ palmerinfamily$ pip install amuse
Collecting amuse
  Using cached amuse-2021.6.0.tar.gz (297 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/palmerinfamily/opt/miniconda3/bin/python /Users/palmerinfamily/opt/miniconda3/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-6hw9vwdm/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'amuse-framework>=13.0.0[MPI]' 'amuse-athena>=13.0.0' 'amuse-bhtree>=13.0.0' 'amuse-brutus>=13.0.0' 'amuse-bse>=13.0.0' 'amuse-capreole>=13.0.0' 'amuse-evtwin>=13.0.0' 'amuse-fastkick>=13.0.0' 'amuse-fi>=13.0.0' 'amuse-fractalcluster>=13.0.0' 'amuse-gadget2>=13.0.0' 'amuse-galactics>=13.0.0' 'amuse-galaxia>=13.0.0' 'amuse-halogen>=13.0.0' 'amuse-hermite>=13.0.0' 'amuse-hop>=13.0.0' 'amuse-huayno>=13.0.0' 'amuse-kepler>=13.0.0' 'amuse-kepler-orbiters>=13.0.0' 'amuse-mameclot>=13.0.0' 'amuse-mercury>=13.0.0' 'amuse-mmams>=13.0.0' 'amuse-ph4>=13.0.0' 'amuse-seba>=13.0.0' 'amuse-secularmultiple>=13.0.0' 'amuse-smalln>=13.0.0' 'amuse-sphray>=13.0.0' 'amuse-sse>=13.0.0' 'amuse-twobody>=13.0.0'
       cwd: None
  Complete output (155 lines):
  DEPRECATION: Extras after version '>=13.0.0[MPI]'. pip 21.0 will remove support for this functionality. A possible replacement is moving the extras before version specifiers.
  Collecting amuse-athena>=13.0.0
    Using cached amuse-athena-2021.6.0.tar.gz (1.0 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/palmerinfamily/opt/miniconda3/bin/python /Users/palmerinfamily/opt/miniconda3/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-szj5ihxh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel amuse-framework
         cwd: None
    Complete output (144 lines):
    Collecting amuse-framework
      Using cached amuse-framework-2021.6.0.tar.gz (901 kB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'done'
    Collecting setuptools
      Using cached setuptools-57.0.0-py3-none-any.whl (821 kB)
    Collecting wheel
      Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
    Collecting docutils>=0.6
      Using cached docutils-0.17.1-py2.py3-none-any.whl (575 kB)
    Collecting h5py>=1.1.0
      Using cached h5py-3.3.0-cp39-cp39-macosx_10_9_x86_64.whl (3.0 MB)
    Collecting numpy>=1.2.2
      Using cached numpy-1.21.0-cp39-cp39-macosx_10_9_x86_64.whl (16.9 MB)
    Collecting pip>=19.0.0
      Using cached pip-21.1.2-py3-none-any.whl (1.5 MB)
    Collecting pytest>=4.0
      Using cached pytest-6.2.4-py3-none-any.whl (280 kB)
    Collecting attrs>=19.2.0
      Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
    Collecting iniconfig
      Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
    Collecting packaging
      Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
    Collecting pluggy<1.0.0a1,>=0.12
      Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
    Collecting py>=1.8.2
      Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
    Collecting pyparsing>=2.0.2
      Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
    Collecting toml
      Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
    Building wheels for collected packages: amuse-framework
      Building wheel for amuse-framework (PEP 517): started
      Building wheel for amuse-framework (PEP 517): finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/palmerinfamily/opt/miniconda3/bin/python /Users/palmerinfamily/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/tmpilkrgt7i
           cwd: /private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-install-4u_vb9yq/amuse-framework_c2a845d18fb0485d84312f393db3b483
      Complete output (97 lines):
      running bdist_wheel
      running build
      running configure_codes
      get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
      Warning: Can't read registry to find the necessary compiler setting
      Make sure that Python modules winreg, win32api or win32con are installed.
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize NAGFCompiler
      customize AbsoftFCompiler
      Could not locate executable f90
      Could not locate executable f77
      customize IBMFCompiler
      Could not locate executable xlf90
      Could not locate executable xlf
      customize IntelFCompiler
      Could not locate executable ifort
      Could not locate executable ifc
      customize GnuFCompiler
      Could not locate executable g77
      customize G95FCompiler
      Could not locate executable g95
      customize PGroupFCompiler
      Could not locate executable pgfortran
      don't know how to compile Fortran code on platform 'posix'
      Running configure for AMUSE
      config.mk not generated; output of configure:
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking for g++... g++
      checking whether we are using the GNU C++ compiler... yes
      checking whether g++ accepts -g... yes
      checking for gfortran... no
      checking for g95... no
      checking for xlf95... no
      checking for f95... no
      checking for fort... no
      checking for ifort... no
      checking for ifc... no
      checking for efc... no
      checking for pgfortran... no
      checking for pgf95... no
      checking for lf95... no
      checking for ftn... no
      checking for nagfor... no
      checking whether we are using the GNU Fortran compiler... no
      checking whether  accepts -g... no
      configure: error: No fortran compiler found, please set the FC flag
  
      Traceback (most recent call last):
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-b05me6pr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 221, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-b05me6pr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-b05me6pr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-b05me6pr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 54, in <module>
          setup(
        File "/private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-b05me6pr/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-b05me6pr/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/palmerinfamily/opt/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-install-4u_vb9yq/amuse-framework_c2a845d18fb0485d84312f393db3b483/support/setup_codes.py", line 1149, in run
          raise Exception("configure failed")
      Exception: configure failed
      ----------------------------------------
      ERROR: Failed building wheel for amuse-framework
    Failed to build amuse-framework
    ERROR: Could not build wheels for amuse-framework which use PEP 517 and cannot be installed directly
    ----------------------------------------
  

> ERROR: Command errored out with exit status 1: /Users/palmerinfamily/opt/miniconda3/bin/python /Users/palmerinfamily/opt/miniconda3/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-szj5ihxh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel amuse-framework Check the logs for full command output.

  ----------------------------------------

> ERROR: Command errored out with exit status 1: /Users/palmerinfamily/opt/miniconda3/bin/python /Users/palmerinfamily/opt/miniconda3/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w1/4hxn82w15hs95vxmkt8jrn800000gn/T/pip-build-env-6hw9vwdm/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'amuse-framework>=13.0.0[MPI]' 'amuse-athena>=13.0.0' 'amuse-bhtree>=13.0.0' 'amuse-brutus>=13.0.0' 'amuse-bse>=13.0.0' 'amuse-capreole>=13.0.0' 'amuse-evtwin>=13.0.0' 'amuse-fastkick>=13.0.0' 'amuse-fi>=13.0.0' 'amuse-fractalcluster>=13.0.0' 'amuse-gadget2>=13.0.0' 'amuse-galactics>=13.0.0' 'amuse-galaxia>=13.0.0' 'amuse-halogen>=13.0.0' 'amuse-hermite>=13.0.0' 'amuse-hop>=13.0.0' 'amuse-huayno>=13.0.0' 'amuse-kepler>=13.0.0' 'amuse-kepler-orbiters>=13.0.0' 'amuse-mameclot>=13.0.0' 'amuse-mercury>=13.0.0' 'amuse-mmams>=13.0.0' 'amuse-ph4>=13.0.0' 'amuse-seba>=13.0.0' 'amuse-secularmultiple>=13.0.0' 'amuse-smalln>=13.0.0' 'amuse-sphray>=13.0.0' 'amuse-sse>=13.0.0' 'amuse-twobody>=13.0.0' Check the logs for full command output.

**Comment by JPGlaser** [comment]
@stevemcmillan  and @rieder , you might have some insight regarding this! I don't have a Mac device running around and nabbing the ISO from the Mac for a virtual box is seeming a tad tricky these days.

~ Joe G.

**Comment by rieder** [comment]
Hi - sorry for the delay!
It looks like no fortran compiler is available (`configure: error: No fortran compiler found, please set the FC flag`), this is a requirement for installing AMUSE.

**Comment by astro-alice** [comment]
Hello! - no worries!
I was able to install gfortran, I'm not sure if it is the same, and got this error instead: 
<error: Cannot compile MPI programs. Check your configuration!!!>

**Comment by astro-alice** [comment]
Hello! - its no worries!
I think I was able to correct everything, and I installed fortran and openmpi, but now I get this error:
`ERROR: Failed building wheel for amuse-simplex
  Failed to build amuse-athena amuse-bhtree amuse-evtwin amuse-galactics amuse-hop amuse-mmams amuse-simplex
  ERROR: Could not build wheels for amuse-athena, amuse-bhtree, amuse-evtwin, amuse-galactics, amuse-hop, amuse-mmams, amuse-simplex which use PEP 517 and cannot be installed directly`

**Comment by rieder** [comment]
Could you try installing one of these manually, e.g. `pip install -v amuse-bhtree`? This may give a bit more info on what is going wrong.

**Comment by astro-alice** [comment]
I receive this, `ERROR: Failed building wheel for amuse-bhtree
Failed to build amuse-bhtree
ERROR: Could not build wheels for amuse-bhtree which use PEP 517 and cannot be installed directly`

**Comment by rieder** [comment]
Hmm, I thought with `-v` you would get a little more output.
