### ISSUE TITLE
Build fails in several routines and codes when 'python' is not python 3.x

### ISSUE THREAD

**Issue by DavidJJansen** [amusecode/amuse#775]
**Describe the bug**
Even when starting the install using: python3 setup.py build, the build.log will show in several places that 'python' is called, leading to failures if python without a version number is actually python 2. 
Of course this issue will not show up if the advise is followed to work with a virtualenv.

Another solution seems to be: export PYTHON=/usr/bin/python3 although I haven't tested that this is used properly everywhere

OS: Redhat 7, Ubuntu 18.04 (both have python 2 as default version)

**Comment by rieder** [comment]
> Another solution seems to be: export PYTHON=/usr/bin/python3

Indeed this is the solution (this is mentioned in ./configure)

**Comment by ipelupessy** [comment]
I think the configure should pick up and prefer python3 when present (well at least it does on my machine....), and this is propagated in most places..can you give an example where python is called?

**Comment by DavidJJansen** [comment]
I think I did something silly that time: I can reproduce the problem 
when starting the build with 'python3 setup.py build' (which is not the 
way mentioned in the documentation); starting with ./configure avoids 
the problem. So not a bug, just me being confused by building other 
python projects.

**Comment by ipelupessy** [comment]
ok..(it would be better ofcourse if we also follow expected behaviour..)
