### ISSUE TITLE
Wrong star mass when mass limits for Kroupa IMF are small

### ISSUE THREAD

**Issue by kyliow** [amusecode/amuse#777]
Hello,

I think this is a bug unless I'm not understanding the code correctly. When I sample the Kroupa IMF using small lower and upper mass limits smaller than 0.5 MSun, the resultant star masses are not bound by the mass limits.

To illustrate my point, simply set upper and lower mass limits the same. The resultant star mass should in theory be the same as the mass limits:
```
>>> from amuse.units import units
>>> from amuse.ic.brokenimf import new_kroupa_mass_distribution
>>>
>>> new_kroupa_mass_distribution(1, 10|units.MSun, 10|units.MSun)          
quantity<[10.0] MSun>
>>> new_kroupa_mass_distribution(1, 1|units.MSun, 1|units.MSun)          
quantity<[1.0] MSun>
>>> new_kroupa_mass_distribution(1, 0.5|units.MSun, 0.5|units.MSun)  
quantity<[0.5] MSun>
```

But when the limits are less than 0.5 MSun:
```
>>> new_kroupa_mass_distribution(1, 0.4|units.MSun, 0.4|units.MSun)
quantity<[0.404887907559] MSun>
>>> new_kroupa_mass_distribution(1, 0.1|units.MSun, 0.1|units.MSun)
quantity<[0.106224063564] MSun>
>>> new_kroupa_mass_distribution(1, 0.01|units.MSun, 0.01|units.MSun)
quantity<[0.0251819560899] MSun>
```

When both limits are unequal, we expect the resultant star mass is between the limits. The below extreme example works:
```
>>> new_kroupa_mass_distribution(1, 1|units.MSun, 1.000001|units.MSun)
quantity<[1.00000028211] MSun>
```

But this doesn't work:
```
>>> new_kroupa_mass_distribution(1, 0.01|units.MSun, 0.05|units.MSun)
quantity<[0.061726538089] MSun>
```

The code I have in my local `amuse.ic.brokenimf` is the updated one.

Please let me know if I have overlooked anything. Thanks!

**Comment by kyliow** [comment]
In `amuse.ic.brokenimf`,  simply change 
- line 56 from `... enumerate(self.mass_boundaries):` to `... enumerate(self.mass_boundaries[1:]:`, and
- line 57 from `if ... > ...` to `if ... >= ...` 
should fix the bug.

The code now works as expected:
```
>>> new_kroupa_mass_distribution(1, 1|units.MSun, 1|units.MSun)          
quantity<[1.0] MSun>
>>> new_kroupa_mass_distribution(1, 0.4|units.MSun, 0.4|units.MSun)          
quantity<[0.4] MSun>
>>> new_kroupa_mass_distribution(1, 0.01|units.MSun, 0.01|units.MSun)
quantity<[0.01] MSun>
>>>
>>> new_kroupa_mass_distribution(1, 0.01|units.MSun, 0.02|units.MSun)
quantity<[0.0179292001441] MSun>
```

**Comment by rieder** [comment]
Confirmed with test, now fixed.
