### ISSUE TITLE
requirements for developer sphinx building not included?

### ISSUE THREAD

**Issue by teuben** [amusecode/amuse#779]
I don't see anywhere the needed sphinx modules needed to "make html" locally in developer mode.     I read in #590 that you only build on readthedocs....  but recently they updated to sphinx 4.1, which broke my NEMO build. So I tried building the AMUSE html tree, which eventually fails for me with 
     Could not import extension matplotlib.sphinxext.only_directives (exception: No module named 'matplotlib.sphinxext.only_directives'). That's probably an easy fix, but I'm also curious if AMUSE builds fine with the new sphinx 4.

For reference, my requirements.txt for sphinx building (in NEMO) is, but that clearly can use an update too:

sphinx>=2.0
sphinx-automodapi==0.12
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
sphinx-rtd-theme==0.5.2

**Comment by teuben** [comment]
On the sphinx 4.1.0 error, this appears to be an upstream error:  https://github.com/sphinx-doc/sphinx/issues/9434

**Comment by rieder** [comment]
Hi Peter - I had to do some fixes (see #781) but it does now build for me.
There may be additional requirements that I'm missing so I'll test on a 'cleaner' machine before merging/closing the issue.

**Comment by teuben** [comment]
I confirm, your doc-fixes branch works for me too now.   I'm curious if any changes you made on the amusecode site will show up on readthedocs. Mine still are not.
