### ISSUE TITLE
Krome code cannot be downloaded

### ISSUE THREAD

**Issue by DavidJJansen** [amusecode/amuse#789]
Download of the Krome code fails during the build. Apparently, the download location has changed, and the code in the makefile, which sets a variable URL to the output of a wget command, results in an empty variable (which results in a wget command without an url, and thus an error message that is not too obvious at first sight.

**Comment by rieder** [comment]
I am not at all sure krome has a complete interface… I’ll have a look.

**Comment by DavidJJansen** [comment]
Probably duplicate of #721 so this issue can be closed.

**Comment by ipelupessy** [comment]
krome is fixed, now clones the repository
