### ISSUE TITLE
 No module named 'amuse.support.codes' when building

### ISSUE THREAD

**Issue by GijsVermarien** [amusecode/amuse#808]
**Describe the bug**
When I try to install AMUSE almost all codes fail to build because of the common error:
```make: Entering directory '/amuse/src/amuse/community/adaptb'
amusifier --type=c interface.py AdaptbInterface -o worker_code.cc
amusifier --type=h -i amuse.support.codes.stopping_conditions.StoppingConditionInterface interface.py AdaptbInterface -o worker_code.h
Traceback (most recent call last):
  File "/usr/local/bin/amusifier", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/amuse/bin/amusifier", line 30, in <module>
    gencode.amusifier()
  File "/amuse/src/amuse/rfi/gencode.py", line 383, in amusifier
    uc.start()
  File "/amuse/src/amuse/rfi/gencode.py", line 248, in start
    self.parse_options()
  File "/amuse/src/amuse/rfi/gencode.py", line 188, in parse_options
    self.options.ignore_classes = list(self.parse_ignore_classes())
  File "/amuse/src/amuse/rfi/gencode.py", line 231, in parse_ignore_classes
    __import__(modulename)
ModuleNotFoundError: No module named 'amuse.support.codes'
make: *** [Makefile:37: worker_code.h] Error 1
make: Leaving directory '/amuse/src/amuse/community/adaptb'
```

**To Reproduce**
Clone main, and try to build using `python setup.py develop_build`

**Expected behavior**
The codes should build

**Logs**
[build.log](https://github.com/amusecode/amuse/files/7667486/build.log)

**Environment (please complete the following information):**
 - OS and version: Ubuntu 20.04
 - Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Additional context**
This is run in a docker container, but when I revert to the last stable release, the problem is solved, so this might not be the issue.

**Comment by rieder** [comment]
Confirmed, I get the same.

**Comment by rieder** [comment]
I reverted #795, now it works again...
