### ISSUE TITLE
Fortran compilation / gcc11 + OS Monterey / MPI types mismatch

### ISSUE THREAD

**Issue by christianboily** [amusecode/amuse#811]
Hi, I have switched to OS Monterey on my mac book and could not reinstall the macports gcc v. 9.3 that I had used before 
under OS Mojave (10.14) ; I cloned Amuse from the main branch @ github, and found some issues linking with the openmpi 
library (-> openmpi + gcc11 is active under a macports install). I have Xcode v 13 and (therefore) mp-clang13 installed. 

There are some fortran codes that mistype their arguments to mpi function calls and that results in compilation failure. I 
edited the Makefiles of these codes (e.g., phigrape, mpiamrvac) and added the fortran  flag (or f90 flag, the case being)  
 
`FFLAGS += -fallow-argument-mismatch `

and the compilation proceeds smoothly, if only with TONS of warnings about argument mismatches, almost always float(8) vs
integer(4). 
The Amuse tests for these codes worked fine however, when a failure was due to a python script / amuse module, and not the 
codes themselves. For example, tests 10 & 11 of mpiamrvac give this output error : 

```
mpiexec -n 1 --oversubscribe pytest --pyargs amuse.test.suite.codes_tests.test_mpiamrvac
>        self.assertTrue(instance.stopping_conditions.timeout_detection.is_set())
> >       rho = instance.itergrids().next().rho[...,0,0]
> E       AttributeError: 'generator' object has no attribute 'next'
```
but all other 25 tests ran through without a glitch. 

I hope this helps somehow. Happy new year, happy new code ...

**Comment by ipelupessy** [comment]
no one commented yet? yea , this is an ongoing issue; I think in most cases we try to fix it with -std=legacy (works on older compilers). note that if there are such errors in interface.f90 or other (eg. the templates) AMUSE code, we should fix the error (but I think these are fixed  already)

**Comment by rieder** [comment]
Odd, I don't get this error at all (also on Monterey / macports gcc11)... But it seems more common than just you @christianboily

**Comment by ipelupessy** [comment]
close if there is no further follow up
