### ISSUE TITLE
channel for equal src and target

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#828]
best to handle this by ignoring the copy
though there cases which could be useful (say copying to a different name)

**Comment by ipelupessy** [comment]
so this concerns  set.new_channel_to(other_set)
with other_set is equal to set

**Comment by rieder** [comment]
I can see no use case for this?

**Comment by ipelupessy** [comment]
yea, its a corner case..I encountered it by accident while debugging..though it may happen if for example you have a number of sets and you want to make sure they all have the same attribute and then you do a loop w/o checking whether the set is different from the source or something
