### ISSUE TITLE
Issue: sudo port gfortran

### ISSUE THREAD

**Issue by guimei-L** [amusecode/amuse#841]
I use the macOS Momterey, I installed Xcode (version 13.3) and the  correspond
command line tool and Macports tool.
And my issue is that when I use the command 
 `sudo port install gcc9 openmpi-gcc9 hdf5 gsl cmake gmp mpfr fftw-3 +gcc9 openblas lapack`
I got an error :

`--->  Building libgcc9
Error: Failed to build libgcc9: command execution failed 
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_gcc9/libgcc9/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there
is a bug.
Error: Processing of port gcc9 failed`

And I wants to know how can I deal with this issue?

**Comment by rieder** [comment]
could you try installing gcc11 instead?

**Comment by guimei-L** [comment]
It works well!&nbsp;
Thank you very much! And I saw the webpage have already changed, you guys are so&nbsp;efficient. I like AMUSE!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amusecode/amuse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amusecode/amuse] Issue: sudo port gfortran (Issue #841)





 could you try installing gcc11 instead?

**Comment by guimei-L** [comment]
But there is another issue with the command 'pip install numpy docutils mpi4py h5py wheel'
I can't install mpi4py, is it the latest version of gcc don't 
support this?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amusecode/amuse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amusecode/amuse] Issue: sudo port gfortran (Issue #841)





 could you try installing gcc11 instead?

**Comment by guimei-L** [comment]
Revolved.
