### ISSUE TITLE
Time values out of sync when too many encounters

### ISSUE THREAD

**Issue by Anit5577** [amusecode/amuse#848]
I am running this code examples/syllabus/gravity_stellar_collision.py (a similar thing happens with the examples/textbook/gravity_stellar_collision.py). When I increase the number N in the simulation (e.g. to 300) creating more collisions/encounters, the timesteps become out of sync with the gravity.model_time.

The following is an extract from the print_diagnostics. The first time information is the time step the simulation has been evolved to, the second is the gravity.model_time. Up to 7 Myr, there is a maximum of 1 collision per timestep, so the two times are in sync. In-between 8 Myr and 9 Myr, there are more than one encounter during this timestep. The simulation then ends at 10 Myr, however the internal "clock" as per the gravity.model_time is only at ~8.7 Myr. So I assume the simulation has not been evolved all the way to 10 Myr, but only to 8.7 Myr?

... T= 7 Myr  - gravity.model_time =  7.00004956543 Myr
At time= 7.30478066786 Myr number of encounters= 1
Resolve encounter Number: 5

T= 8 Myr   - gravity.model_time = 8.00002741777 Myr
At time= 8.33659924721 Myr number of encounters= 1
Resolve encounter Number: 6

T= 9 Myr # gravity.model_time = 8.44684936292 Myr ???
At time= 8.44684976253 Myr number of encounters= 1
Resolve encounter Number: 7

T= 10 Myr, gravity.model_time = 8.69592632714 Myr ???

**Comment by rieder** [comment]
Thanks for alerting us to this Christina!
Indeed this looks like an error in the script.

**Comment by rieder** [comment]
Solved for the examples/textbook version of the script.

**Comment by rieder** [comment]
The issue was that `evolve_model` only evolves until either `time` is reached or until the first collision occurs. If more than one collision is expected in a timestep, the difference between the expected time and the actual model time becomes increasingly large. 
The fixed version continues the evolve step after a collision until the expected time is reached.

**Comment by Anit5577** [comment]
Thanks a lot for solving this issue so quickly. It puzzled for a while and I couldn't figure out if my code that I derived from the example was wrong. I have updated my code as well and it now works as expected (many encounters within a time step).
