### ISSUE TITLE
Amuse installation issue

### ISSUE THREAD

**Issue by dfeigelson** [amusecode/amuse#860]
Hello, I am attempting to install amuse on a brand new mac and am running into some issues. I believe all prerequisites are properly installed, however, when I run `pip install mpi4py` I get the following: 

ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects

Further, when I run `pip install amuse-framework` I get:

ERROR: Could not build wheels for amuse-framework, which is required to install pyproject.toml-based projects

I am not sure if this is related to the mpi4py issue or if both are caused by the same thing, but I think everything else is installed correctly. Please let me know if you have any suggestions.

On a separate note, I tried doing a development build and cloned the directory and installed it. However, when I navigate to it and run `./configure` I get: `configure: error: C compiler cannot create executables`

If I navigate to config.log, I find the following, though I am not sure if it is enlightening:
gcc version 11.2.0 (MacPorts gcc11 11.2.0_3) 
configure:3012: $? = 0
configure:3001: gcc -V >&5
gcc: error: unrecognized command-line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3012: $? = 1
configure:3001: gcc -qversion >&5
gcc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:3012: $? = 1
configure:3032: checking whether the C compiler works
configure:3054: gcc    conftest.c  >&5
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
configure:3058: $? = 1
configure:3096: result: no

I am happy to proceed with either method of installation if one problem is easier to fix.

**Comment by ipelupessy** [comment]
hmm, if the compiler doesn't work, it will also fail for mpi4py - have you tried to compile any simple hellow world c program with gcc?

**Comment by ipelupessy** [comment]
I think the essential bit is "library not found for -lSystem"..if I google for this, it seems to be a common error on mac when the enironment is not setup correctly; I cannot test this, but maybe you can try some of them?

e.g.: https://stackoverflow.com/questions/56156520/gfortran-error-ld-library-not-found-for-lsystem-when-trying-to-compile

(also: when it does work to compile a program is that the same version (11.2.0)?)

**Comment by ipelupessy** [comment]
I think its a system config issue, and propose to close this issue w/o further feedback.
