### ISSUE TITLE
remove set_acceleration from gd.py

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#862]
propose to remove set_acceleration from the gravitational dynamics interface..its hardly implemented anywhere and I am not sure why it is there (no consistent use case..)

**Comment by rieder** [comment]
I don't really see why though. This will be recalculated immediately.

**Comment by ipelupessy** [comment]
yea..

**Comment by rieder** [comment]
Moved the comment to a different issue.
set_acceleration methods in Bonsai do set the acceleration, however it's immediately overwritten so I don't see the point of having them...

**Comment by christianboily** [comment]
Hi Steven, waw that was a quick reply .. It may well be that I am 
messing up the units somehow, but why should the

approach be different for Bonsai, compared to (say) Octgrav or Ph4 ? My 
script is a simple embedding of a galactic disc

(of stars) in a frozen external (halo) potential. The disc is built with 
Agama, but that is not important I don't think. I provide

a converter, i.e. the same set of units used to create the stellar disc, 
and then embed that disc in the halo. As I say, I used

Ph4, .. Phigrape (gpu) , using GPU's - for Octgrav, Phigrape - or mpi. 
It works fine, but performances are not great with N ~ 2^17

= 131k stars or more ; Bonsai handles easily up to 2^19 ~ 400k stars in 
a fraction of the time (it's actually 15 minutes of runtime

compared to 4h for the other codes). But the Bonsai integrator simply 
thinks that the disc is isolated so it is missing a large halo

potential, as used by Agama to integrate [individual] orbits. The disc 
dissolves quickly, when it should be in equilibrium ;(

Cheers,

Chris B.

__________________________________________________________________

Christian Boily            Tel.:  work:       +33-(0)3.68.85.24.36
Observatoire astronomique         home:
11, rue de l'Universite    FAX :              +33-(0)3.68.85.24.17
Strasbourg F-67000         ***@***.***
France                urlhttp://www.rzuser.uni-heidelberg.de/~s17   
------------------------------------------------------------------
