### ISSUE TITLE
asterisk compilation issue

### ISSUE THREAD

**Issue by Yrisch** [amusecode/amuse#865]
Hi,

I tried to compile Asterisk but it seems to crash on a amusifier command that build the jar file : 

`****************************************************************************************************
Building libraries and codes
****************************************************************************************************
****************************************************************************************************
Building code: asterisk, target: all, in directory: src/amuse/community/asterisk
****************************************************************************************************
make[1] : on entre dans le répertoire « /home/yann/Documents/Workspace/AMUSE_GPU/src/amuse/community/asterisk »
#done
make[1] : on quitte le répertoire « /home/yann/Documents/Workspace/AMUSE_GPU/src/amuse/community/asterisk »
****************************************************************************************************
****************************************************************************************************
Building code: asterisk, target: asterisk_worker_java, in directory: src/amuse/community/asterisk
****************************************************************************************************
make[1] : on entre dans le répertoire « /home/yann/Documents/Workspace/AMUSE_GPU/src/amuse/community/asterisk »
Compiling Asterisk Lib
make -C src
make[2] : on entre dans le répertoire « /home/yann/Documents/Workspace/AMUSE_GPU/src/amuse/community/asterisk/src »
Compiling Asterisk
rm -f -r tmp dist
mkdir tmp
mkdir dist
/usr/bin/javac -g -classpath "lib/*:lib/jogl/*"  -d tmp src/nl/esciencecenter/asterisk/AsteriskInterfaceWindow.java src/nl/esciencecenter/asterisk/SPHGas.java src/nl/esciencecenter/asterisk/Sphere.java src/nl/esciencecenter/asterisk/Star.java src/nl/esciencecenter/asterisk/visual/DistanceComparator.java src/nl/esciencecenter/asterisk/visual/StarModel.java src/nl/esciencecenter/asterisk/visual/PlanetModel.java src/nl/esciencecenter/asterisk/visual/PointCloud.java src/nl/esciencecenter/asterisk/visual/SphereModel.java src/nl/esciencecenter/asterisk/Particle.java src/nl/esciencecenter/asterisk/input/AsteriskInputHandler.java src/nl/esciencecenter/asterisk/PointGas.java src/nl/esciencecenter/asterisk/AsteriskGLEventListener.java src/nl/esciencecenter/asterisk/Planet.java src/nl/esciencecenter/asterisk/interfaces/VisualScene.java src/nl/esciencecenter/asterisk/interfaces/SceneStorage.java src/nl/esciencecenter/asterisk/interfaces/TimedPlayer.java src/nl/esciencecenter/asterisk/AsteriskSettings.java src/nl/esciencecenter/asterisk/Asterisk.java src/nl/esciencecenter/asterisk/Snapshot.java src/nl/esciencecenter/asterisk/data/IndexNotAvailableException.java src/nl/esciencecenter/asterisk/data/GlueTimedPlayer.java src/nl/esciencecenter/asterisk/data/GlueSceneStorage.java src/nl/esciencecenter/asterisk/data/GlueDatasetManager.java src/nl/esciencecenter/asterisk/data/GlueScene.java src/nl/esciencecenter/asterisk/data/GlueSceneDescription.java
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Building jar file
/usr/bin/jar -cf dist/asterisk.jar -C tmp .
/usr/bin/jar -uf dist/asterisk.jar images shaders
rm -f -r tmp
done compiling Asterisk
make[2] : on quitte le répertoire « /home/yann/Documents/Workspace/AMUSE_GPU/src/amuse/community/asterisk/src »
amusifier --type=java --mode=class interface.py AsteriskInterface -o Worker.java
amusifier --type=java --mode=interface interface.py AsteriskInterface -o CodeInterface.java
rm -f -r tmp
mkdir tmp
/usr/bin/javac -g -cp "src/lib/*:src/lib/jogl/*:src/dist/*" -d tmp *.java
Building jar file
/usr/bin/jar -cf worker.jar -C tmp .
rm -f -rf tmp
amusifier -x --type=java --mode=script interface.py AsteriskInterface -o asterisk_worker_java
Usage: amusifier [options] name_of_module name_of_class_in_module.
    
    or: amusifier --mode=dir name_of_the_code
    
    This script will generate code from the class with name <name_of_class_in_module>. The
    class must be defined in the module <name_of_module>. The module name
    can be a python file or the python module name.
    
    If mode is dir the script will create a directory with all files
    needed to start creating a code interface.
    
    This script handles all code generation for the AMUSE framework. It can
    be used to create C++ or Fortran code to handle the MPI messages, 
    create a header file or create stub code as a start for defining
    the interface between the code and AMUSE.
    
    Examples
    --------
    To generate code for interfacing with MPI do:
        amusifier --type=c --mode=mpi test.py TestInterface
    or (for fortran):
        amusifier --type=f90 --mode=mpi test.py TestInterface
        
    To generate a header file do (for C):
        amusifier --type=h test.py TestInterface
    or (for C++):
        amusifier --type=H test.py TestInterface
        
    To generate a stub file do:
        amusifier --type=c --mode=stub test.py TestInterface
    or (for fortran):
        amusifier --type=f90 --mode=stub test.py TestInterface
        
    To generate create a directory and put files in it do:
        amusifier --type=c --mode=dir MyCode
    or (for fortran):
        amusifier --type=f90 --mode=dir MyCode
    
    To see a description of all arguments do:
        amusifier --help
    
    

amusifier: error: <class 'AsteriskInterface'> is a built-in class
make[1]: *** [Makefile:90 : asterisk_worker_java] Erreur 2
make[1] : on quitte le répertoire « /home/yann/Documents/Workspace/AMUSE_GPU/src/amuse/community/asterisk »
****************************************************************************************************
********************************************************************************
Building finished
********************************************************************************`
Thank you.

**Comment by ipelupessy** [comment]
yea, its already fixed in one of the upcoming pulls..i can cherry pick the commit if you want..

**Comment by Yrisch** [comment]
Hi,
Yes, It could be great !
Thank you !

**Comment by ipelupessy** [comment]
should be fixed now
