### ISSUE TITLE
[SimpleHash] Python: Command Not Found

### ISSUE THREAD

**Issue by JPGlaser** [amusecode/amuse#875]
**Describe the bug**
The make command for simplehash cannot see the `python` command when system `python3` is used, despite alias being set. 

**To Reproduce**
Run `cd /opt/amuse/ && ./configure --enable-cuda` within the attached singularity container.
[torch.txt](https://github.com/amusecode/amuse/files/9103166/torch.txt)

**Expected behavior**
`simplehash` should be able to see `python`.

**Logs**
```
[10:15:24] building simple_hash-library
error in call, tail output:

make[1]: Entering directory '/opt/amuse/lib/simple_hash'
gcc -g -O2 -fPIC -std=c99 -O2 -fPIC -c -o simple_hash.o simple_hash.c
g++ -O2 -o test_hash test.cpp simple_hash.o


python test.py ./test_hash 123456
make[1]: python: Command not found
make[1]: *** [Makefile:28: test] Error 127
make[1]: Leaving directory '/opt/amuse/lib/simple_hash'
```

**Environment (please complete the following information):**
 - OS and version: Rocky Linux 8.6
 - Compiler: gcc11, python3.9

**Comment by ipelupessy** [comment]
thanks, this has to be fixed..work around is to make sure a link alias from python->python3 exists..

**Comment by ipelupessy** [comment]
fixed
