### ISSUE TITLE
bhtree module not found

### ISSUE THREAD

**Issue by dfeigelson** [amusecode/amuse#876]
Hello, I worked with Steven last week to install amuse on my mac and did this successfully via a development build. However, I am now trying to work through the example interactive session on the installation website, and when I run `from amuse.community.bhtree.interface import BHTree`, I get the following error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'amuse.community.bhtree'`

When I import any of the other three packages, it works perfectly. Furthermore, bhtree successfully installed with the development build, and if I run `make bhtree.code`, whether in a new window or the same session, it builds successfully.

Do you know if this is an issue with my paths, an amuse bug, or something else? Thanks for the help

**Comment by ipelupessy** [comment]
can you confirm the installation its using by e.g. printing
```
import amuse
print(amuse.__file__)
import amuse.community
print(amuse.community.__file__)
```
and checking the corresponding file locations
