### ISSUE TITLE
CoreException: tried to get unknown parameter 'epsilon_squared' for a 'Mikkola' object

### ISSUE THREAD

**Issue by ErwanH29** [amusecode/amuse#880]
Hello. 

I am practicing a bit of AMUSE and trying to run a code originating from another GitHub repository, namely the triple_around_smbh.ipynb notebook from [here](https://github.com/rieder/amuse-tutorial/blob/main/notebooks/3.%20Bridging%20codes/triple_around_smbh.ipynb). When I try to apply Mikkola as my gravitational solver I get:

CoreException: tried to get unknown parameter 'epsilon_squared' for a 'Mikkola' object

I wasn't sure if this is normal, but when I check the Fortran file Mikkola is constructed from I can see that it holds a parameter `mikkola.set_eps2` which defines the softening parameter.

**To Reproduce**
I would like to be able to bridge the system using Mikkola as my gravitational solver rather than Hermite. By applying 
`code = Mikkola(converter)`
`code.set_eps2(epsilon_squared)`
I was hoping the code would run.

**Logs**
`~/amuse/src/amuse/couple/bridge.py in __init__(self, code, field_codes, do_sync, verbose, radius_is_eps, h_smooth_is_eps, zero_smoothing)`
`    323         if not hasattr(self.code,"parameters"):`
`    324             self.zero_smoothing=True`
`--> 325         elif not hasattr(self.code.parameters,"epsilon_squared"):`
`    326             self.zero_smoothing=True`
`    327         else:`

`~/amuse/src/amuse/datamodel/parameters.py in __getattr__(self, name)`
`    308 `
`    309     def __getattr__(self, name):`
`--> 310         return self.convert_from_target_to_source_if_needed(getattr(self._original, name))`
`    311 `
`    312     def __setattr__(self, name, value): `

`~/amuse/src/amuse/datamodel/parameters.py in __getattr__(self, name) `
`     33         #    return object.__getattribute__(self, name) `
`     34         if not name in self._mapping_from_name_to_definition: `
`---> 35             raise exceptions.CoreException("tried to get unknown parameter '{0}' for a '{1}' object".format(name, type(self._instance()).__name__)) `
`     36  `
`     37         self._instance().before_get_parameter()`

` CoreException: tried to get unknown parameter 'epsilon_squared' for a 'Mikkola' object`

**Environment (please complete the following information):**
 - Ubuntu Linux 20.04.3
 - Python 3.8.10

Thanks,
Erwan H

**Comment by ipelupessy** [comment]
At the moment the softening parameter in Mikkola is not exposed (the function set_eps2 and get_eps2 don't do anything). The following steps can be done to add:
- [ ] add a module variable epsilon_squared to module Mikkola in interface.f90, eg. around line 23
- [ ] add corresponding code to set and get this variable to the already existing stubs (line 426 and further in interface.f90)
- [ ] set soft to epsilon_squared**0.5 (instead of zero) at line 327
- [ ] add the parameter definition to define_parameters in interface.py (after line 325), e.g. copy/pasting from rebound interface.py

**Comment by ErwanH29** [comment]
It seems to work now. 
Thank you very much!
