### ISSUE TITLE
Error in SeBa interface when using the function recall_memory_one_step

### ISSUE THREAD

**Issue by silviatoonen** [amusecode/amuse#890]
I believe there is a bug in the SeBa interface when using the function recall_memory_one_step.
The interface uses a parameter called seba_time. Every timestep this parameter is updated to the end_time (see the function evolve_system in interface.cc). However, when recall_memory_one_step is called it is not reset. As a result I'm running into the situation that after the recall, when the new needed timestep is calculated in evolve_system, the timestep is negative. Consequently SeBa keeps on running as the end_time is never reached (while loop is never broken).

Suggested solution: I suggest we set the seba_time to the current_time at the end of the recall_memory_one_step function, e.g.:
seba_time = seba_node->get_starbase()->get_current_time() - seba_node->get_starbase()->get_time_offset();

**Comment by spzwart** [comment]
Ok. Let's have a look how this works. I am still not 100% sure that this shouldn't be the relative_age, but lets design a small test to figure this out.
