### ISSUE TITLE
MESA community codes need individual pip packages

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#892]
Currently, we have one amuse-mesa package (which doesn't work). This is not ideal, since it is unclear which MESA this will install.
I think it's probably best to have individual packages for mesa_r15140 and mesa_r2208, and also a package amuse-mesa which will depend on mesa_r15140 (I don't think it's possible to have an "or" dependency, so I'd choose the newer one).

**Comment by rieder** [comment]
suggested package names:
amuse-mesa-r15140 (installs amuse.community.mesa_r15140)
amuse-mesa-r2208 (installs amuse.community.mesa_r2208)
amuse-mesa (depends on amuse-mesa-r15140, installs amuse.community.mesa)

**Comment by rieder** [comment]
@ipelupessy do you agree with the above?

**Comment by rjfarmer** [comment]
Is the plan here to bundle a fully compiled MESA with all its data files into a python package?

**Comment by rieder** [comment]
No, that would not work.
