### ISSUE TITLE
Buggy line at "config.py" in the amuse directory

### ISSUE THREAD

**Issue by MariosGkMeng** [amusecode/amuse#894]
**Describe the bug**
There is a conditional: "if value.startswith("@") and value.endswidth("@")",
wherein it should have been "if value.startswith("@") and value.endswith("@")" 
in script: "config.py"

**Comment by stephenpcook** [comment]
https://github.com/amusecode/amuse/blob/b7fe00fb8cb235ecee3f716fe967c3790a935c22/src/amuse/config.py#L22

**Comment by rieder** [comment]
ah, width should be with of course! thanks for reporting!

**Comment by rieder** [comment]
Please feel free to create a PR fixing things like this in the future :). Always good to see more people help with development and bug fixing!
