### ISSUE TITLE
mpiexec -np doesn't always work

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#90]
when starting with sockets channel an mpi enabled code it does e.g. a 
mpiexec -np 2 worker_name

"-np" doesn't always work (can be -n)??

**Comment by ipelupessy** [comment]
related issue is that mpiexec may not be always be present at configure time
(e.g. on the ECMWF cray supercomputer), so detection at configure time is tricky

**Comment by arjenve** [comment]
Well the standard suggests "-n" (http://mpi-forum.org/docs/mpi-2.1/mpi21-report-bw/node193.htm)
So we'll make it -n by default and configurable through amuserc and code

**Comment by ipelupessy** [comment]
ok, seems like a good idea! thanks..
