### ISSUE TITLE
"Python interpreter is too old"

### ISSUE THREAD

**Issue by edrick-afk** [amusecode/amuse#907]
I managed to pip install all the prerequisite packages and python itself through macport. However, when I was installing amuse-framework, it says that 

private/var/folders/h_/b0h3s3qj17385z8tn9smvfs40000gn/T/pip-build-env-y8fky0t5/overlay/lib/python3.9/site-packages/setuptools/command/build.py:31: SetuptoolsDeprecationWarning:
                              It seems that you are using `distutils.command.build` to add
                              new subcommands. Using `distutils` directly is considered deprecated,
                              please use `setuptools.command.build`.

Also, when it is checking if the version of my python interpreter is >=3.5, the output is "no", even though I got Python 3.9.15
 after typing $ python --version:

 checking whether /Users/edrick/Downloads/Emory Classes/PHYS Lab/Amuse-env/bin/python3 version is >= 3.5... no
                  configure: error: Python interpreter is too old

[Setuptools deprecation.pdf](https://github.com/amusecode/amuse/files/10079944/Setuptools.deprecation.pdf)

Is there any reason why my computer can't seem to recognize that the python version is high enough? And how do i resolve the setuptools deprecation warning?

**Comment by rieder** [comment]
Don't worry about the setuptools warning - it's a warning, not an error.
As for python, could you check the output of ```
/Users/edrick/Downloads/Emory Classes/PHYS Lab/Amuse-env/bin/python3 --version
```
?
I expect it is indeed an older version.
If so, please remove the virtual environment and create it again with the right (newer) Python.

**Comment by edrick-afk** [comment]
I thought so too, so I checked the version right after. But it does in fact says 3.9.15...I don't know why my computer thinks the version is not high enough. Here are the commands I ran in terminal:
`edrick@Edricks-MacBook-Air ~ % cd /Users/edrick/Downloads/Emory\ Classes/PHYS\ Lab/Amuse-env/bin 
edrick@Edricks-MacBook-Air bin % python3 --version
Python 3.9.15
`

**Comment by rieder** [comment]
You have to type exactly `/Users/edrick/Downloads/Emory Classes/PHYS Lab/Amuse-env/bin/python3 --version`, the way you typed it will not call the python in that directory...

**Comment by edrick-afk** [comment]
I got the same output:
edrick@Edricks-MacBook-Air ~ % /Users/edrick/Downloads/Emory\ Classes/PHYS\ Lab/Amuse-env/bin/python3 --version
Python 3.9.15

**Comment by rieder** [comment]
That's very odd.
Could you try deleting the entire pip cache?
`rm -r /Users/edrick/Library/Caches/pip/`
And then first try installing just `amuse-framework`:
`pip install amuse-framework`

**Comment by edrick-afk** [comment]
Still does not work.
[11:24-10;19.pdf](https://github.com/amusecode/amuse/files/10086779/11.24-10.19.pdf)

**Comment by edrick-afk** [comment]
Installing and setting python 3.10 as default (instead of 3.9) also does not help. Still says the same configure error.

**Comment by rieder** [comment]
Have you set any environment variables that might be interfering, e.g. PYTHONPATH?

**Comment by edrick-afk** [comment]
No I have not (I do not know how to set up environment variables). I simply did `python3 -m venv Amuse-env`, and activated it right after.
Also, it seems like the "configure error: python interpreter is too old" could just mean the python interpreter is not found. Would that be possible in this case? I don't know if me having downloaded anaconda has affected anything (I have uninstalled anaconda for now just to make sure it is not interfering with anything).

**Comment by dnrgodilano7** [comment]
Hi, I'm also having the same problem. My python version is 3.9.13.
I used: export AMUSE_ALLOW_BUILD_FAILURES=all
Some libraries were installed but libraries like MESA has the error:

It seems that you are using `distutils.command.build` to add
                  new subcommands. Using `distutils` directly is considered deprecated,
                  please use `setuptools.command.build`.

so when it starts building it gets:

error: could not create 'build/lib/amuse/community/mesa_r15140/mesa_worker': No such file or directory

Thanks!

**Comment by rieder** [comment]
(bug title updated)

**Comment by rieder** [comment]
> Hi, I'm also having the same problem. My python version is 3.9.13. I used: export AMUSE_ALLOW_BUILD_FAILURES=all Some libraries were installed but libraries like MESA has the error:
> 
> It seems that you are using `distutils.command.build` to add new subcommands. Using `distutils` directly is considered deprecated, please use `setuptools.command.build`.
> 
> so when it starts building it gets:
> 
> error: could not create 'build/lib/amuse/community/mesa_r15140/mesa_worker': No such file or directory
> 
> I was able to use the other packages and work on some examples.
> 
> Thanks!

This is not the same issue. The deprecation warning is unrelated to the issue here (Python reported to be too old). The MESA error is again a different error (related to or the same as other MESA errors that have been reported).

**Comment by rieder** [comment]
> No I have not (I do not know how to set up environment variables). I simply did `python3 -m venv Amuse-env`, and activated it right after.

Could you post the output of `export` here?

> Also, it seems like the "configure error: python interpreter is too old" could just mean the python interpreter is not found. Would that be possible in this case? 

I don't think that's the case.

> I don't know if me having downloaded anaconda has affected anything (I have uninstalled anaconda for now just to make sure it is not interfering with anything).

Quite likely. AMUSE and Anaconda don't work well together I'm afraid...
It will quite likely help if you deactivate any Anaconda environment you have active, then re-install AMUSE in a Python virtual environment (following the instructions in the AMUSE documentation for creating this environment).

**Comment by edrick-afk** [comment]
> Could you post the output of export here?
`(Amuse-env) edrick@Edricks-MacBook-Air PHYS Lab % export
HOME=/Users/edrick
LANG=en_US.UTF-8
LOGNAME=edrick
OLDPWD='/Users/edrick/Downloads/Emory Classes/PHYS Lab'
PATH='/Users/edrick/Downloads/Emory Classes/PHYS Lab/Amuse-env/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin'
PS1='(Amuse-env) %n@%m %1~ %# '
PWD='/Users/edrick/Downloads/Emory Classes/PHYS Lab'
SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
SHELL=/bin/zsh
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.7h4ITPKNCi/Listeners
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=445
TERM_SESSION_ID=DCC2C2D2-779F-4918-B44F-92F6BA9E8860
TMPDIR=/var/folders/h_/b0h3s3qj17385z8tn9smvfs40000gn/T/
USER=edrick
VIRTUAL_ENV='/Users/edrick/Downloads/Emory Classes/PHYS Lab/Amuse-env'
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
__CFBundleIdentifier=com.apple.Terminal
`

> It will quite likely help if you deactivate any Anaconda environment you have active, then re-install AMUSE in a Python virtual environment (following the instructions in the AMUSE documentation for creating this environment).

Yes this is what I did. Before I activated the current amuse environment, I cleared all traces of anaconda by following their instructions and also uninstalled the app.
