### ISSUE TITLE
Mercury stalls after setting output files

### ISSUE THREAD

**Issue by jilkoval** [amusecode/amuse#91]
It seems that Mercury gets stuck after the parameters for output files are set. While it seems to work fine with the default values (_/dev/null_ for all output files), when any of the parameters __close_encounters_file__, __bigbody_file__, __smallbody_file__, __integration_parameters_file__, or __restart_file__ is set to some other path, the code stalls. The minimal example works fine until the bit changing the output files is in:

```
import os
from amuse.units import units
from amuse.ext.solarsystem import new_solar_system
from amuse.community.mercury.interface import Mercury

solsys = new_solar_system()
mercury = Mercury()
mercury.particles.add_particles(solsys)

### changing mercury output files path stalls the code
#~ names=["close_encounters_file", 
       #~ "bigbody_file",
       #~ "smallbody_file",
       #~ "integration_parameters_file",
       #~ "restart_file"]
#~ for name in names:
    #~ setattr(mercury.parameters,name,os.path.join('./',name))

print mercury.parameters

mercury.evolve_model(6.66|units.yr)
mercury.stop()
```

**Comment by jilkoval** [comment]
The problem disappears if the files already exist (and the output is appended in such case).

**Comment by ipelupessy** [comment]
there was a bug in the code that created the files if  not present; fixed now..atm it will always append the files already present, is this ok? (it could also overwrite the files)

**Comment by jilkoval** [comment]
I see, thanks! I think appending is all-right (at least for me).
