### ISSUE TITLE
Boolean attributes issue

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#93]
Codes with parrticle boolean attributes cause an issue with some versions of numpy, it relates to the fact that codes return int8 for boolean output arguments, while if a particle set with a boolean attribute cannot be set with an int8 array. An example of this is the test of secularmultiple code.

**Comment by ipelupessy** [comment]
it would be good to have attributes of boolean type not converted to integer for code interfaces...

**Comment by rieder** [comment]
Maybe this is fixed now @ipelupessy?

**Comment by ipelupessy** [comment]
not fixed afaik
