### ISSUE TITLE
How to set eps2 for kicking particles with FastKick in bridge?

### ISSUE THREAD

**Issue by ReinosoB** [amusecode/amuse#937]
I want to bridge two codes but perform the kicks using FastKick with bridge.
I noted that FastKick will adopt the value of  eps2 of the code from which the particles are passed,
but cannot set this value for FastKick independently.
What is the correct way of doing this? 
Here is the method I follow:

`from amuse.lab import *`
`from amuse.community.ph4.interface import ph4`
`from amuse.community.fastkick.interface import FastKick`
`from amuse.couple import bridge`
`import numpy`

`eps=500.|units.AU`
`conv=nbody_system.nbody_to_si(1.|units.MSun,1000.|units.AU)`

`star1=Particles(1)`
`star1.mass=1.|units.MSun`
`star1.position=[0.,0.,0.]|units.AU`
`star1.velocity=[0.,0.,0.]|units.kms`

`star2=Particles(1)`
`star2.mass=1.|units.MSun`
`star2.position=[1000.,0.,0.]|units.AU`
`star2.velocity=[0.,0.,0.]|units.kms`

`nbody1=ph4(conv)`
`nbody1.initialize_code()`
`#nbody1.parameters.epsilon_squared=(eps)**2`
`nbody1.particles.add_particles(star1)`

`nbody2=ph4(conv)`
`nbody2.initialize_code()`
`#nbody2.parameters.epsilon_squared=(eps)**2`
`nbody2.particles.add_particles(star2)`

`#Kick with FastKick`
`def new_code_to_calculate_gravity():  ## Use FastKick.....`
`   result = FastKick(conv)`
`   result.parameters.epsilon_squared=eps**2`
`   return result`

`gravity_from_star1 = bridge.CalculateFieldForCodes(`
`     new_code_to_calculate_gravity,              # the code that calculates the acceleration field`
`     input_codes=[nbody1],                       # the codes to calculate the acceleration field of`
`     required_attributes=['mass', 'x','y','z', 'vx','vy','vz']`
`     )`

`gravity_from_star2 = bridge.CalculateFieldForCodes(`
`     new_code_to_calculate_gravity,              # the code that calculates the acceleration field       `
`     input_codes=[nbody2],                       # the codes to calculate the acceleration field of`
`     required_attributes=['mass', 'x','y','z', 'vx','vy','vz']`
`     )`

`integrator=bridge.Bridge(verbose=True,timestep=1.|units.yr,use_threading=False)`
`integrator.add_system(nbody1,(gravity_from_star2,))`
`integrator.add_system(nbody2,(gravity_from_star1,))`

`#Get acceleration on each star....`
`#accel on star 1`
`ac1x,ac1y,ac1z=integrator.get_gravity_at_point(0.*eps,star1.x,star1.y,star1.z)`
`#accel on star 2`
`ac2x,ac2y,ac2z=integrator.get_gravity_at_point(0.*eps,star2.x,star2.y,star2.z)`

`ac1=numpy.sqrt( ac1x.value_in(units.km/units.s**2)**2 + ac1y.value_in(units.km/units.s**2)**2 + ac1z.value_in(units.km/units.s**2)**2  )`
`ac2=numpy.sqrt( ac2x.value_in(units.km/units.s**2)**2 + ac2y.value_in(units.km/units.s**2)**2 + ac2z.value_in(units.km/units.s**2)**2  )  `

`##Now accelration using Plummer smoothing `
`acc=-constants.G*star1.mass*(star2.position-star1.position)/( (star2.position-star1.position).lengths()**2 + eps**2  )**(3./2.)`
`acg=acc.lengths().value_in(units.km/units.s**2)`

`print('accelerations from bridge:')`
`print('on star1:',ac1,'km/s**2')`
`print('on star2:',ac2,'km/s**2')`
`print('Acceleration with Plummer smoothing:')`
`print('on each star:',acg,'km/s**2')`

Note that changing eps won't change the results delivered by bridge, unless it is set in the ph4 codes

**Comment by rieder** [comment]
Hi,

Indeed, the softening is taken from the source code and not from the kicker code.
This is done by Bridge.
Currently, a way to work around this would be to use the `h_smooth` or `radius` property of the stars for the softening length (note that these may be used for other things as well so this is at your own risk).
You can use these by adding a system to Bridge with either of these set to True: `radius_is_eps=False, h_smooth_is_eps=False`

**Comment by spzwart** [comment]
Hmm,
Interesting point, Reinoso Astro,
In the source code, amuse/src/amuse/community/fastkick//interface.cc, the
eps2 parameter seems to be propagated properly, and also the setters and
getters for eps2 work.
Inti/Steven: do you have an idea what goes amiss here?

Cheers,
Simon

**Comment by fredt00** [comment]
Hi,

I have a similar problem where I want to manually set the softening length used for force calculation in bridge (independent of the codes being bridged). The code I'm using has no attribute for h_smooth and I get the error `amuse.support.exceptions.AmuseException: Cannot set attributes ['h_smooth']`. However, I don't want to set the radius attribute as this would impact the star cluster evolution. Have there been any developments or other work arounds for this problem?
