### ISSUE TITLE
Mercury build crashes for increased code parameters

### ISSUE THREAD

**Issue by jilkoval** [amusecode/amuse#97]
I changed some default parameters for Mercury (maximum number of particles etc.), see [mercury.inc here](https://github.com/jilkoval/amuse/blob/mercury/src/amuse/community/mercury/src/mercury.inc#L20). After the change, the build of mercury (using `make mercury.code`) crashes with the following error:
```
... : relocation truncated to fit: R_X86_64_PC32 against `.bss'
... : additional relocation overflows omitted from the output
```
After some google search, I suspect this might be due to allocating some big arrays which could be fixed by adding necessary flags to the fortran compiler (see e.g. [here](http://stackoverflow.com/questions/20687170/fortran-array-implementation-error)) in the Makefile. However, I struggle to make it work (I'm not exactly sure where exactly to add the flags, actually).
Thanks!

**Comment by ipelupessy** [comment]
I can get a little bit further by: FFLAGS+= -mcmodel=medium in the mercury/Makefile
but then it gives a similar error in the stopcond library (which is weird)

**Comment by jilkoval** [comment]
Your fix works for me. ([the modified Makefile](https://github.com/jilkoval/amuse/commit/92c6e5de16b6436a5a4b02d29a71862b91a7723a)). Mercury compiles ok on two different machines...

**Comment by jilkoval** [comment]
hmmm, Mercury compiles ok but stalls during initialization (`code=Mercury()`).

**Comment by ipelupessy** [comment]
I couldn't finish build with the flag (complains when linking against stopcond, rebuilding this with the same flag didn't help), which compiler are you using? is there any output, have you tried running in the debugger? I am not sure what the issue is exactly, if its the automatic arrays in the subroutines I think having them allocated as heap arrays (-heap-arrays for the intel compiler) should also work (but it doesn't...)

**Comment by jilkoval** [comment]
I don't get any error message, but I haven't tired in debugger yet (will try). I use gfortran (at least that's what in my config.status).

**Comment by ipelupessy** [comment]
it builts and starts on thestrw machines - the only difference I could see (apart from having more recent compilers and gfortran) was that it also builts the stopcond and forsockets libraries etc with -fPIC...

**Comment by jilkoval** [comment]
hmm, on my strw machine (kwistbeek), Mercury doesn't start (it compiles though). The compiler is gfortran too and there is FCFLAGS=-g -O2 -fPIC in config.mk.
I just noticed I actually did F77FLAGS+= -mcmodel=medium, but the result is the same with F7FLAGS+= -mcmodel=medium.

**Comment by rieder** [comment]
Need to try this again with current machines and compilers...
