### ISSUE TITLE
Could not build wheels for amuse-Athena, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by BOOM5s** [amusecode/amuse#970]
Hello sir,
I have already "pip install pyproject-toml" but again it is showing error in installing Athena, bhtree ,fi ,galacties ,hop and simplex.
below i have attached the script

[amuse.txt](https://github.com/amusecode/amuse/files/11988789/amuse.txt)

**Comment by rieder** [comment]
Closed - see #971
