### ISSUE TITLE
Amuse sockets channel - print address after resolving host names

### ISSUE THREAD

**Issue by fjansson** [amusecode/amuse#99]
On one machine where I installed Amuse, the MPI channel worked fine, but the sockets channel didn't. Amuse and the worker code just wouldn't connect to each other, both processes waited until a 60 s timeout was reached.

The reason turned out to be that I had an old alias in /etc/hosts, resolving my locally defined host name to an invalid IP address. The worker code then got this invalid IP address when resolving the host name, at line 1308 in worker_code.cc: server = gethostbyname(host);

This is not an Amuse bug - but additional messages would be helpful when debugging. For example, printing the resolved IP address in the worker code. Thanks to Inti for debugging this with me.

One way to print the IP address:
#include <arpa/inet.h>
...
server = gethostbyname(host);  //worker_code.cc line ~1308
printf("Host name: %s\n", host);
printf("IP address: %s\n", inet_ntoa( *(in_addr*) server->h_addr));

and an alternative without adding another include file:
  printf("IP address: %u.%u.%u.%u\n",
	   (unsigned char)server->h_addr[0], (unsigned char)server->h_addr[1],
	   (unsigned char)server->h_addr[2], (unsigned char)server->h_addr[3]);

Related - The gethostbyname manpage states:
> The gethostbyname*(), gethostbyaddr*(), herror(), and hstrerror() functions are obsolete.  Applications should use getaddrinfo(3), getnameinfo(3), and  gai_strerror(3) instead.

Also, gethostbyname returns an array of addresses, h_addr is the first of them. h_addr_list contains them all.

**Comment by ipelupessy** [comment]
I agree - some more reporting of this would also work when encountering similar issues with the /etc/hosts file on OSX i think....

**Comment by ipelupessy** [comment]
fixed by 09af2e7
